### ISSUE TITLE
LWS_CALLBACK_CLOSED sometimes is called twice

### ISSUE THREAD

**Issue by shevvit** [warmcat/libwebsockets#1066] opened 2017-10-24 08:34 UTC
Sometimes I see such messages in lwsws's stdout:

lwsws[6107]: CLOSING wsi 0x1008940, pss 0x100cde0 ********
lwsws[6107]: CLOSING wsi 0x1008940, pss (nil) ********

I don't do any magic, it's just a little changed protocol_lws_status.c with adding hash table to store id:wsi_pointer addresses.

Is it a bug or I do something wrong?
Btw, Does lws have builtin hashtab to store wsi? I want to find right *wsi by some id to send message  with lws_callback_on_writable(wsi).

Thanks!

**Comment by lws-team** [comment] 2017-10-24 08:41
Can you tell me a little bit more about when you see this?  You are closing a browser window on lws_status?

On master there is no string like that in lws itself AFAICS.

There is either a map or hashtable implemented in lws for fd -> wsi.  I guess it depends on what you need to do, but usually a linked-list in the pss is effective and cheap.

**Comment by lws-team** [comment] 2017-10-24 12:27
I added this on master

```
diff --git a/plugins/protocol_lws_status.c b/plugins/protocol_lws_status.c
index d9240cae..2ad43cbe 100644
--- a/plugins/protocol_lws_status.c
+++ b/plugins/protocol_lws_status.c
@@ -207,6 +207,7 @@ walk_final:
                break;
 
        case LWS_CALLBACK_CLOSED:
+               lwsl_notice("%s: closed\n", __func__);
                pss1 = vhd->live_pss_list;
                pss2 = NULL;
 
```

and when I close the browser window, it looks like this at -d 255 

```
lwsws[5594]: lws_handle_POLLOUT_event: non http2
lwsws[5594]: lws_callback_on_writable: 0x8de3a0
lwsws[5594]: lws_handle_POLLOUT_event: non http2
lwsws[5594]: lws_callback_on_writable: 0x8de3a0
lwsws[5594]: lws_handle_POLLOUT_event: non http2
lwsws[5594]: lws_callback_on_writable: 0x8de3a0
lwsws[5594]: lws_handle_POLLOUT_event: non http2
lwsws[5594]: lws_callback_on_writable: 0x9b73c0
lwsws[5594]: lws_read: read_ok, used 8
lwsws[5594]: lws_callback_on_writable: 0x9b12e0
lwsws[5594]: lws_read: read_ok, used 8
lwsws[5594]: lws_callback_on_writable: 0x8de3a0
lwsws[5594]: lws_read: read_ok, used 8
lwsws[5594]: lws_service_fd: closing
lwsws[5594]: 0x9b73c0: end FLUSHING_STORED_SEND_BEFORE_CLOSE
lwsws[5594]: lws_same_vh_protocol_remove: removing same prot wsi 0x9b73c0
lwsws[5594]: have prev 0x63bc10, setting him to our next (nil)
lwsws[5594]: ah det due to close
lwsws[5594]: lws_service_fd: closing
lwsws[5594]: 0x9b12e0: end FLUSHING_STORED_SEND_BEFORE_CLOSE
lwsws[5594]: lws_same_vh_protocol_remove: removing same prot wsi 0x9b12e0
lwsws[5594]: have prev 0x63bbf8, setting him to our next (nil)
lwsws[5594]: callback_lws_status: closed <<<<======================
lwsws[5594]: lws_service_fd: closing
lwsws[5594]: 0x8de3a0: end FLUSHING_STORED_SEND_BEFORE_CLOSE
lwsws[5594]: lws_same_vh_protocol_remove: removing same prot wsi 0x8de3a0
lwsws[5594]: have prev 0x63bc38, setting him to our next (nil)
lwsws[5594]: ah det due to close
lwsws[5594]: ah det due to close
lwsws[5594]: closing 0x9b9f80: parent (nil)
lwsws[5594]: lws_same_vh_protocol_remove: removing same prot wsi 0x9b9f80
lwsws[5594]: ah det due to close
^Ckilling service processes
```

If there's something I'm missing please let me know more info on how to reproduce.

**Closed by lws-team** 2017-10-24 12:27 UTC
