### ISSUE TITLE
Slow Web Server Responce

### ISSUE THREAD

**Issue by udenaka** [warmcat/libwebsockets#875] opened 2017-04-19 07:06 UTC
Hi,

I am trying to use the 2.2 stable version and and experiencing slow responses when making multiple http-request form the server simultaneously (2.0 seems to be much faster in this aspect) with ssl enable. I am also observing spike in CPU usage as well (when switch from 2.0  to 2.2 stable versions).

Recreate the issue in test server

run the  "libwebsockets-test-server -ssl" in 2.0 version and refresh (CTRL+R) rapidly. No CPU spikes in CPU usage and Fully responsive web page with active web-socket connection.

run the  "libwebsockets-test-server -ssl" in 2.2 version and refresh (CTRL+R) rapidly. After few refreshing spikes in CPU usage and Unresponsive web page with inactive-web-socket connection.

**Comment by lws-team** [comment] 2017-04-19 12:54
Is the problem still there on latest v2.2-stable or master?

**Comment by udenaka** [comment] 2017-04-19 15:05
Hi,

I am facing this issue with the  latest v2.2-stable branch.

**Comment by lws-team** [comment] 2017-04-19 23:27
I cannot reproduce it... this is on Linux or something else?

**Comment by udenaka** [comment] 2017-04-20 03:09
I am facing this on Ubuntu 16.04 and Arch Linux arm version.  I install he 2.0 stable and 2.1 stable in a another ubuntu 16.04 and get the similar result.

When I monitor the web server running (in ssl mode) PCs System monitor while continuously refreshing the webpage (webpage open in another PC **https://web_server_ip:7681/** ) , In 2.2 stable I am seeing one cpu-core goes to 100% and web server stop responding. but in 2.0 stable It runs smoothly.

**Comment by lws-team** [comment] 2017-04-20 03:11
Your "v2.2-stable" is at 2238857ea43730bb51476946bdc32319fe2d6cca is it?

**Comment by udenaka** [comment] 2017-04-20 03:14
Hi, 

Yes. It is at  2238857. I did the new test 30 minutes before with fresh download.

**Comment by mmilata** [comment] 2017-05-02 23:21
Tried running `libwebsockets-test-server --ssl` from v2.2-stable (a68539492f6bace6bae48e8e28fc52ad695b1441) and refreshing rapidly couple of times in browser but did not notice any abnormal CPU usage.

**Comment by lws-team** [comment] 2017-05-02 23:24
@mmilata thanks for the confirmation... will close this then.  @udenaka if you get any new info (such as where it spins...) please add it here.

**Closed by lws-team** 2017-05-02 23:24 UTC
