### ISSUE TITLE
firefox/chrome disconnects when ws payload is big

### ISSUE THREAD

**Issue by alexeadem** [warmcat/libwebsockets#2529] opened 2021-12-20 22:02 UTC
I'm using v4.3-stable and  lws-mirror-protocol. 
When ws payload is 11900 firefox, chrome and lws client all work just fine. 
When ws payload is 23371 firefox and chrome disconnects and lws client works fine when the message gets mirrored to all wsi(s)

LWS CLIENT
`wsi %p = 0x688ef (lws client 4.3.0-v4.3.0-78-g33007a2f4 ) => ALL GOOD`
```
2021-12-20T19:13:45.141760+00:00 d13 api U: qbo.c:1182 1bc2ad31 0x688ef60 LWS_CALLBACK_SERVER_WRITEABLE vhost = proxy, status = 200
2021-12-20T19:13:45.143591+00:00 d13 api I: qbo.c:1235 1bc2ad31 0x688ef60 tx len = 23371
2021-12-20T19:13:45.144448+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: ssl_capable_write (4116) says 4116
2021-12-20T19:13:45.144633+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: new partial sent 4116 from 23375 total
2021-12-20T19:13:45.145277+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: _lws_change_pollfd: fd 15 events 1 -> 5
2021-12-20T19:13:45.145554+00:00 d13 api U: qbo.c:1303 1bc2ad31 0x688ef60 CMD_GET
2021-12-20T19:13:45.146070+00:00 d13 api U: qbo.c:5223 1bc2ad31 wsi = 0x688ef60 thread_id = 104908544 status 0
2021-12-20T19:13:45.157499+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: _lws_change_pollfd: fd 15 events 5 -> 5
2021-12-20T19:13:45.159039+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lws_service_fd_tsi: Close and handled
2021-12-20T19:13:45.159310+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: __lws_close_free_wsi: caller: close_and_handled
2021-12-20T19:13:45.159496+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: __lws_close_free_wsi: LRS_FLUSHING_BEFORE_CLOSE
2021-12-20T19:13:45.159705+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lwsi_set_state: lwsi_set_state 0x20000119 -> 0x2000011e
2021-12-20T19:13:45.159929+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: __lws_set_timeout: 5 secs, reason 12
2021-12-20T19:13:45.270530+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: draining 19259
2021-12-20T19:13:45.271672+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: ssl_capable_write (4116) says 4116
2021-12-20T19:13:45.271831+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: partial adv 4116 (vs 19259)
2021-12-20T19:13:45.271977+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: _lws_change_pollfd: using leave_pollout_active
2021-12-20T19:13:45.392368+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: draining 15143
2021-12-20T19:13:45.393266+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: ssl_capable_write (4116) says 4116
2021-12-20T19:13:45.393422+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: partial adv 4116 (vs 15143)
2021-12-20T19:13:45.393612+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: _lws_change_pollfd: using leave_pollout_active
2021-12-20T19:13:45.479409+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: draining 11027
2021-12-20T19:13:45.480174+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: ssl_capable_write (4116) says 4116
2021-12-20T19:13:45.480338+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: partial adv 4116 (vs 11027)
2021-12-20T19:13:45.480488+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: _lws_change_pollfd: using leave_pollout_active
2021-12-20T19:13:45.580218+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: draining 6911
2021-12-20T19:13:45.581008+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: ssl_capable_write (4116) says 4116
2021-12-20T19:13:45.581156+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: partial adv 4116 (vs 6911)
2021-12-20T19:13:45.581338+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: _lws_change_pollfd: using leave_pollout_active
2021-12-20T19:13:45.675981+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: draining 2795
2021-12-20T19:13:45.677075+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: ssl_capable_write (2795) says 2795
2021-12-20T19:13:45.677334+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: partial adv 2795 (vs 2795)
2021-12-20T19:13:45.677626+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: buflist_out flushed
2021-12-20T19:13:45.677824+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: *signalling to close now
2021-12-20T19:13:45.678008+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_handle_POLLOUT_event: signalling to close
2021-12-20T19:13:45.678169+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lws_service_fd_tsi: Close and handled
2021-12-20T19:13:45.678347+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: __lws_close_free_wsi: caller: close_and_handled
2021-12-20T19:13:45.678524+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: __lws_close_free_wsi:  end LRS_FLUSHING_BEFORE_CLOSE
2021-12-20T19:13:45.678698+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: __lws_close_free_wsi: real just_kill_connection A: (sockfd 15)

```
FIREFOX
```
 wsi %p = 0x59a03d0 (Mozilla/5.0 (X11; Fedora; Linux x86_64; rv:91.0) Gecko/20100101 Firefox/91.0) => DISCONNECTS

/* write start payload size 23371 */
2021-12-20T19:13:45.129843+00:00 d13 api U: qbo.c:1182 1bc2ad31 0x59a03d0 LWS_CALLBACK_SERVER_WRITEABLE vhost = proxy, status = 0

2021-12-20T19:13:45.144448+00:00 d13 api I: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: ssl_capable_write (4116) says 4116
2021-12-20T19:13:45.144633+00:00 d13 api D: [wsisrv|8|adopted|0x688ef]: lws_issue_raw: new partial sent 4116 from 23375 total
2021-12-20T19:13:45.144853+00:00 d13 api I: buflist.c:59 lws_buflist_append_segment: len 19259 first 1 (nil)
2021-12-20T19:13:45.145035+00:00 d13 api D: alloc.c:121 _realloc: size 19300: lws_buflist_append_segment
2021-12-20T19:13:45.134260+00:00 d13 api I: http2.c:634 lws_h2_tx_cr_get: [wsisrv|2|adopted]: own tx credit 12045338: nwsi credit 12045338
2021-12-20T19:13:45.134492+00:00 d13 api I: [wsisrv|2|adopted]: lws_wsi_mux_mark_parents_needing_writeable: sid 0, pending writable
2021-12-20T19:13:45.134709+00:00 d13 api D: [wsisrv|2|adopted]: _lws_change_pollfd: fd 11 events 1 -> 5
2021-12-20T19:13:45.134907+00:00 d13 api U: qbo.c:1283 1bc2ad31 instance unlock }
...
2021-12-20T19:13:45.160208+00:00 d13 api I: ops-h2.c:116 rops_handle_POLLIN_h2: [wsisrv|2|adopted] wsistate 0x20000119, events 5, revents 5, pollout 4
2021-12-20T19:13:45.160497+00:00 d13 api D: [wsisrv|2|adopted]: lws_issue_raw: draining 19268
2021-12-20T19:13:45.161619+00:00 d13 api I: [wsisrv|2|adopted]: lws_issue_raw: ssl_capable_write (4116) says 4116
2021-12-20T19:13:45.161827+00:00 d13 api I: [wsisrv|2|adopted]: lws_issue_raw: partial adv 4116 (vs 19268)
2021-12-20T19:13:45.161971+00:00 d13 api D: ops-h2.c:761 already pending writable
2021-12-20T19:13:45.162142+00:00 d13 api I: http2.c:634 lws_h2_tx_cr_get: [wsisrv|2|adopted]: own tx credit 12045338: nwsi credit 12045338
2021-12-20T19:13:45.162345+00:00 d13 api I: [wsisrv|2|adopted]: lws_wsi_mux_mark_parents_needing_writeable: sid 0, pending writable
2021-12-20T19:13:45.162560+00:00 d13 api D: [wsisrv|2|adopted]: _lws_change_pollfd: using leave_pollout_active
2021-12-20T19:13:45.162718+00:00 d13 api I: ops-h2.c:187 rops_handle_POLLIN_h2: has buffered out
...
/* In wireshark you can see a SYN/FIN send from the browser to lws */

Frame 2047: 66 bytes on wire (528 bits), 66 bytes captured (528 bits) on interface lo, id 1
Ethernet II, Src: 00:00:00_00:00:00 (00:00:00:00:00:00), Dst: 00:00:00_00:00:00 (00:00:00:00:00:00)
Internet Protocol Version 4, Src: 127.0.0.1, Dst: 127.0.0.1
Transmission Control Protocol, Src Port: 53832, Dst Port: 9601, Seq: 1702, Ack: 441891, Len: 0
    Source Port: 53832
    Destination Port: 9601
    [Stream index: 62]
    [Conversation completeness: Complete, WITH_DATA (63)]
    [TCP Segment Len: 0]
    Sequence Number: 1702    (relative sequence number)
    Sequence Number (raw): 4038707193
    [Next Sequence Number: 1703    (relative sequence number)]
    Acknowledgment Number: 441891    (relative ack number)
    Acknowledgment number (raw): 3376300481
    1000 .... = Header Length: 32 bytes (8)
    Flags: 0x011 (FIN, ACK)
        000. .... .... = Reserved: Not set
        ...0 .... .... = Nonce: Not set
        .... 0... .... = Congestion Window Reduced (CWR): Not set
        .... .0.. .... = ECN-Echo: Not set
        .... ..0. .... = Urgent: Not set
        .... ...1 .... = Acknowledgment: Set
        .... .... 0... = Push: Not set
        .... .... .0.. = Reset: Not set
        .... .... ..0. = Syn: Not set
        .... .... ...1 = Fin: Set
        [TCP Flags: ·······A···F]
    Window: 9718
    [Calculated window size: 1243904]
    [Window size scaling factor: 128]
    Checksum: 0xfe28 [unverified]
    [Checksum Status: Unverified]
    Urgent Pointer: 0
    Options: (12 bytes), No-Operation (NOP), No-Operation (NOP), Timestamps
    [Timestamps]



/*Firefox disconnects here at one point and loops below starts */
/* extremely  long loop  */
...
2021-12-20T19:18:15.883221+00:00 d13 api I: ops-h2.c:116 rops_handle_POLLIN_h2: [wsisrv|2|adopted] wsistate 0x20000119, events 5, revents 29, pollout 4
2021-12-20T19:18:15.883402+00:00 d13 api I: ops-h2.c:187 rops_handle_POLLIN_h2: has buffered out
2021-12-20T19:18:15.883608+00:00 d13 api I: ops-h2.c:116 rops_handle_POLLIN_h2: [wsisrv|2|adopted] wsistate 0x20000119, events 5, revents 29, pollout 4
2021-12-20T19:18:15.883752+00:00 d13 api I: ops-h2.c:187 rops_handle_POLLIN_h2: has buffered out
2021-12-20T19:18:15.883937+00:00 d13 api I: ops-h2.c:116 rops_handle_POLLIN_h2: [wsisrv|2|adopted] wsistate 0x20000119, events 5, revents 29, pollout 4
2021-12-20T19:18:15.884110+00:00 d13 api I: ops-h2.c:187 rops_handle_POLLIN_h2: has buffered out
...
/* extremely  long loop */

/* connection finally closes */
2021-12-20T19:18:15.884931+00:00 d13 api I: [wsisrv|2|adopted]: lws_validity_cb: validity too old
2021-12-20T19:18:15.885865+00:00 d13 api I: [wsisrv|2|adopted]: __lws_close_free_wsi: caller: validity timeout
2021-12-20T19:18:15.886296+00:00 d13 api D: [wsisrv|2|adopted]: __lws_close_free_wsi: real just_kill_connection A: (sockfd 11)
2021-12-20T19:18:15.886659+00:00 d13 api I: ops-h2.c:701  [wsisrv|2|adopted], his parent [null wsi]: siblings:
2021-12-20T19:18:15.887028+00:00 d13 api I: ops-h2.c:709 closing [wsisrv|2|adopted]: parent [null wsi]
2021-12-20T19:18:15.887921+00:00 d13 api I: ops-h2.c:713  parent [wsisrv|2|adopted]: closing children: list:
2021-12-20T19:18:15.888859+00:00 d13 api I: [mux|1b|h2_sid65_(wsisrv|2|adopted])]: lws_wsi_mux_close_children:    closing child
2021-12-20T19:18:15.889617+00:00 d13 api I: [mux|1b|h2_sid65_(wsisrv|2|adopted])]: __lws_close_free_wsi: caller: mux child recurse
2021-12-20T19:18:15.891026+00:00 d13 api D: [mux|1b|h2_sid65_(wsisrv|2|adopted])]: lws_http_close_immortal: [wsisrv|2|adopted] (3)
2021-12-20T19:18:15.891756+00:00 d13 api D: [mux|1b|h2_sid65_(wsisrv|2|adopted])]: __lws_close_free_wsi: real just_kill_connection A: (sockfd -1)
2021-12-20T19:18:15.893042+00:00 d13 api D: alloc.c:121 _realloc: size 56: pps
2021-12-20T19:18:15.893685+00:00 d13 api I: http2.c:483 lws_h2_rst_stream: RST_STREAM 0x0, sid 65, REASON 'none'
2021-12-20T19:18:15.894521+00:00 d13 api I: http2.c:145 lws_h2_state: [mux|1b|h2_sid65_(wsisrv|2|adopted])]: state LWS_H2S_OPEN -> LWS_H2S_CLOSED
2021-12-20T19:18:15.894758+00:00 d13 api I: ops-h2.c:701  [mux|1b|h2_sid65_(wsisrv|2|adopted])], his parent [wsisrv|2|adopted]: siblings:
2021-12-20T19:18:15.894966+00:00 d13 api I: [mux|1b|h2_sid65_(wsisrv|2|adopted])]: lws_wsi_mux_dump_children:    \----

```
I wonder if the problem is the credit received here:

2021-12-20T19:13:45.134260+00:00 d13 api I: http2.c:634 lws_h2_tx_cr_get: [wsisrv|2|adopted]: own tx credit 12045338: nwsi credit 12045338

Also not sure why LWS is not able to detect the disconnect sooner (SYN/FIN) without going into the long loop taking significant CPU

**Comment by alexeadem** [comment] 2021-12-21 01:17
Loop I mentioned previously may be related to https://github.com/warmcat/libwebsockets/issues/2360 but it doesn't mention the disconnects in the web browser

**Comment by lws-team** [comment] 2021-12-21 06:09
This is a restriction on using h2, the lws client you have is only using h1 and so has no problem.

With h2, it must announce the size of its DATA frame at the start of the frame, if you give lws_write() 19KB then it uses 19KB for the DATA frame size, since even if it has to send it in pieces, once it starts the frame it's blocked from sending any other frame until it drains the oversize write.  The problem is coming because the h2 endpoints negotiate their max frame size during the SETTINGS phase, the default max DATA is 16KB and that is pretty universally used as the negotiated value because it aligns with the tls max record size of 16KB.  The browsers are seeing you violate the agreed frame size limit with your 19KB and closing the connection because of it.

Atm there's no support for splitting huge writes into multiple 16KB frames in lws_write()... when sending files by lws http, it implements the frame splitting there.  You need to limit what you give lws_write() to 16KB or below to use bulk write with h2.

> 2021-12-20T19:18:15.883402+00:00 d13 api I: ops-h2.c:187 rops_handle_POLLIN_h2: has buffered out

This looks like it is related to deferring the close processing until it has sent everything.  But the connection was already closed by the peer.

**Comment by alexeadem** [comment] 2021-12-22 00:57
Thanks for the info. I did that and it is working. Im fragmenting the frame in a while loop.

But I'm forced to use a 4096 instead of 16k. I think if if I use 16k lws will do partial writes on 16k (< 4096) and add its own  flags:

LWS_WRITE_CONTINUATION | LWS_WRITE_NO_FIN
LWS_WRITE_CONTINUATION
LWS_WRITE_TEXT

which will conflict with my flags. This makes the browser to disconnect too. 

Not sure if this is < 4096 limit is  due to SSL...

The only drawback with my method is that I'm bypassing lws partial writes mechanism and forced to use frame of less than 4096

**Comment by lws-team** [comment] 2021-12-22 03:30
> fragmenting the frame in a while loop.

You should only do one lws_write() per WRITEABLE.  It's the right idea to fragment it but you should do it statefully, send one fragment and if more to send ask for another writeable callback.

> 4096

This is the default info.pt_serv_buf size at context creation time.  It's used to stage framed writes so they can try to go out in one hit.  You can increase it to, eg, 16K to allow sending 16KB - 16 payloads frames.  The 16 accounts for the ws-over-h2 encapsulation framing.

> I think if if I use 16k lws will do partial writes on 16k (< 4096) and add its own flags

No the partial writes operate dumbly, after framing and before write().  So fulfilling them never adds more framing.

**Comment by alexeadem** [comment] 2021-12-24 17:17
I did what you suggested. I wrapped code around to allow a lws_write() per WRITEABLE.
`lws_ring_insert(pss->mi->ring, &amsg, 1) 
`
that allows me to break up the frame to smaller pieces before inserting to the ring buffer. 

I need to control the framing with
`flags = lws_write_ws_flags(LWS_WRITE_TEXT, p == start, p == end);`
for it to work and use a frame below 4096. If a use a value bigger than, my framing is lost as lws will do partial send and it will disconnect the client.

**Comment by lws-team** [comment] 2021-12-24 17:19
You should be able to increase info.pt_serv_buf to send larger things (up to a bit below 16KB).  The lws_protocols struct can also limit how much you can send at once, if pt_serv_buf's not enough check that.

**Comment by alexeadem** [comment] 2021-12-28 07:38
That did it. Thanks so much. Happy holidays.

**Comment by lws-team** [comment] 2021-12-28 07:38
No worries, same to you.

**Closed by lws-team** 2021-12-28 07:38 UTC
