### ISSUE TITLE
Does not support ipv-6?

### ISSUE THREAD

**Issue by wodetian55** [warmcat/libwebsockets#720] opened 2016-12-15 08:30 UTC
Please.
In the ipv6-only environment, libwebsockets does not support other ports? eg, test.test.com:7001.
Because of these problems, I am in Apple's ipv6-only audit, the same reason refused to 3 times.

`
lws_client_connect(_wsContext, "test.test.com", 7001, _SSLConnection,
                                            "", "test.test.com:7001", "test.test.com:7001",
                                             name.c_str(), -1);
`

**Comment by lws-team** [comment] 2016-12-15 08:56
Why don't you try rewrite you question in a way I might care about.

Because listening to people using my software I gave them for free bitching they can't make money from a shitty US Corporation like Apple quick enough and I should do something about it, is not going to get the result you want.

**Comment by lws-team** [comment] 2016-12-15 12:59
Well, I will close this and you can open something more actionable if you can arrive at it.

 - if the problem only exists on your platform, or cannot be reproduced for some other reason, it's your problem to debug it.  I literally don't have your problem, your code, or your platform, or any motivation to care.

 - If you think you understand the problem, try to translate it into something I can look at on Linux + the lws test apps we both have.  Test it to make sure the problem is there, and then let me know how to reproduce it.

 - Even better fix the problem and send me a patch.  I used to get a lot more of that.

**Closed by lws-team** 2016-12-15 12:59 UTC
