### ISSUE TITLE
minimal-http-server-sse-ring U: dropping! and CPU usage goes 100%

### ISSUE THREAD

**Issue by siamect** [warmcat/libwebsockets#2302] opened 2021-05-18 16:09 UTC
Dear Sirs/Madams

Thanks for a fantastic project.
I have installed lws 4.2 from git (1367c11e1ee4) on Ubuntu 20.04.2 LTS

```
mkdir build
cd build
cmake ..
make
sudo make install

```
I run the minimal-http-server-sse-ring 

 ```
cmake . && make
 ./lws-minimal-http-server-sse-ring

```
It works fine in the beginning but when I refresh the web browser the output in the textbox stops and the CPU goes to 100%
Here is the output from the command line:
```
-http-server-sse-ring$ ./lws-minimal-http-server-sse-ring
[2021/05/18 23:01:42:2581] U: LWS minimal http Server-Side Events + ring | visit http://localhost:7681
[2021/05/18 23:01:42:2584] N: LWS: 4.2.99-v4.2.0-30-gecacbfbb, loglevel 1031
[2021/05/18 23:01:42:2584] N: NET CLI SRV H1 H2 WS ConMon IPv6-absent
[2021/05/18 23:01:42:2585] N:  ++ [wsi|0|pipe] (1)
[2021/05/18 23:01:42:2586] N:  ++ [vh|0|netlink] (1)
[2021/05/18 23:01:42:2586] N:  ++ [vh|1|default||7681] (2)
[2021/05/18 23:01:42:2587] N: lws_socket_bind: nowsi: source ads 0.0.0.0
[2021/05/18 23:01:42:2587] N:  ++ [wsi|1|listen|default||7681] (2)
[2021/05/18 23:01:48:3256] N:  ++ [wsisrv|0|adopted] (1)
[2021/05/18 23:01:48:3463] E: lws_mux_mark_immortal: not h2 substream
[2021/05/18 23:02:12:4314] N:  ++ [wsisrv|1|adopted] (2)
[2021/05/18 23:02:12:4793] E: lws_mux_mark_immortal: not h2 substream
[2021/05/18 23:02:13:2156] U: dropping!
[2021/05/18 23:02:13:2157] U: dropping!
[2021/05/18 23:02:13:3743] U: dropping!
[2021/05/18 23:02:13:3745] U: dropping!
[2021/05/18 23:02:13:5331] U: dropping!
[2021/05/18 23:02:13:5332] U: dropping!
[2021/05/18 23:02:13:6918] U: dropping!
[2021/05/18 23:02:13:6919] U: dropping!
[2021/05/18 23:02:13:8505] U: dropping!
[2021/05/18 23:02:13:8506] U: dropping!
[2021/05/18 23:02:14:0092] U: dropping!
[2021/05/18 23:02:14:0093] U: dropping!
[2021/05/18 23:02:14:1680] U: dropping!
[2021/05/18 23:02:14:1681] U: dropping!
[2021/05/18 23:02:14:3267] U: dropping!
[2021/05/18 23:02:14:3268] U: dropping!
```

Any advice how to solve this problem is highly appreciated.

Take care
Thanks in advance
Martin

**Comment by lws-team** [comment] 2021-05-18 20:23
The implementation for the multi-tail ring that is most maintained is the mirror protocol one.

Unfortunately the minimal examples by design have a lot of duplicated code, that makes them easy to consume but extremely difficult to maintain if better ways are found to do what they are demonstrating.

In this case, after being copied into the see example, the mirror protocol grew a helper to reassess what is the worst / oldest tail

https://libwebsockets.org/git/libwebsockets/tree/plugins/protocol_lws_mirror.c#n115

and that is called on client close after removing the closing pss / tail from the client list.  That solves the problem that in the sse example, he doesn't forget the oldest tail of the closed guy and then gets stuck.

If you are interested to cut and paste the mirror example improvements and graft them on to the sse-ring example for your own purposes and send a patch updating it, that would be great.

**Comment by siamect** [comment] 2021-05-19 13:16
So I tried a little but it is definitely well over my level. 
I tried these example because lots has happened to lws since I used it last time which probably was ten years ago...

I suggest that those examples that doesn't work is simply removed or at least flagged with a warning in the readme file. 

This is not the only one with problems.
The minimal-http-server-sse (without the ring) has the same problem. Additionally it doesn't compile with the cmake file that are supplied but you can use the cmake file from the ring and just edit away the ring and it compiles.

Thanks anyway...

**Closed** 2021-05-19 13:25 UTC

**Comment by lws-team** [comment] 2021-05-19 15:50
Bye...
