### ISSUE TITLE
unknown opcode

### ISSUE THREAD

**Issue by jiamuluo** [warmcat/libwebsockets#1553] opened 2019-04-23 14:19 UTC
I send bytes by lws_write,at this moment useing tcpdump to capture net data,i will get many unknown opcode such as 1011 ,0011,0100.i don't known what happened.these unknown opcode will lead to websocket connection close.the mount of send data may be over 50k，Is there a problem?

**Comment by lws-team** [comment] 2019-04-23 14:22
> Is there a problem?

Apparently... but is it my problem?

Who is telling you "unknown opcode", tcpdump?  You should be aware tcpdump cannot always keep up with network traffic, it reports after you close it how many packets it failed to capture.

If that's not the problem, please explain it more clearly and let me know how to reproduce the problem using the examples.

**Comment by jiamuluo** [comment] 2019-04-23 14:25
sorry，i am not familiar with websocket .may i send tcpdump file to your email? thanks

**Comment by lws-team** [comment] 2019-04-23 14:44
I have no idea what you have but

1) tcpdump cannot always catch all packets.  If it misses a packet, it may lose track of the ws frame boundaries

2) you can't tcpdump encrypted wss data and make any sense of it

3) do the minimal examples show the same probelm?

4) What version of lws

5) What is your platform

6) Are we using permessage-deflate extension?

**Comment by jiamuluo** [comment] 2019-04-24 02:40
sorry,it is my fault that give you incomplete message.my ws version is 3.1.0 and plat form is linux4.9 ,ARMv7 Processor .i use libev for ws event.when i want to send data,i will do something like this
`
int write_to_server(int len,void *data)
{
   struct senddata *node = calloc(1,sizeof(strcut senddata ));
  node->data = data;
  node->len = len;
 list_add_tail(node,head);
 lws_callback_on_writable(wsi);
}
`
the data has reserved LWS_SEND_BUFFER_PRE_PADDING;
then i will get callback on websocket_callback
`
swich(reason)
{
   case LWS_CALLBACK_CLIENT_WRITEABLE:
   {
      /*for get node*/
   struct senddata *node;
   unsigned char ucHeadBuf[sizeof(SERVER_HEADER) + LWS_SEND_BUFFER_PRE_PADDING + LWS_SEND_BUFFER_POST_PADDING] = {0}
     list_for_each_entry_safe(node,head)
    {
       bzero(ucHeadBuf,ARRAY_SIZE(ucHeadBuf));
       n = lws_write(wsi,(unsigned char *)&ucHeadBuf[LWS_SEND_BUFFER_PRE_PADDING],sizeof(SERVER_HEADER),LWS_WRITE_BINARY);

      n = lws_write(wsi,node->data + LWS_SEND_BUFFER_PRE_PADDING,node->len - LWS_SEND_BUFFER_PRE_PADDING,LWS_WRITE_BINARY);
    }
   }
  break;
}
`
the roughly processes is like this.i known that call lws_write multiple may lead to block here,but i think i can take in the block result .

**Comment by lws-team** [comment] 2019-04-24 05:44
The first part is OK (although notice for a long while, there is a shorter alias LWS_PRE you can use).  It's worth looking through the minimal examples that try to show the current best way to use individual features in lws.

The second part, it is broken in at least a couple of ways.

You can't sit there dumping as much as you like on a tcp socket in a loop.  tcp doesn't work like that and lws is not designed to do that either.  The network stack is not a magic black hole that eats arbitrary amounts of data and teleports it the other side.  What you can send is determined by the state of the receiver as well as the sender.

tcp network stacks that support POSIX send() are at liberty to refuse all or part of what you are trying to send.  That is not a theoretical constraint if your send() length is above ~1KB.  If that happens, lws conceals it from your code as a convenience... it mallocs up a side buffer for the remaining unsent data, and hides WRITEABLE callbacks to your code until it has been able to use them to send the remaining "partial send" on your behalf.

On v3.1 there's just one of these partial buffers per wsi... that doesn't matter if you follow the rules and send one thing per WRITEABLE, because lws hides WRITEABLE callbacks to your code until the partial buffer is all sent.  But with your looping scheme, it ignores all that and keeps trying to send more, overwriting the pending unsent data and turning everything to crap.

On master, internally because of corner cases with compression, lws introduced a 'buflist' for wsi where they can stack up multiple pending output buffers on the heap if it has to.  But that still makes your code really inefficient even if it worked... it will not block though since in lws all sockets are set nonblocking.

The quick fix is remove the looping and whatever this all-zeros message is trying to do... you have one lws_write() you can do per WRITEABLE.  Add a variable to the pss (doesn't make sense?  Read through the minimal examples...) that holds state for that connection as to what you will send next.  Consume things off the ringbuffer only after you just sent the last piece of it.  If there's more in the ringbuffer, ask at the end for another callback on writable.

Optionally, if the messages may be large compared to the point your network stack may start doing partial sens (for Linux, it's around the mtu size) then use ws fragmentation to only send pieces of a size that will almost definitely be wholly accepted.  There's a helper api that figures of the logic for what type of lws_write() you need

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-write.h#n220-245

this requires more state tracking in your WRITEABLE callback, but it buys you a very low probability lws_write() will have to allocate your remaining partials on the heap itself, improving overall efficiency.

**Closed by lws-team** 2019-04-24 05:44 UTC
