### ISSUE TITLE
Crash on simultaneous disconnection of several clients

### ISSUE THREAD

**Issue by zbroyar** [warmcat/libwebsockets#2114] opened 2020-11-13 14:35 UTC
Hi,

I tested my server (derived from minimal-ws-server-threads-foreign-smp) with 8 libuv loops and ~50 simultaneous connections. All went well until the end of the test when I did basically `killall -9 test-client` just to finish the test.

Server crashed with core. I repeated the scenario several times and found that I can’t crash the server with log level = LLL_INFO | LLL_DEBUG, i.e. when amount of logs is high. Without logs I’ve got two types of backtraces (see below). Second one I was able to got only once.

First:

<img width="1140" alt="1" src="https://user-images.githubusercontent.com/338701/99082217-87648500-25cc-11eb-9cf2-10487f5f6589.png">

Second:

<img width="870" alt="2" src="https://user-images.githubusercontent.com/338701/99082256-9814fb00-25cc-11eb-9712-c4c1906e05b2.png">

**Comment by lws-team** [comment] 2020-11-13 15:40
This is a bit difficult to interpret without knowing what the libuv assert is complaining about exactly.  On current head libuv core.c:930 is

```
 assert(loop->watchers[w->fd] == w);
```

and kqueue.c:148 is

```
assert(w->pevents != 0);
```

Idunno what actually has the problem there.  Whatever it is is might be downstream of other problems, it'd be good if valgrind has traces about it.

**Comment by zbroyar** [comment] 2020-11-13 16:20
I'm sorry for missing that part.

In the first case it's `(loop->watchers[w->fd] == w)`.
In the second - `(w->pevents != 0)`.

I'll try to reproduce the problem on linux machine ASAP and let you know.

**Comment by zbroyar** [comment] 2020-11-13 19:26
The interesting thing is I can't reproduce the crash on linux. The server never crashes if I run it under the valgrind. It crashes on win64 and osx, but not on linux.

On linux it sometimes just hangs.

I test the server with two spam threads and 5 service threads. If I suddenly drop like 100 connections I see the following:

5 threads are hung on lws_mutex_refcount_lock:
```
t2: lws_mutex_refcount_lock (mr=0x5562e477e9b0, reason=0x5562e292ea08 <__func__.33927> "lws_io_cb")
t3: lws_mutex_refcount_lock (mr=0x5562e477e9b0, reason=0x5562e292ea08 <__func__.33927> "lws_io_cb")
t4: lws_mutex_refcount_lock (mr=0x5562e477e9b0, reason=0x5562e292e9f8 <__func__.33917> "lws_uv_idle")
t5: lws_mutex_refcount_lock (mr=0x5562e477e9b0, reason=0x5562e292e9f8 <__func__.33917> "lws_uv_idle")
t8: lws_mutex_refcount_lock (mr=0x5562e477e9b0, reason=0x5562e29266e0 <__func__.31801> "lws_set_timeout")
```

Another two threads are hung on my mutex, locked by t8 and one thread is waiting on pthread_join.

**Comment by lws-team** [comment] 2020-11-13 20:20
Valgrind changes the low level timing and even the underlying memory layout quite a bit, if the problem is coming because of truly simultaneous execution on two separate CPUs, it can be difficult to keep what it needs to make the collision the same.  You can also try it with helgrind option, this makes much less change to the execution speed but it can report a lot of false alarms where we read stuff without locking, because it is sticky and if we just miss it, we will see it next time and clear it only when we handle it.

The first problem about `lws_accept_modulation()` it might be because of assumptions about the vhost listen socket thread domain are broken with SMP.  It's only used for limiting the number of allowed connections, if you don't care about it you can try comment out lws_accept_modulation() guts in pollfd.c and see if it helps, I can take a closer look tomorrow.

> t8: lws_mutex_refcount_lock (mr=0x5562e477e9b0, reason=0x5562e29266e0 <__func__.31801> "lws_set_timeout")

Hm they seem deadlocked... helgrind is very good at following lock ordering and complaining if it sees a different order (which can cause deadlocking).  But it has to do a sort of TOFU scheme to guess the "right" ordering and it's not always right.

It'll help if you can suggest how to reproduce... ab with 100 concurrent should do it?  Or it needs something else?

**Comment by zbroyar** [comment] 2020-11-16 09:41
OK. Here's what I'm going to do:

1. I will add another minimal example of ws client
2. I will try to reproduce the problem on my platforms
3. If successful, I will create a PR with the code and write to this issue the steps to reproduce the proble.

Does this plan sound like a plan? :-)

**Comment by lws-team** [comment] 2020-11-16 09:43
Sure... if I can reproduce it I can debug it... the actual problem should be quite simple since there is no problem with this without SMP.

**Comment by zbroyar** [comment] 2020-11-16 15:25
OK. So here is [PR](https://github.com/warmcat/libwebsockets/pull/2117) with minimal client that establish the given number of connections at start and keep them alive indefinitely.

My test case looks like the following:

1. Start `lws-minimal-ws-server-threads-foreign-smp`. By default it shall create 5 service threads over foreign libuv loops.
2. Start two instances of `lws-minimal-ws-client-spam-tx-rx -n 200`
3. Wait for 1 minute
4. `killall -9 lws-minimal-ws-client-spam-tx-rx`

With this scenario I'm able to reproduce both variants of server crash on linux.

**Comment by lws-team** [comment] 2020-11-16 20:07
`killall` has a really nonobvious quirk, by default it only tries to match the first 15 chars of the process name

```
-e, --exact

    Require an exact match for very long names. If a command name is longer than 15 characters, the full name may be unavailable (i.e. it is swapped out). In this case, killall will kill everything that matches within the first 15 characters. With -e, such entries are skipped. killall prints a message for each skipped entry if -v is specified in addition to -e,
```

https://linux.die.net/man/1/killall

If I follow the reproducer on my laptop, it just kills all three processes, matching on "lws-minimal-ws".

I started looking at it with helgrind, but I can see it has some problems closing SMP libuv loops that I left when I first got it working, it needs a restructuring and cleaning of the destroy stuff into a state machine flow to get rid of those I will have to look at that first.

**Comment by zbroyar** [comment] 2020-11-16 21:09
Yes, you are right about `-e`. But somehow I get a core from a server process every time even without this option:

<img width="1101" alt="Screenshot 2020-11-16 at 23 08 12" src="https://user-images.githubusercontent.com/338701/99308461-a7ac7200-2860-11eb-9275-4e5b6a5d3b63.png">

**Comment by lws-team** [comment] 2020-11-16 21:13
Yes it's the unsolved context destroy stuff... I did note the destroy flow wasn't right for smp libuv when I first did got it working.  There are more dependencies on what can be done when for libuv +smp case than it currently understands, but it's already overdue for a refactor rather than more hacks.

**Comment by lws-team** [comment] 2020-11-20 08:57
There's a big patch on main that refactors the context destroy flow to support libuv smp destroy staging and cleans it up into a state machine.  This solves the problems around libuv smp destroy here.

Notice your example is renamed from "foreign" to "foreign-libuv" since that's all it supports.

**Comment by lws-team** [comment] 2020-11-20 16:29
If still problems, please let me know.

**Closed by lws-team** 2020-11-20 16:29 UTC
