### ISSUE TITLE
How to use lws_cancel_service() with libuv?

### ISSUE THREAD

**Issue by markmaker** [warmcat/libwebsockets#3045] opened 2024-01-08 15:31 UTC
Using libuv `lws_cancel_service()` seems to be stuck in the uv loop instead of ending the `lws_service()` loop. 

I'm following the [minimal-ws-server-echo](https://github.com/warmcat/libwebsockets/tree/main/minimal-examples-lowlevel/ws-server/minimal-ws-server-echo) example, wanting to end the service on certain conditions, just like the example `-o` command-line option. 

The loop looks like this:

https://github.com/warmcat/libwebsockets/blob/43df4901eee0f9cae4718f5ee7cc3fd11c8c3b0e/minimal-examples-lowlevel/ws-server/minimal-ws-server-echo/minimal-ws-server-echo.c#L110-L111

And it cancels here:

https://github.com/warmcat/libwebsockets/blob/43df4901eee0f9cae4718f5ee7cc3fd11c8c3b0e/minimal-examples-lowlevel/ws-server/minimal-ws-server-echo/protocol_lws_minimal_server_echo.c#L207-L216

I was under the impression that lws completely _abstracts_ the event loop of my choice (`LWS_SERVER_OPTION_LIBUV`). Or is this a misunderstanding? Must I explicitly take building blocks of the ["eventlib-foreign" example here](https://github.com/warmcat/libwebsockets/blob/main/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-foreign/README.md)?

And how do I correctly cancel a service and exit the uv loop? Is it really through `lws_context_destroy()` as shown in the signal handler of this example?

https://github.com/warmcat/libwebsockets/blob/43df4901eee0f9cae4718f5ee7cc3fd11c8c3b0e/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c#L62-L76

**Comment by lws-team** [comment] 2024-01-08 15:45
The name 'cancel service' is causing confusion here, although 'cancelling' is the correct name for aborting the wait generally.  This only interrupts a waiting event loop thread, forcing it to wake; it's typically used to get service from other threads synchronized on the lws event loop thread where you can call any lws api.  It doesn't exit the loop.

Just follow the foreign event loop example, if you only want libuv you can simplify it a lot by throwing out the code in the example related to other loop types.. the example supports choosing any supported event loop at runtime.  It shows how to exit the loop too.

**Comment by markmaker** [comment] 2024-01-08 17:39
Thanks, I think I got it. :smile: 

Just to be sure I understood correctly:

Stopping the service is done by simply calling `uv_stop()`, right? This will call the proper cleanup code in lsw as well (it seems that way from logs).

I deviated from the example, also calling `uv_stop()` rather than `lws_context_destroy()` in the `SIGINT` signal handler. 

Am I right to assume that this is a bug in the [example](https://github.com/warmcat/libwebsockets/blob/43df4901eee0f9cae4718f5ee7cc3fd11c8c3b0e/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c#L62-L76)?

IMHO it doesn't make sense, logically and at least my tests show it doesn't work.

**Comment by markmaker** [comment] 2024-01-08 17:44
Btw. is there a way to get the loop from the context? 

I'm not using static variables (ever) to keep it multi-instance capable, so I had to use user data, but I guess the loop is stored somewhere in lws? API search was fruitless so far :eyes:

**Comment by lws-team** [comment] 2024-01-08 17:45
No the example is how it should be.  The order your suggesting would leak.  Try the example unchanged first.

You create your loop.  You can set it running.

You create an lws_context and bind it to your loop.

Eventually you destroy the lws_context.  Everything it has on the loop is cleanly closed / removed and destroyed.

Your loop can continue doing other things.

Eventually you stop and dedtroy your loop.

Nothing leaks.

**Comment by lws-team** [comment] 2024-01-08 17:49
You can use the context's opaque_user_pointer at creation time to bind whatever additional malloc'd object containing whatever you want to it.

**Comment by markmaker** [comment] 2024-01-08 19:02
> No the example is how it should be. The order your suggesting would leak.

> Eventually you stop and destroy your loop.
> Nothing leaks.

Okay, I guess I misunderstood the design intention. But there _are_ bugs. :grin: 

I noted  that there is a second `lws_context_destroy()` in `main()` here:

https://github.com/warmcat/libwebsockets/blob/43df4901eee0f9cae4718f5ee7cc3fd11c8c3b0e/minimal-examples-lowlevel/http-server/minimal-http-server-eventlib-foreign/minimal-http-server-eventlib-foreign.c#L331-L333

Using `uv_stop()` happens to do right thing: temporarily breaks the `uv_run()` loop and returns to `main()`, _then_ the example calls `lws_context_destroy()` and also closes its own uv signal handler and timer making sure it doesn't proceed. Then a second `uv_run()` inside `ops->cleanup();` will do the async cleanup until no active handles are left and it returns again and also cleans up the loop itself.

Conversely, the current example will hang after the `SIGINT`, because the loop never returns to `main()`, as the signal and timer uv handles are still open and active. The example will eventually stop the loop when the timer goes to the `TEST_STATE_EXIT` and calls `uv_stop()`. It will then return to `main()` and call `lws_context_destroy()` again. 

In fact `lws_context_destroy()`is called a _third_ time after it was called both by `SIGINT` and `TEST_STATE_DESTROY_LWS_CONTEXT` (or the other way around). It doesn't seem that `lws_context_destroy()` is protected against being called multiple times. 

If I understand your design intention correctly, one would probably need reference counting on the context, so `lws_context_destroy()` is never called twice, in all cases: no `SIGINT`, `SIGINT` before `TEST_STATE_DESTROY_LWS_CONTEXT`, and `SIGINT` after `TEST_STATE_DESTROY_LWS_CONTEXT`.

**Comment by markmaker** [comment] 2024-01-08 19:07
> You can use the context's opaque_user_pointer at creation time to bind whatever additional malloc'd object containing whatever you want to it.

I've used `lws_protocol_vhost_options`, as in the abovementioned echo example.

**Comment by lws-team** [comment] 2024-01-08 19:08
lws_context_destroy is stateful - it has to be for libuv at least since with libuv closing a handle does not complete until some more ties around the loop.  And yes, there is reference counting to determine when all the handles are closed.

It's possible something in the example is wrong, but if so, just let me know how to reproduce it on the unchanged example, that's why the examples are there.

**Comment by markmaker** [comment] 2024-01-08 19:18
Ah okay, then I have even more misunderstood the design intentions, including of `lws_context_destroy()`. 

Maybe because of the API description:

> This function closes any active connections and then frees the  context.  After calling this, any further use of the context is undefined.

https://libwebsockets.org/lws-api-doc-main/html/group__context-and-vhost.html#ga8ee0314028755f1ddfa9428e09b4fddb.

**Comment by lws-team** [comment] 2024-01-08 19:27
That is still correct for default platform loop since there's no event lib to bring its own additional constraints that force multistage context destruction still using the event loop.

For the event lib, if you just confirm the provided example works, then base your code off it, you can avoid all these speculative alternate universe misunderstandings because it started off working with the recommended best design and never stopped working while you adapted it to do whatever your code needs to do.

**Comment by markmaker** [comment] 2024-01-08 20:45
My design goal is different, which probably also contributed to the misunderstanding. Upon `SIGINT` or other stop conditions I _want_ to close the whole service, the loop must immediately return. If I understand the example right, it too uses `uv_stop()` for that in the `TEST_STATE_EXIT`. So I'll just do both `lws_context_destroy()` and `uv_stop()` in the signal handler.

It seems to work.

**Comment by lws-team** [comment] 2024-01-08 20:50
Well, I think I had this code wrongly explained to me enough different ways in this issue... never mind I wrote it.  I think we should just agree you can do what you like with it if you aren't going to need my help.

**Closed by lws-team** 2024-01-08 20:50 UTC

**Comment by markmaker** [comment] 2024-01-08 21:24
Well, I apologize for having misunderstood the example, and then jumped to false conclusions. 

Your actual help was in [clarifying](https://github.com/warmcat/libwebsockets/issues/3045#issuecomment-1881287498) the meaning of `lws_cancel_service()`, and that adaptation to libuv is not done by simply setting `LWS_SERVER_OPTION_LIBUV`. 

So thank you.
