### ISSUE TITLE
Sending a large buffer with lws_write takes 63 seconds in some cases

### ISSUE THREAD

**Issue by alexhultman** [warmcat/libwebsockets#464] opened 2016-03-18 01:26 UTC
I think this needs investigation. Like I mentioned, both the ev and uv backends behave identical in this regard and that is when sending a 100mb buffer with lws_write, it can take less than a second in the case of rx_buffer_size being large enough (larger than or equal to 33 kb in my specific case). In cases where rx_buffer_size is smaller, or unset (4kb) it takes 63 seconds to complete.

**Comment by alexhultman** [comment] 2016-03-18 01:46
The fact that lws_write now makes internal buffering instead of refusing to write more than what the kernel allows makes it hard to solve by using fragmented sends. When I pass 100 mb to lws_write it returns that it did accept all bytes:

lws_write accepted: 104857600

Still, it doesn't actually manage to send these bytes in a reasonable time.

**Comment by alexhultman** [comment] 2016-03-18 02:09
When it fails, I get bursts of lws_service_fd_tsi calls, then a long wait, then a new burst, etc. lws_service_fd_tsi is not being called as often as it should have.

**Comment by lws-team** [comment] 2016-03-18 02:29
I don't really understand why the rx buffer size is involved.  However as I wrote in #463 lws_write() is a wrapper around send().  You cannot call send() with a 100MB buffer one time either and expect it to get anywhere.

The malloc() thing is a safety-net for the case that sometimes the kernel won't accept all of a reasonable buffer size like 4KB, it's not intended to enable this 100MB usage thing.

It'd help me a lot if you can hack the test case on the normal test server so I can hopefully see what you're seeing.

**Comment by alexhultman** [comment] 2016-03-18 02:33
Do you have any plans on adding a flag to lws_write so that one can explicitly say "no, do not buffer things up if you couldn't fit in the kernel buffer". Because currently I have no way of knowing how much I can send without triggering the built-in buffering. I want to explicitly disable it so that I can be sure my fragments are directly sent to the kernel, and I do not want to guess.

**Comment by alexhultman** [comment] 2016-03-18 02:39
If you look at the old documentation: https://libwebsockets.org/libwebsockets-api-doc.html

lws_write is said to return the number of bytes *actually* sent. Now, since the internal buffering change (which I personally cannot get to work reliably) there is no way of knowing how many bytes were written, since it now accepts all bytes and does the internal buffering.

I want to disable the internal buffering so that I can get the old behavior where you manually have to do the fragmented send.

**Comment by alexhultman** [comment] 2016-03-18 02:44
The rx_buffer_size is just a way for me to trigger the bug. I don't know why. Some people cannot reproduce the bug (you involved), but for me the rx_buffer_size is how I reproduce it.

**Comment by alexhultman** [comment] 2016-03-18 03:21
I'm looking at the code and it actually seems to work for me, even if it is very very slow. Is is actually sending small fragments all the time.

So if we move this issue to focus on getting a better lws_write interface. It should be simple to add a check in output.c to skip the buffering in lws_issue_raw:

```c++
	if ((unsigned int)n == real_len) // skip this check if we do not want to use the built-in buffering
		/* what we just sent went out cleanly */
		return n;
```

**Comment by alexhultman** [comment] 2016-03-18 03:34
I fixed it :)

If I do this:

```c++
	if (len > 4096)
		len = 4096;

	n = lws_ssl_capable_write(wsi, buf, len);
	lws_latency(context, wsi, "send lws_issue_raw", n,
		    (unsigned int)n == len);
```

Where 4096 is the rx_buffer_size, it massively speeds up.

**Comment by alexhultman** [comment] 2016-03-18 03:43
Okay the "bug" seems to be that if we send (unix socket send) more than rx_buffer_size then the sending becomes *ultra* slow. I do not know why but I know that if I limit the length passed to send (unix send) it dramatically speeds up on my system.

**Comment by alexhultman** [comment] 2016-03-18 03:53
It is strange that this happens because you seem to already limit the sending to rx_buffer_size:

```
		n = wsi->protocol->rx_buffer_size;
		if (!n)
			n = LWS_MAX_SOCKET_IO_BUF;
		n += LWS_PRE;
		wsi->u.ws.rx_ubuf = lws_malloc(n + 4 /* 0x0000ffff zlib */);
		if (!wsi->u.ws.rx_ubuf) {
			lwsl_err("Out of Mem allocating rx buffer %d\n", n);
			return 1;
		}
		wsi->u.ws.rx_ubuf_alloc = n;
		lwsl_info("Allocating RX buffer %d\n", n);
#if LWS_POSIX
		if (setsockopt(wsi->sock, SOL_SOCKET, SO_SNDBUF,
			       (const char *)&n, sizeof n)) {
			lwsl_warn("Failed to set SNDBUF to %d", n);
			return 1;
		}
#endif
```

setsockopt should make the send function not accept more than this, right? That seems to fail in this case.

**Comment by alexhultman** [comment] 2016-03-18 04:00
http://stackoverflow.com/questions/8114280/effect-of-so-sndbuf

Okay the kernel is allowed to allocate a larger buffer than what is set in setsockopt. So we need to make sure we never send more than what we set in setsockopt (or find the reason why things become ultra slow when sending longer fragments than rx_buffer_size).

**Comment by lws-team** [comment] 2016-03-18 04:07
I can't see the context of the code you pasted, but didn't the 'fix' just chop off and throw away 99.996MB of your 100MB?

It's slow otherwise because it malloc's a buffer for the 99.996MB and sends a lump more each time the socket becomes writeable, ie, actually does the send.  Apologies if I missed the point.

The socket option thing is trying to reserve at least the rx buffer size for the connection kernelside.  That's not guaranteed to succeed, but normally, on Linux, it should let us send() that amount of data cleanly if the connection is writeable.

I'm not sure I got your meaning correctly but it seems the solution is send <= rxbuffer sized fragments (allowing for ws header) and everything happy.

**Comment by alexhultman** [comment] 2016-03-18 04:09
Hehehe, yes I wrote a typo there. I meant something like this:

int limitedLen = len;
if (limitedLen > "rx_buffer_size")
  limitedLen = "rx_buffer_size"

The client gets all bytes.

**Comment by alexhultman** [comment] 2016-03-18 04:11
Yep the fix is to (unix) send less than or up to rx_buffer_size.

**Comment by alexhultman** [comment] 2016-03-18 04:13
So I am in output.c, `int lws_issue_raw(struct lws *wsi, unsigned char *buf, size_t len)` and I need to get the rx_buffer_size, is that possible?

**Comment by alexhultman** [comment] 2016-03-18 04:15
This seems to work:

```c++
	/* make sure not to send more than wsi->u.ws.rx_ubuf_alloc */
	int passedLen = len;
	if (passedLen > wsi->u.ws.rx_ubuf_alloc)
		passedLen = wsi->u.ws.rx_ubuf_alloc;

	n = lws_ssl_capable_write(wsi, buf, passedLen);
```

**Comment by alexhultman** [comment] 2016-03-18 04:17
No that assumes the socket is ws right? It will break on HTTP sends right?

**Comment by lws-team** [comment] 2016-03-18 04:18
Eh no that's the size of user_space associated with the protocol.

You want what you pasted before

```
n = wsi->protocol->rx_buffer_size;
if (!n) n = LWS_MAX_SOCKET_IO_BUF;
```

**Comment by lws-team** [comment] 2016-03-18 04:19
protocols[0] (http[s]) can also set his rx_buffer_size.

**Comment by alexhultman** [comment] 2016-03-18 04:22
```
diff --git a/lib/output.c b/lib/output.c
index 0d850eb..f598ab8 100644
--- a/lib/output.c
+++ b/lib/output.c
@@ -123,9 +123,14 @@ int lws_issue_raw(struct lws *wsi, unsigned char *buf, size_t len)
        if (!lws_socket_is_valid(wsi->sock))
                lwsl_warn("** error invalid sock but expected to send\n");
 
+       /* limit sending */
+       n = wsi->protocol->rx_buffer_size;
+       if (!n) n = LWS_MAX_SOCKET_IO_BUF;
+       if (n > len) n = len;
+
        /* nope, send it on the socket directly */
        lws_latency_pre(context, wsi);
-       n = lws_ssl_capable_write(wsi, buf, len);
+       n = lws_ssl_capable_write(wsi, buf, n);
        lws_latency(context, wsi, "send lws_issue_raw", n,
                    (unsigned int)n == len);
```

**Comment by alexhultman** [comment] 2016-03-18 04:23
Would that be correct? It makes my 60 second send into a 0.5 second send.

**Comment by lws-team** [comment] 2016-03-18 04:29
I don't understand why it gets into this 60s thing,  Once there's a malloc buffer they can't nest and ought to be cheap to drain.

This is forcing it to use the malloc'd buffer each time it was given > rx buffer size, it seems trying to do the big send() is the super expensive thing on your system, not the malloc'd buffer.

I don't think it should break anyone's code, although if they were on 127.0.0.1 and didn't have this problem, they might complain it's slower.  I'll try the patch later and see what happens.

**Comment by alexhultman** [comment] 2016-03-18 04:29
The message being sent is verbatim received at the client, if I tamper with one byte it reports a corruption.

**Comment by lws-team** [comment] 2016-03-18 04:30
Yes the patch seems sane like that.  I don't understand why it buys you 59s tho.

**Comment by alexhultman** [comment] 2016-03-18 04:30
I don't know why it becomes slow but from my basic debugging I found it was sending about 65k while the rx_buffer_size was 4k. More than that I do not currently know.

**Comment by alexhultman** [comment] 2016-03-18 04:33
Okay so this would be problem number 1: getting the lws_write internal buffering to work for me. Problem number two would be, I would want to control the buffering by passing a boolean to lws_write to allow or disallow the internal buffering. That way I can do more efficient fragmentation like I wrote about earlier.

**Comment by alexhultman** [comment] 2016-03-18 04:36
Ah, in C you cannot have default arguments like in C++ right? So you probably want to let me set a flag or something so I do not break the API. lws_set_write_buffering(boolean) or something.

**Comment by lws-team** [comment] 2016-03-18 04:43
No there is already a flags arg on lws_write() you can add a flag.

But I don't feel I understand the situation or why the patch seems to do something for you.  Depending on the root cause the patch or formalizing a flag might not be a good idea.  So we / I should understand the diagnosis before dispensing medicine.

**Comment by alexhultman** [comment] 2016-03-18 04:53
If I have a buffer, say 500 GB large. I then want to send this over WebSocket (insane, but still plausible).

I do not know beforehand how many bytes the kernel can take.

If I pass it to lws_write, it will gladly accept the buffer, allocate a new one, copy the contents and mark the socket as buffered. Then it will do the sending for me. This will consume at least 2 * 500 GB ram (my original buffer, the internal buffer).

This is not what I want, I want to disable buffering so that lws_write returns the actual bytes sent so that I can keep my buffer and only pass fragments to lws_write.

One solution would be to pass *guesses* to lws_write, say 4k segments. But there is no way to know if lws_write actually can handle 4k so it might do the buffering. I want to pass LWS_NO_BUFFERING as write flag and get a guarantee that there will be no buffering done internally.

**Comment by lws-team** [comment] 2016-03-18 04:57
This becomes problematic if you consider an extension between your source data and what's actually sent.  There is no way to express the (eg, compressed) remainder in units of the input buffer.

**Comment by alexhultman** [comment] 2016-03-18 04:58
Touché. So the correct solution would be to guess, based on the rx_buffer_size?

**Comment by lws-team** [comment] 2016-03-18 05:04
I tried a few ways and the only solution that stopped my ml filling up with complaints was just take responsibility for whatever they gave, without asking them to do or understand anything more.

I think that's still the right approach that covers all the baees, at least unless the whole thing was rewritten with input buffer destroy callbacks to let lws control buffer lifetime and eliminate the memcpy.  But that's encouraging nonfragmented send that's just bad.  So until this 60s thing it's fine as it was afaik.

If I can reproduce the 60s later, your patch seems a sane way.  But the 60s doesn't itself seem sane.  So I worry we miss the real point.

**Comment by lws-team** [comment] 2016-03-18 05:06
Maybe send() does work on the full requested buffer first (mapping it or somesuch) each time before deciding it only will use a little bit of it.  That'd explain the observation and why the patch helps.

**Comment by alexhultman** [comment] 2016-03-18 05:22
I kind of get the same requests. People want to just throw "a buffer" at you and then forget about it. Fragments are of course the best way to go but people just won't use them.

I didn't understand what you meant about the patch? I will use it in my next release so we should find out if it decreases the performance or not.

**Comment by alexhultman** [comment] 2016-03-18 05:27
How do you handle permessage deflate on a buffered message? Because if you cannot know the uncompressed length from the compressed length you should have the same problem as I would get if using the LWS_NO_BUFFERING?

**Comment by lws-team** [comment] 2016-03-18 05:36
There's nothing objectionable about the patch.  But I need to understand why it does something.  My best guess is it's very expensive just to call send with a big length, if so, the patch is probably needed.

It took a lot of time to get the compression extension right for that.  zlib operates in stream mode but there are quirks.  The extension fills a fixed-size buffer at a time and passes that up only.  Incoming buffers and outgoing buffers are wound through the event loop so the whole thing is nonblocking.  A similar buffering system operates on extension-processed data as needed.

**Comment by alexhultman** [comment] 2016-03-18 05:57
From my testing I can only get better performance with this patch. And increasing the size of the rx_buffer_size is only making it faster (a lot faster). So send with a large buffer is nothing bad in my testing.

**Comment by lws-team** [comment] 2016-03-18 06:23
Yes.  But 127.0.0.1 (lo network interface) is a special case, he will accept large packets easily.  The test will act completely differently in terms of what send() likes to do on a real network interface and / or when the kernel feels under memory pressure.

It's not a ding on your patch just you are getting the wrong idea about what's possible packet size-wise from using lo.

**Comment by alexhultman** [comment] 2016-03-18 06:34
Short term I can solve this in node-lws by chopping the passed message up into pieces of rx_buffer_size length and send them as fragments (this essenially enforces a limit on each send the same way the patch does).

Long term we can test this patch and evaluate it.

**Comment by lws-team** [comment] 2016-03-18 06:57
Yeah I'll put it in master for now and see what happens

**Comment by alexhultman** [comment] 2016-03-18 07:12
Yep we can revert it later if it completely blows up :)

**Comment by lws-team** [comment] 2016-03-18 17:13
It's pushed, I close this for now and the pr.

**Closed by lws-team** 2016-03-18 17:13 UTC
