### ISSUE TITLE
Parsing of escaped URL does not work as expected (take 2)

### ISSUE THREAD

**Issue by emptyVoid** [warmcat/libwebsockets#371] opened 2015-12-15 04:17 UTC
Whereas 38f3225b223aeeca515f9022883c9b7560a8a6e1 fixed an issue with the internal parsing of URL components, it does not solve the major problem: libwebsockets user receives a modified query string, that in some scenarios could be unusable or even harmful (or am I missing something and API provides the means to retrieve raw (escaped) query string or parsed key-value pairs?)

Here's another example:
```
/cgi-bin/settings.js?UPDATE_SETTINGS=1&Root_Channels_1_Channel_name_http_post=dummy%26hack%3D1&Root_Channels_1_Channel_location_http_post=dummy
```

got parsed to:
```
UPDATE_SETTINGS=1&Root_Channels_1_Channel_name_http_post=dummy&hack=1&Root_Channels_1_Channel_location_http_post=dummy
```

again as reported by ```lws_hdr_copy( wsi, ..., ..., WSI_TOKEN_HTTP_URI_ARGS )```.

As you can see the value of ```Root_Channels_1_Channel_name_http_post``` got split and one of its parts is indistinguishable from a normal key-value pair.

libwebsockets shouldn't decode/unescape  the query string, maybe?

**Comment by lws-team** [comment] 2015-12-15 05:24
No atm he doesn't provide access to the parsed pairs.

The reason he does it at all is since lws must deal with http, it's better that things we can expect to be commonly related to that are in the library, rather than repeated in user implemenations of varying completeness and quality.

I think the solution for this is to provide the pair metadata somehow... %26 should become & the problem is it's overloaded as the separator the user code must re-parse...

**Comment by lws-team** [comment] 2015-12-15 15:46
Please take a look at current HEAD.... basically he does the same thing, but re-uses the fragment support to logically cut each x=y parameter into individual fragments.

An api is added to allow access generally to individual header fragments.

If you look at the end of this how test-server is adapted to dump the individual parameters, it explains how to use it clearly -->

https://github.com/warmcat/libwebsockets/commit/4eb36373d70b3fda099d1896733c6ddd3046bdf1

**Comment by lws-team** [comment] 2015-12-16 10:01
This seems to me to be solved, so I will close it.  If more problems are coming with it, please reopen.

**Closed by lws-team** 2015-12-16 10:01 UTC
