### ISSUE TITLE
destroy vhost, stop listening

### ISSUE THREAD

**Issue by sejvlond** [warmcat/libwebsockets#963] opened 2017-07-14 12:23 UTC
Hi,

is it possible to stop the listening socket? I have multiple vhosts and I want to stop/close/destroy one of them. And after some time to create it again. Lws is serving. I know that I can return non zero from callback to close the current connection, but how about to close the listening one?

Thank you

**Comment by lws-team** [comment] 2017-07-14 12:37
There's no way to do it directly as it stands.

Why do you need to destroy the vhost?

**Comment by sejvlond** [comment] 2017-07-14 12:46
I have an application which opens 2 different ports. One is for commands, second is opened only sometimes for some data stream. Let's assume this situation:

App opens port 1111 for commands and waits for client. When client connects and sends some specific command (eg. "START SINGING xyz") the app opens new port 2222, waits until client connects and starts sending some data (lets say text of song xyz). When some other command ("STOP") arrives, the app closes the 2222 port.
This situation may repeat in time, but with different xyz song and based on this a different object in c++ is created with different callback function.

I would say, why not to allow to remove registered vhost and to stop listening without destroying the whole context with all vhosts...? Is there a reason?

**Comment by lws-team** [comment] 2017-07-14 12:55
Yeah the reason is I never needed this capability.

I read your description a couple of times.... is there a reason you make it reconnect to some ephemeral listening port as in your description?

It he is already connected on port 1111, why can't you do your business on that existing connection?

**Comment by sejvlond** [comment] 2017-07-14 12:57
a lot of legacy code ... ? :)

**Comment by lws-team** [comment] 2017-07-14 12:59
Hmmm do these legacy client "know" it's port "2222" (number changed to protect the guilty) or they get told the port by the connection on "1111"?

**Comment by sejvlond** [comment] 2017-07-15 07:38
Clients are told the port, but only once at the beginning, then they use it for ever. Port number was changed, because 1) I don't really remember it, and 2) it can be even random :)

I know we are misusing the lws quite badly, we would have one listening port and use only different protocols with callbacks or use vhosts etc. The problem is, there is a lot of code already written, the code was originally using 2 different lws contexts, which was failing sometimes (destroying the lws context clears openssl and so on) so, I am trying to refactor it. Using vhosts looks like a good way, the only problem is, I would need to dynamically create/destroy the vhosts.

There is (I think I saw it somewhere) a possibility to reload lws context with new vhosts' configuration, isn't it?

**Comment by lws-team** [comment] 2017-07-15 07:45
Yeah there is a way to leave all alive connections up but strip the listen sockets from the vhost.  At the same time, a new process is started using the new config.

New connections find whatever new listen sockets are around and use them.  Old connections exist until their number reaches zero, when the original process exits.

lwsws implements it by having a dumb, no-network root process stay alive and spawn the actual lwsws process (which runs under reduced credentials).  When the parent process gets a signal it does the reload action.

However you're not the only person asking for dynamic vhost destruction in the last days... the other guy on the mailing list has some nice reasons like network interfaces change state / IP and he wants to make lws adaptively follow with the related vhost.  For routers or whatever, that's actually pretty much needed.

So I have implemented it thisafternoon, I need to think up a way to test it and make sure valgrind is happy (not trivial when libuv is involved).

**Comment by sejvlond** [comment] 2017-07-15 08:36
Awesome, it would be great.

You're planning the functionality same as vhost_create, right? If I destroy a vhost, and it is the last vhost on the port, the listening port will be closed, otherwise only vhost is removed.

**Comment by lws-team** [comment] 2017-07-15 11:29
Yeah it intends to handle everything including shared listen sockets.

I pushed what I have on master, which is tested for doing its bit for context destruction but not anything else yet.

**Comment by lws-team** [comment] 2017-07-16 01:35
I added testing in libwebsockets-test-server and ...v2.0.

Firing a SIGUSR1 at the test server makes it toggle between creating and destroying an identical vhost on port + 1.  That works both with and without libuv.

**Comment by lws-team** [comment] 2017-07-18 08:25
The other guy confirmed it worked for him, following the scheme of doing the destroy outside of service that is done in test-server.  So closing this unless there is some problem.

**Closed by lws-team** 2017-07-18 08:25 UTC

**Comment by sejvlond** [comment] 2017-07-20 12:24
I can confirm that lws_vhost_destroy is working for me as well, great job, thank you for it!

Will you increase version and create "official" release?

**Comment by lws-team** [comment] 2017-07-20 12:32
Yes we are heading for a v2.3 release soon.  I want to wait a little bit more to see if any problems with lws-meta, it's only really stable a few days ago.  The test servers + libwebsockets.org switched over to it but not ESP32 yet, where it will be really beneficial.

**Comment by sejvlond** [comment] 2017-07-20 12:34
ok, no need to hurry, thank you
