### ISSUE TITLE
Example CGI not working.

### ISSUE THREAD

**Issue by lailton-dev** [warmcat/libwebsockets#1971] opened 2020-07-10 20:29 UTC
Hello @lws-team 

I am trying to use the libwebsockets with CGI but after enable it all my tests was without success.
Then I was testing it using the minimal example provided and also doesnot works.

The original .sh on Mac OS dont exist. "/proc/meminfo", so I did test with the original sh and with the modified.

### 1-Don't works.

<img width="1680" alt="Screen Shot 2020-07-10 at 17 16 48" src="https://user-images.githubusercontent.com/58268709/87200028-19344c80-c2d2-11ea-89a4-d58b85fe679d.png">

### 2-It works with minimal HTML but after 6~10 REFRESH the page it give me a error segment fault.

<img width="1680" alt="Screen Shot 2020-07-10 at 17 18 54" src="https://user-images.githubusercontent.com/58268709/87200036-1df90080-c2d2-11ea-9952-37ad62fb8abe.png">

### 3-Using the minimal example I can not READ also the info like REQUEST METHOD and all the others.
<img width="1680" alt="Screen Shot 2020-07-10 at 17 20 05" src="https://user-images.githubusercontent.com/58268709/87200046-20f3f100-c2d2-11ea-86bc-0a513a67fd2c.png">

### NOTE:
**If you send a POST to the minimal example ( number 2 here on the list ) it close and give an segment fault also.**

My computer info:
MacOSX - Catalina 10.15.5
LibWebsockets last version from GITHUB

Thanks.

**Comment by lws-team** [comment] 2020-07-10 20:36
> close and give an segment fault also.

There is no point telling me that unless you're giving me a backtrace.

It looks like it's racing reading the stdout vs the close... what happens if you put something like `sleep 0.5s` before your script exits?

**Comment by lailton-dev** [comment] 2020-07-10 20:48
@lws-team Thanks for reply.
I will try to give you all informations need to check what is happening.

After I have added the sleep 0.5s to the .sh it have stoped to give me the segmentation fault when I refresh the page.
But I still not receiving the information about REQUEST_METHOD etc.
Another important info is when I try to call it using the POSTMAN APP using the METHOD POST it give me error.

Here you have the screenshot:

<img width="1680" alt="Screen Shot 2020-07-10 at 17 42 43" src="https://user-images.githubusercontent.com/58268709/87201687-78479080-c2d5-11ea-8a95-7f92e5143225.png">
<img width="1680" alt="Screen Shot 2020-07-10 at 17 43 06" src="https://user-images.githubusercontent.com/58268709/87201694-7d0c4480-c2d5-11ea-906b-08404a0652d9.png">

Thanks

**Comment by lws-team** [comment] 2020-07-10 20:50
So this CGI is served OK using the same code.

https://libwebsockets.org/mailman/listinfo

You're using master lws or something else?

**Comment by lws-team** [comment] 2020-07-10 20:52
... also on mac, I use the underlying spawn APIs a lot for Sai, it spawns the build processes using this.  So it should be OK on OSX.

You should run it under lldb and get a backtrace (bt) where the problem is coming.  Valgrind is also good but broken on OSX.

**Comment by lailton-dev** [comment] 2020-07-10 20:56
I am using the master.
<img width="547" alt="Screen Shot 2020-07-10 at 17 54 37" src="https://user-images.githubusercontent.com/58268709/87202233-7c27e280-c2d6-11ea-8d53-3528995cfbec.png">

Do you have MacOSX on your side to test the example?
I dont have experience with lldb, I will check what I can see.

**Comment by lws-team** [comment] 2020-07-10 20:58
I do but I am busy with other things.

Just run it `lldb theapp` if you normally run it `theapp`

Then `r` for run and when it crashes, `bt` for the backtrace.

Make sure you build lws with -DCMAKE_BUILD_TYPE=DEBUG and also if you build the test app separately, use the same flag to build that in debug mode so it will tell the source lines.

**Comment by lailton-dev** [comment] 2020-07-10 21:01
Sure,
I will try it.
Thanks

**Comment by lailton-dev** [comment] 2020-07-10 21:29
@lws-team 

<img width="1357" alt="Screen Shot 2020-07-10 at 18 29 07" src="https://user-images.githubusercontent.com/58268709/87204464-40dbe280-c2db-11ea-83f3-708de3d0bc2a.png">

**Comment by lws-team** [comment] 2020-07-12 19:27
I modified the test script to not look at /proc/meminfo, run it and click like crazy on safai reload button, I just get the expected message in the browser and no crash... this is on a mac mini.

**Comment by lailton-dev** [comment] 2020-07-13 14:21
Hi @lws-team,
What is version your MacOS? which branch are you using?
Did you have recompiled your example using the last version?
I am going to install a different OS to test the same example, anyway for me the example
is not working on MacOSX Catalina.
Are you able to read the POST data? can you install the POSTMAN app on your Mac Mini and try submit a POST
and put here a screenshot?
Thanks

**Comment by lws-team** [comment] 2020-07-13 14:25
It's lws master on Catalina.

I built the example, and edited the test script to just print static text and not look for /proc/meminfo.

And I GET it, not POST on it.  I works if you GET it?  Because I just tried GET.

I don't care enough about this to figure out how to install POSTMAN.  As I say this same stuff works fine on Linux at the URL I gave with mailman, for POST and GET and that's running very close to master lws.  And I use lws_spawn all the time on the mac mini for CI.

**Comment by lailton-dev** [comment] 2020-07-13 14:28
No, I can not READ the REQUEST_METHOD or CONTENT_LENGTH with both.
and using the method POST is how reproduce the error above

Anyway, I am going to do more tests to point you to the correct point where it is not working

Thanks

**Comment by lailton-dev** [comment] 2020-07-13 15:51
Linux Ubuntu ( last version )

<img width="1680" alt="Screen Shot 2020-07-13 at 12 44 56" src="https://user-images.githubusercontent.com/58268709/87324887-1e2e1180-c507-11ea-8f03-cf6623644dc7.png">

The script is called but the page is not loaded.
I will try to night to test also on Windows, but for sure there is something that is not working as expected.
I will try later also to test OLD versions LWS maybe something was changed and is causing the issues.

Thanks anyway.

**Comment by lws-team** [comment] 2020-07-13 16:54
I tried the cgi example as it is on Fedora 32 / current Firefox and he works fine.  I hold down Ctrl-R so he's spamming away and he's fine.

I noticed in the background your terminal says "CGI hdrs > buf size".... this comes from here

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/cgi/cgi-server.c#n632-637

That's selected here

https://libwebsockets.org/git/libwebsockets/tree/lib/roles/cgi/cgi-server.c#n594-598

For sure as the example is provided, it does not cause that problem.... but you're not mentioning anything about changing that here...  If you mail cgi creates huge headers, for example, huge cookies, you can try adjusting the value in the last link so it can allocate for them.

**Comment by lailton-dev** [comment] 2020-07-13 17:00
I am not doing any change, I am running the examples how it is.

I am compiling the LWS using this command:
mkdir build
cmake .. -DLWS_ROLE_H1=1 -DLWS_WITH_CGI=1 -DLWS_WITHOUT_SERVER=0 -DBUILD_SHARED_LIBS=1 -DLWS_WITH_MINIMAL_EXAMPLES=1
make 

after that, I am going to the folder bin
copy from the examples taht my-script.sh .
chmod +x my-script.sh

then run:
./lws-minimal-http-server-cgi

Then I open it on the browser.

on MacOSX, I am using more theses 2 additional define.
 -DOPENSSL_ROOT_DIR=/usr/local/Cellar/openssl@1.1/1.1.1g -DLWS_OPENSSL_INCLUDE_DIRS=/usr/local/Cellar/openssl@1.1/1.1.1g/include/

Am I doing something wrong?

**Comment by lws-team** [comment] 2020-07-13 17:12
Other server examples have assets like images and so on that they look for in ./, his particular example doesn't care except the script must be in the cwd.  But it sounds like you did that.

Build with -DLWS_WITH_MINIMAL_EXAMPLES=1 is a good way, I did that but cd into the example dir where the script was, then actually run `../../../build/bin/lws-minimal-http-server-cgi`

If I run the script by hand, he says like

```
$ ./my-cgi-script.sh 
content-type: text/html
transfer-encoding: chunked

<html><meta charset=UTF-8><body>
<h1>lwstest script stdout</h1>
lwstest script stderr: REQUEST_METHOD was <h2>REQUEST_METHOD=</h2>
<table>
<tr><td colspan="2">/proc/meminfo</td></tr>
<tr><td>MemTotal</td>
<td>8026572 kB</td></tr>
<tr><td>MemFree</td>
<td>521016 kB</td></tr>
<tr><td>MemAvailable</td>
<td>893536 kB</td></tr>
<tr><td>Buffers</td>
<td>61152 kB</td></tr>
<tr><td>Cached</td>
<td>2255520 kB</td></tr>
<tr><td>SwapCached</td>
<td>148976 kB</td></tr>
<tr><td>Active</td>
<td>4731020 kB</td></tr>
<tr><td>Inactive</td>
<td>2041108 kB</td></tr>
<tr><td>Active(anon)</td>
<td>4433776 kB</td></tr>
<tr><td>Inactive(anon)</td>
<td>1740536 kB</td></tr>
<tr><td>Active(file)</td>
<td>297244 kB</td></tr>
<tr><td>Inactive(file)</td>
<td>300572 kB</td></tr>
<tr><td>Unevictable</td>
<td>68680 kB</td></tr>
<tr><td>Mlocked</td>
<td>1744 kB</td></tr>
<tr><td>SwapTotal</td>
<td>8179708 kB</td></tr>
<tr><td>SwapFree</td>
<td>5131196 kB</td></tr>
<tr><td>Dirty</td>
<td>588 kB</td></tr>
<tr><td>Writeback</td>
<td>0 kB</td></tr>
<tr><td>AnonPages</td>
<td>4508064 kB</td></tr>
<tr><td>Mapped</td>
<td>1444840 kB</td></tr>
<tr><td>Shmem</td>
<td>1717416 kB</td></tr>
<tr><td>KReclaimable</td>
<td>172080 kB</td></tr>
<tr><td>Slab</td>
<td>486496 kB</td></tr>
<tr><td>SReclaimable</td>
<td>172080 kB</td></tr>
<tr><td>SUnreclaim</td>
<td>314416 kB</td></tr>
<tr><td>KernelStack</td>
<td>20112 kB</td></tr>
<tr><td>PageTables</td>
<td>69528 kB</td></tr>
<tr><td>NFS_Unstable</td>
<td>0 kB</td></tr>
<tr><td>Bounce</td>
<td>0 kB</td></tr>
<tr><td>WritebackTmp</td>
<td>0 kB</td></tr>
<tr><td>CommitLimit</td>
<td>12192992 kB</td></tr>
<tr><td>Committed_AS</td>
<td>15638188 kB</td></tr>
<tr><td>VmallocTotal</td>
<td>34359738367 kB</td></tr>
<tr><td>VmallocUsed</td>
<td>42856 kB</td></tr>
<tr><td>VmallocChunk</td>
<td>0 kB</td></tr>
<tr><td>Percpu</td>
<td>9408 kB</td></tr>
<tr><td>HardwareCorrupted</td>
<td>0 kB</td></tr>
<tr><td>AnonHugePages</td>
<td>0 kB</td></tr>
<tr><td>ShmemHugePages</td>
<td>0 kB</td></tr>
<tr><td>ShmemPmdMapped</td>
<td>0 kB</td></tr>
<tr><td>FileHugePages</td>
<td>0 kB</td></tr>
<tr><td>FilePmdMapped</td>
<td>0 kB</td></tr>
<tr><td>CmaTotal</td>
<td>0 kB</td></tr>
<tr><td>CmaFree</td>
<td>0 kB</td></tr>
<tr><td>HugePages_Total</td>
<td>0</td></tr>
<tr><td>HugePages_Free</td>
<td>0</td></tr>
<tr><td>HugePages_Rsvd</td>
<td>0</td></tr>
<tr><td>HugePages_Surp</td>
<td>0</td></tr>
<tr><td>Hugepagesize</td>
<td>2048 kB</td></tr>
<tr><td>Hugetlb</td>
<td>0 kB</td></tr>
<tr><td>DirectMap4k</td>
<td>652600 kB</td></tr>
<tr><td>DirectMap2M</td>
<td>7618560 kB</td></tr>
<tr><td>DirectMap1G</td>
<td>0 kB</td></tr>
</table>
<br/>done
</body></html>
```

You can see he can't really make trouble for huge headers like your error says, I dunno what it means.

I also test here with latest chrome, no problem spamming Ctrl-R (he won't repeat if you hold it down).

I check by firefox dev tools, he fetches it on http/1.1 consistent with your settings.

**Comment by lws-team** [comment] 2020-07-14 06:03
Are you sure you have not modified the cgi script to the point of removing the blank line between its generated headers and the body part?  That would give the error you have if it went on to create eg 2KB of body that looked like 2KB of headers.

**Comment by lailton-dev** [comment] 2020-07-14 07:54
Hi @lws-team 
Yes, I am 100% sure that I have not removed it.
Let me ask you, is possible you send me your script .sh and binary file created for macOSX?
then I will try to execute your version on my side to check.
Thanks

**Comment by lws-team** [comment] 2020-07-14 08:25
You do claim it's broken on focal.

Here's what I did to run the test on the Mac Mini

```
diff --git a/minimal-examples/http-server/minimal-http-server-cgi/my-cgi-script.sh b/minimal-examples/http-server/minimal-http-server-cgi/my-cgi-script.sh
index 7437999b..88b213db 100755
--- a/minimal-examples/http-server/minimal-http-server-cgi/my-cgi-script.sh
+++ b/minimal-examples/http-server/minimal-http-server-cgi/my-cgi-script.sh
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 
 echo -e -n "content-type: text/html\x0d\x0a"
 echo -e -n "transfer-encoding: chunked\x0d\x0a"
@@ -19,8 +19,14 @@ if [ "$REQUEST_METHOD" = "POST" ] ; then
 	echo "read=\"$line\""
 else
 	echo "<table>"
+if [ -e /proc/meminfo ] ; then
 	echo "<tr><td colspan=\"2\">/proc/meminfo</td></tr>"
-	cat /proc/meminfo | while read line ; do
+	FI=/proc/meminfo
+else
+	echo "<tr><td colspan=\"2\">no proc meminfo on this box</td></tr>"
+	FI=$0
+fi
+	cat FI | while read line ; do
 		A=`echo "$line" | cut -d: -f1`
 		B=`echo "$line" | tr -s ' ' | cut -d' ' -f2-`
 		echo -e "<tr><td>$A</td>"
```

I tested it using the native browser but I also exposed :7681 at the mac mini and tested it from Firefox on Fedora, no problem either way.

**Comment by lailton-dev** [comment] 2020-07-14 16:31
Sure,
I will test it and I will let you know

**Comment by lailton-dev** [comment] 2020-07-17 05:00
@lws-team 
I did several test but without success. I can run .sh file on terminal without problem.
I can run CGI without problem using CHROME, but the REQUEST_METHOD is empty and not returning the method.

Still the problem if I send a POST the server crash.
`curl --location --request POST 'http://localhost:7681/' \
--header 'Content-Type: application/x-www-form-urlencoded' \
--data-urlencode 'name=testing'`

Thanks

**Comment by lws-team** [comment] 2020-07-17 06:57
> I did several test but without success.
> I can run CGI without problem using CHROME

Hm... that is at least some success isn't it?

> REQUEST_METHOD is empty 

Here, on fedora, it's like this via firefox

```
lwstest script stdout
REQUEST_METHOD=GET

/proc/meminfo
--
MemTotal | 8026572 kB
MemFree | 386796 kB
...
```
and chrome

```
lwstest script stdout
REQUEST_METHOD=GET

/proc/meminfo
--
MemTotal | 8026572 kB
MemFree | 296324 kB
MemAvailable | 637144 kB
...
```

I would guess if this is on OSX for you, that's more about shell env var handling in zsh than about the cgi action.  In both cases it's clean running the cgi test app under valgrind.

> curl --location --request POST 'http://localhost:7681/' \ --header 'Content-Type: application/x-www-form-urlencoded' \ --data-urlencode 'name=testing'

This "seems" to work OK here...

```
$ curl --location --request POST 'http://localhost:7681/' --header 'Content-Type: application/x-www-form-urlencoded' --data-urlencode 'name=testing'
<html><meta charset=UTF-8><body>
<h1>lwstest script stdout</h1>
<h2>REQUEST_METHOD=POST</h2>
CONTENT_LENGTH=12
read="name=testing"
<br/>done
</body></html>
```

... but if I look in valgrind, it provokes trouble and doesn't produce output, so something to do here, I will study it.

**Comment by lailton-dev** [comment] 2020-07-17 12:16
@lws-team 
Interesting how it works to you.
I will do more test and some debugs to see if I can find why it dont work as expected to me.

Thanks.

**Comment by lws-team** [comment] 2020-07-17 12:20
For the push case, something is broken; I'm looking at it.  But you should be able to reproduce my results good and bad at least on Linux.

BTW I spotted something that might explain the env var problem on OSX, IIRC it doesn't have execvpe(), you might want

```
diff --git a/lib/plat/unix/unix-spawn.c b/lib/plat/unix/unix-spawn.c
index 76382070b..190af4291 100644
--- a/lib/plat/unix/unix-spawn.c
+++ b/lib/plat/unix/unix-spawn.c
@@ -511,7 +512,7 @@ lws_spawn_piped(const struct lws_spawn_piped_info *i)
 	}
 
 #if !defined(LWS_HAVE_VFORK) || !defined(LWS_HAVE_EXECVPE)
-#if defined(__linux__)
+#if defined(__linux__) || defined(__APPLE__)
 	m = 0;
 	while (i->env_array[m]){
 		char *p = strchr(i->env_array[m], '=');
```

**Comment by lailton-dev** [comment] 2020-07-17 12:22
Let me check

**Comment by lailton-dev** [comment] 2020-07-17 13:19
@lws-team 

Good catch!
Now it is returning the value REQUEST_METHOD as expected :)

Here you have a screenshot when a METHOD POST is received it crash.

<img width="1566" alt="Screen Shot 2020-07-17 at 10 17 09" src="https://user-images.githubusercontent.com/58268709/87790374-db29b200-c816-11ea-9e19-25eda62cad22.png">

You can see on left side the output looks ok, so it is something when it is trying to "free" something.

**Comment by lailton-dev** [comment] 2020-07-17 13:29
@lws-team 

I have commented the line close.c 176  **lws_free(wsi);**  then it stop to crash.

I have tried to use
`if(wsi)
lws_free(wsi);
`
but still the problem, only works when I remove it.

**Comment by lws-team** [comment] 2020-07-17 13:46
Yes but that's not where the problem is coming from... I have a patch that's valgrind-clean but I am not sure it's doing the same job for push, you can apply the patches on top from here but it's a WIP

https://libwebsockets.org/git/libwebsockets/log?h=_temp

**Comment by lailton-dev** [comment] 2020-07-17 15:45
@lws-team 

Different error, but still with crash.

<img width="1219" alt="Screen Shot 2020-07-17 at 12 45 18" src="https://user-images.githubusercontent.com/58268709/87805256-6c0a8880-c82b-11ea-83ff-3cf85510ad4b.png">

**Comment by lws-team** [comment] 2020-07-17 15:46
Yes still working on it, there'll be an update shortly.

**Comment by lailton-dev** [comment] 2020-07-17 15:46
@lws-team 

Thanks

**Comment by lws-team** [comment] 2020-07-17 16:12
I update that _temp branch, I am out of time for today.

It works well for me now so long as sleep 0.5 at the end of the script... I tried to work around that but... out of time.  Please give it a go.

**Comment by lailton** [comment] 2020-07-17 18:54
@lws-team 

It works much better now to me and without issue. ( was not needed also the sleep 0.5 ).

I did a test to see quality it and the result was not so good.

**ab -n 100 http://127.0.0.1:7681**

**_Failed requests:        85_**
Requests per second:    13.30 [#/sec] (mean)

<img width="585" alt="Screen Shot 2020-07-17 at 15 46 39" src="https://user-images.githubusercontent.com/59419433/87820833-2d81c780-c845-11ea-8d67-f6e3e88db1e1.png">

Compared with a minimal http server

**Failed requests:        0** GREAT!
**Requests per second:    11911.85 [#/sec] (mean)** GREAT!

<img width="536" alt="Screen Shot 2020-07-17 at 15 51 23" src="https://user-images.githubusercontent.com/59419433/87821091-a3862e80-c845-11ea-8b21-ddb2a4d00e9a.png">

Anyway, the issue was solved, you can close it.

Thank you for your attention and have a nice weekend!

**Comment by lailton-dev** [comment] 2020-07-17 18:56
@lws-team 

It works much better now to me and without issue. ( was not needed also the sleep 0.5 ).

I did a test to see quality it and the result was not so good.

**ab -n 100 http://127.0.0.1:7681**

**_Failed requests:        85_**
Requests per second:    13.30 [#/sec] (mean)

<img width="585" alt="Screen Shot 2020-07-17 at 15 46 39" src="https://user-images.githubusercontent.com/59419433/87820833-2d81c780-c845-11ea-8d67-f6e3e88db1e1.png">

Compared with a minimal http server

**Failed requests:        0** GREAT!
**Requests per second:    11911.85 [#/sec] (mean)** GREAT!

<img width="536" alt="Screen Shot 2020-07-17 at 15 51 23" src="https://user-images.githubusercontent.com/59419433/87821091-a3862e80-c845-11ea-8b21-ddb2a4d00e9a.png">

Anyway, the issue was solved, you can close it.

Thank you for your attention and have a nice weekend!

**Closed** 2020-08-20 18:09 UTC
