### ISSUE TITLE
Closing connection for big ( > 100kb) messages

### ISSUE THREAD

**Issue by theZiz** [warmcat/libwebsockets#392] opened 2016-01-08 12:21 UTC
Hello,

I just noticed, if my application sends quite big messages with libwebsockets, it fails with
```
ERROR xxxxxx writing to socket
```
where xxxxxx is the amount of bytes my appliaction tried to send. Sometimes it is around 140kb, but sometimes even over 400 kb work.
I made a quick and dirty fix in output.c. In `lws_ssl_capable_write_no_ssl` I changed 
```
	n = send(wsi->sock, buf, len, MSG_NOSIGNAL);
	if (n >= 0)
		return n;
```
to
```
	n = send(wsi->sock, buf, len, MSG_NOSIGNAL);
	if (n >= 0)
	{
		int N = n;
		while (N < len)
		{
			buf = &(buf[N]);
			len -= N;
			N = send(wsi->sock, buf, len, MSG_NOSIGNAL);
			n += N;
		}
		return n;
	}
```
However I am quite sure, that this is not the right way to fix this. But it works for me, so maybe it helps you fixing this issue.
Or am I doing something wrong in the very first place?

Greetings, Ziz

**Comment by lws-team** [comment] 2016-01-08 12:40
Yeah as you say, it's not 'the way', although both the hack and the result make the problem nice and clear.

Basically the issue is we take a lot of care to schedule to do that send() after we have been told by poll() that the socket is willing to have stuff sent on it.  However there is no posix api that can tell us how much he is willing to take.  The only way is try it and see afterwards what he took.

If the guy sending allocated that buffer on the stack, we must deal with it right away.  In current lws there is an 'emergency' partial send system that mallocs up a buffer and copies the remainder into there to deal with later (and it schedules more POLLOUT service automatically until that is drained).  It's necessary because under memory pressure send might not send even relatively small buffers.  But obviously malloc and memcpy is not a good thing and makes the memory pressure worse.

The right way to solve this is use ws framing to make your 400KB one ws message that is sent in several smaller ws fragments.  Then your send does not block other connection service, and the smaller individual sends have much lower risk of choking send().

Look at test-fraggle.c for example code but basically you send the first fragment of the message as BINARY | LWS_WRITE_NO_FIN, intermediate ones as CONTINUATION|LWS_WRITE_NO_FIN and the last fragment as CONTINUATION.

**Comment by theZiz** [comment] 2016-01-08 12:59
Thanks for your explanations! I will fix my application like you proposed.

**Comment by rerelease** [comment] 2016-01-08 13:25
I've been having an issue with partial sends for a long time.

I split large messages and send them 4kB at a time. On localhost and most other local machines it works fine. But on one machine (other machines have failed in similar manner) when trying to send a 4.8kB message the first `libwebsocket_write` already returns only 2.8kB and after the other 2kB has been sent to client, the connection is closed by the server.

Meanwhile the client only receives 4.2kB of the message before the connection is dropped.

In tag v1.4 at least, commenting out the following in `output.c` fixes the issue (compiled without extensions and SSL):
``` 
//if (n && wsi->u.ws.clean_buffer)
		/*
		 * This buffer unaffected by extension rewriting.
		 * It means the user code is expected to deal with
		 * partial sends.  (lws knows the header was already
		 * sent, so on next send will just resume sending
		 * payload)
		 */
                 // return n;

```

Running the v1.6 fraggle server on that machine actually gives me an error as well:
```
libwebsockets test fraggle
(C) Copyright 2010-2015 Andy Green <andy@warmcat.com> licensed under LGPL2.1
[1452257974:4416] NOTICE: Initial logging level 7
[1452257974:4417] NOTICE: Libwebsockets version: 1.6.0 27174e6
[1452257974:4417] NOTICE: IPV6 not compiled in
[1452257974:4417] NOTICE: libev support not compiled in
[1452257974:4418] NOTICE:  mem: platform fd map:  8192 bytes
[1452257974:4419] NOTICE:  mem: per-conn:          264 bytes + protocol rx buf
[1452257974:4419] NOTICE:  canonical_hostname = thinkPad-T520
[1452257974:4420] NOTICE:  Listening on port 7681
server sees client connect
Spamming 942 random fragments
[1452257984:6147] ERR: Partial write
Terminating...
[1452257984:6148] NOTICE: lws_context_destroy
```

Is this a bug in libwebsockets? If there was something wrong with how I split messages I would expect the fraggle demo to still work...

**Comment by lws-team** [comment] 2016-01-08 14:03
@rerelease Thanks...I think you're right that code should go.  I just pushed a patch removing it.

Originally the idea was that if the buffer hadn't been mangled, user callback could manage the partial send itself.  But after the partial handling was introduced that's no longer necessary, the partial handling is always safe (if expensive for large buffers).  The code you pointed out actively defeats partial handling so userland can do it, but I think few people are aware the write action may be truncated and they should do something.

So the patch makes the write action always succeed from user callback perspective, by using the partial buffering.  It's likely behind @theZiz's problem too.

**Comment by lws-team** [comment] 2016-01-12 00:58
I'll close this... if any related trouble still coming, please reopen.

**Closed by lws-team** 2016-01-12 00:58 UTC
