### ISSUE TITLE
libwebsocket connection to socket.io

### ISSUE THREAD

**Issue by hemanth4ap** [warmcat/libwebsockets#531] opened 2016-05-19 04:27 UTC
Hi ,
I am communicating between libwebsocket and socket.io. client is libwebsocket and server is socket.io. my client sending connection request after connected server sending pingtimeout like 0{"sid":"SVqOMAeGZDrYTuhAAAAA","upgrades":[],"pingInterval":25000,"pingTimeout":60000} . if event not there within timeout in client connection closing. in server side it shows like connection is closed by client because of pingtimeout. but i want connection keep always open. Is it possible?

**Comment by lws-team** [comment] 2016-05-19 04:45
Thanks for opening a new issue.

If the connection is in http state (didn't upgrade) ws will close idle kept-alive connections himself after 60s.

In ws state though, he has no active timeout on lws side.

And your server is not in a position to judge why the client has closed in terms of whether it was a ping timeout, he's only in a position to close it because he thinks it didn't respond to his ping.  So unless I misunderstood your description, actually the problem is related to socket.io closing the connection because he felt he didn't get a PING response.  Does that seem correct?

**Comment by hemanth4ap** [comment] 2016-05-19 05:21
This is my code please find attached file,

[code.txt](https://github.com/warmcat/libwebsockets/files/271883/code.txt)

these are socket io logs:
-----------------------------
engine handshaking client "UG0cAUdj8FoGWMz1AAAB" +1m
  engine:socket sending packet "open" ({"sid":"UG0cAUdj8FoGWMz1AAAB","upgrades":[],"pingInterval":25000,"pingTimeout":60000}) +3ms
  engine:socket flushing buffer to transport +3ms
  engine:ws writing "0{"sid":"UG0cAUdj8FoGWMz1AAAB","upgrades":[],"pingInterval":25000,"pingTimeout":60000}" +2ms
  engine:transport setting request +6ms
  socket.io:server incoming connection with id UG0cAUdj8FoGWMz1AAAB +0ms
  socket.io:client connecting to namespace / +8ms
  socket.io:namespace adding socket to nsp / +4ms
  socket.io:socket socket connected - writing packet +2ms
  socket.io:socket joining room /#UG0cAUdj8FoGWMz1AAAB +6ms
  socket.io:client writing packet {"type":0,"nsp":"/"} +2ms
  socket.io-parser encoding packet {"type":0,"nsp":"/"} +6ms
  socket.io-parser encoded {"type":0,"nsp":"/"} as 0 +0ms
  engine:socket sending packet "message" (0) +7ms
  engine:socket flushing buffer to transport +0ms
  engine:ws writing "40" +0ms
a user connected
  socket.io:socket joined room /#UG0cAUdj8FoGWMz1AAAB +4ms
  engine:ws received "5:::hello world" +2ms
  engine:socket packet +4ms
  engine:ws received "5:::hello world" +7ms
  engine:socket packet +0ms

  engine:ws closing +1m
  socket.io:client client close with reason ping timeout +5ms
  socket.io:socket closing socket - reason ping timeout +0ms

**Comment by lws-team** [comment] 2016-05-19 06:23
unless there's something unexpected about lws pingresponse, this seems to be decided by socket.io, I think you're going to have to ask them why it times out at 60s.

**Comment by alexhultman** [comment] 2016-05-19 17:31
@hemanth4ap You cannot use Socket.IO against a regular WebSocket server. Socket.IO uses Engine.IO which implements its own protocol, with its own pings which libwebsockets will not respond to. You will have to connect Socket.IO Client <-> Socket.IO Server.

**Comment by lws-team** [comment] 2016-05-19 21:43
Googling around after what Alex said, and looking at the fact he can negotiate a ws connection with lws, it is using standard websockets underneath.

But it seems to have assumptions on top about the ws protocol running on it... to interoperate with it will require you to follow its expectations about its protocol.  Since it otherwise seems to work for you, maybe that's just a matter of supporting its non-ws PINGs correctly.

**Comment by hemanth4ap** [comment] 2016-05-20 12:39
thank you .
My application is communication between libwebsocket and socket.io . on server side socket.io using . in client side libwebsocket. can u tell me libwebsocket 1.5 is better or 2.0 is better for socket.io communication.
my application is real time application, libwebsocket want to send more data like 'tcpdump' information to socket.io server

**Comment by lws-team** [comment] 2016-05-20 12:52
Lws provides the websocket layer only, it has no idea what socket.io protocol on top of ws is. (In that sense, lws 1.5 or 2.0 are the same.)

So to get the two sides communicating, you will have to do some work adding what socket.io expects to see in the ws protocol.  It seems from what you wrote it kinda worked already and just needs the PING support.

If you're okay with taking that job on, it should be possible to make it work well.

If you get it working and feel like sharing it I'd be happy to add it to lws directly if it's reasonable to integrate.

If you have a choice, it's better to use lws 2.0 since this is supported and 1.5 isn't updated any more.

**Comment by lws-team** [comment] 2016-05-24 07:12
There seems to be nothing for me to do here, if there's progress or more questions please reopen.

**Closed by lws-team** 2016-05-24 07:12 UTC

**Comment by tayenderkumar** [comment] 2019-04-01 09:58
Hello @hemanth4ap ,

Could you please share your client side code. I am trying to do the same, as, i am trying to connect a libwebsocket client to a socket.io server. But i am not able to establish connection between the two.
