### ISSUE TITLE
200 established tcp connection limit

### ISSUE THREAD

**Issue by xmanmax** [warmcat/libwebsockets#1175] opened 2018-02-08 04:09 UTC
hi, lws team 

I met a problem about websockets connections count limit. I have about 2000 devices ,and will connect my ws server at one time, but I found that only about 200 devices can connect succeed.
I tried to optimize linux net parameter as below:

net.ipv4.tcp_syncookies = 1 
net.ipv4.tcp_max_syn_backlog = 16384  
net.core.netdev_max_backlog = 20000
net.ipv4.tcp_fin_timeout = 60
net.ipv4.tcp_tw_reuse = 0
net.ipv4.tcp_tw_recycle = 0
net.ipv4.tcp_synack_retries = 2 
net.ipv4.tcp_retries2 =15
net.ipv4.tcp_max_orphans =4096
net.ipv4.tcp_orphan_retries=1
net.ipv4.ip_local_port_range = 1024 65535 
net.ipv4.tcp_max_syn_backlog = 1024
net.ipv4.tcp_synack_retries = 2
net.ipv4.ip_local_port_range=1024 65535 
net.core.somaxconn=32768
fs.file-max = 1000000

lws version: v2.4-stable
openssl : 1.1.0f, 
OS: ubuntu platform

do you have any suggest?

T&R

**Comment by lws-team** [comment] 2018-02-08 06:31
You can easily have 100,000 or more connections with lws.  There's no need to do any kernel tuning, although uou will need to mess with the ulimit for the process beyond whatever the OS default process limit is (eg 1024 in Fedora).

The question is happens in lws when you add the 201'st client?

**Comment by xmanmax** [comment] 2018-02-08 07:02
hi, thx for your reply
test my ulimit as below:

_ulimit -n_ 
1000000

200 connections is just a approximate number，the range about 150~300，I have a monitor platform, and tcp established rate as below:
![7](https://user-images.githubusercontent.com/29703035/35959546-07a6dfd6-0ce1-11e8-9591-945373e7ec8e.jpeg)

**Comment by lws-team** [comment] 2018-02-08 07:06
So, what happens in the lws logs for the failed connections?

**Comment by xmanmax** [comment] 2018-02-08 09:33
hi, that is about 15M, I simulated 10000 devices, and tried to connect my ws server one by one using a loop. then I can not visit my http api at this time, looks like socket hung .
[lwslog.zip](https://github.com/warmcat/libwebsockets/files/1706427/lwslog.zip)

**Comment by xmanmax** [comment] 2018-02-09 10:10
hi, anything new?
I got net data using tcpdump and analyzed them with wireshark, found that sometimes it looks like https packages and sometimes tcp.
1st
![11](https://user-images.githubusercontent.com/29703035/36022494-48f63a48-0dc4-11e8-8c8c-abf536a43d8a.jpeg)

2nd
![22](https://user-images.githubusercontent.com/29703035/36022529-68e30278-0dc4-11e8-9984-8e4f041ecded.jpeg)

**Comment by lws-team** [comment] 2018-02-09 10:36
That's not related... it looks like libev support in lws has some problem.  Is there a reason you are using libev (you didn't mention it until I look at the 145MB log you sent...) and not, eg, libuv?  This doesn't have any probs as far a I know.

**Comment by lws-team** [comment] 2018-02-19 02:52
Actually I was mistaken, libev and libevent work OK.  But their own library headers conflict with each other at build-time if both are enabled, eg

```
/usr/include/event2/event.h:#define EV_READ		0x02
/usr/include/event2/event.h:#define EV_WRITE	0x04
```

/usr/include/ev.h

```
  EV_READ     =            0x01, /* ev_io detected read will not block */
  EV_WRITE    =            0x02, /* ev_io detected write will not block */
```

I pushed a patch enforcing that both cannot be enabled for compile at the same time.  After that, they work OK.

Running `libwebsockets-test-server-libev` against ab, with 700 x concurrent for 200K fetches of test.html, I get:

```
$ ab -c 700 -n 200000 http://127.0.0.1:7681/test.html
This is ApacheBench, Version 2.3 <$Revision: 1807734 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)
Completed 20000 requests
Completed 40000 requests
Completed 60000 requests
Completed 80000 requests
Completed 100000 requests
Completed 120000 requests
Completed 140000 requests
Completed 160000 requests
Completed 180000 requests
Completed 200000 requests
Finished 200000 requests


Server Software:        
Server Hostname:        127.0.0.1
Server Port:            7681

Document Path:          /test.html
Document Length:        66872 bytes

Concurrency Level:      700
Time taken for tests:   50.031 seconds
Complete requests:      200000
Failed requests:        0
Total transferred:      13392800000 bytes
HTML transferred:       13374400000 bytes
Requests per second:    3997.56 [#/sec] (mean)
Time per request:       175.107 [ms] (mean)
Time per request:       0.250 [ms] (mean, across all concurrent requests)
Transfer rate:          261418.60 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   1.6      0      51
Processing:    16  175  15.1    172     260
Waiting:       12  174  15.1    172     260
Total:         62  175  14.5    172     260

Percentage of the requests served within a certain time (ms)
  50%    172
  66%    177
  75%    181
  80%    184
  90%    193
  95%    199
  98%    217
  99%    224
 100%    260 (longest request)
```

ie, no problem.  Can you pull and build latest master and try the same test?

**Comment by lws-team** [comment] 2018-02-19 09:06
Not sure if it will get solved, but FYI https://github.com/libevent/libevent/issues/596

**Comment by lws-team** [comment] 2018-02-22 23:55
Closing as can't reproduce.

**Closed by lws-team** 2018-02-22 23:55 UTC

**Comment by xmanmax** [comment] 2018-02-26 09:41
hi, sorry for late replay
I test latest master and tried " ab -c 700 -n 200000 http://127.0.0.1:7681/test.html", that is fun like yours.
but I did some changes:
in test_server_http.c :
```
try_to_reuse:
	if (lws_http_transaction_completed(wsi))
		return -1;
```

I commit out " if (lws_http_transaction_completed(wsi)) return -1;" , "return 0" directly.

Because for my business, I will hold the request socket 5 seconds, and after that , send response to the request url, so I cannot return -1, which will free the wsi.

btw, 
my business logic , there are 3 part : device, ws-server, other web server, the relationship is:
device <--protocol: websockets --> ws-server <--protocol: http-- > other web server
if "other web server" will send msg to "device“ through "ws-server", "ws-server" will wait "device" response and send the response to "other web server", timeout is 5 seconds, so I will hold the "other web server" request for 5 seconds.

**Comment by xmanmax** [comment] 2018-02-26 09:48
after commit out 
```
if (lws_http_transaction_completed(wsi))
		return -1;
```
result as below:
~$ ab -c 700 -n 200000 http://127.0.0.1:7681/test.html
This is ApacheBench, Version 2.3 <$Revision: 1528965 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking 127.0.0.1 (be patient)


apr_pollset_poll: The timeout specified has expired (70007)

**Comment by lws-team** [comment] 2018-02-26 10:28
No offense... but so what?  If you comment out two random lines that is in several paths of the code, something breaks.  What should I do about that, do you think?

**Comment by xmanmax** [comment] 2018-02-27 02:28
hmmm., I mean I have to hold the sockets, if "return -1", the sockets will lost, do you have some suggestion about this scenario?

**Comment by xmanmax** [comment] 2018-02-27 02:43
I see that struct lws has "outer_will_close", but do not find any interface to update it .

**Comment by lws-team** [comment] 2018-02-27 04:14
Http has three choices, hang up after the transaction completes, or if http/1.1 and /or the connection is marked "keep-alive", then it can process or wait for a new http transaction to start on the same connection.  Lastly,if an http/2 client, it can handle multiple simultaneous transactions independently.

`lws_http_transaction_completed()` is the guy that makes the decision about what to do when your particular http transaction completes, considering all that.  You can't just comment it out and expect normal operation.

So... why is it that you think you need the http connection to stay up 'for 5s' after it finished the transaction?

**Comment by xmanmax** [comment] 2018-02-27 06:08
So... why is it that you think you need the http connection to stay up 'for 5s' after it finished the transaction?

thanks, and when I received a http message, I do not know what will response until "Device" give me the response or nothing, so I stay up '5s‘。

as related as above, ws-server will transfer all messages:

**device <--protocol: websockets --> ws-server <--protocol: http-- > other web server**
two cases:
after 'other web server' send an http request to 'ws-server'

1) if 'device'  give me response within 5s, i will put the 'device' response body as my http response body and send it to 'other web server'
2) if device not give me response within 5s, i will put a 'timeout' string as the response body to 'other web server'

**Comment by lws-team** [comment] 2018-02-27 06:52
You should only call `lws_http_transaction_completed()` when you have finished sending whatever you are going to send in response to the transaction.  Like it says, when the "transaction is completed".

If in fact you handle the HTTP callback, and you don't have any response immediately, you should trigger the device or thread or whatever it is, set a 5s timeout on the wsi and `return 0;`, which effectively does nothing but gives you 5s to do something else or it will hang up on the connection.  The transaction is not completed.  If something calls the WRITABLE callback within 5s and sends the result, then does the transaction completed flow, everything will be OK.  If nothing does anything further, well, that's OK too lws will just hang up on the http client.

I don't really understand what your device does, but, eg, in the case your device is a device node like `/dev/mydevice`, or, '/dev/ttyACM2' etc so it can be polled when it has data ready, a very convenient way to integrate it into the same lws service thread is open an fd on the device node and adopt it using a RAW wsi.

```
typedef enum {
        LWS_ADOPT_RAW_FILE_DESC = 0,    /* convenience constant */
        LWS_ADOPT_HTTP = 1,             /* flag: absent implies RAW */
        LWS_ADOPT_SOCKET = 2,           /* flag: absent implies file descr */
        LWS_ADOPT_ALLOW_SSL = 4,        /* flag: if set requires LWS_ADOPT_SOCKET */
        LWS_ADOPT_WS_PARENTIO = 8,      /* flag: ws mode parent handles IO
                                         *   if given must be only flag
                                         *   wsi put directly into ws mode
                                         */
} lws_adoption_type;

typedef union {
        lws_sockfd_type sockfd;
        lws_filefd_type filefd;
} lws_sock_file_fd_type;

/*
* lws_adopt_descriptor_vhost() - adopt foreign socket or file descriptor
* if socket descriptor, should already have been accepted from listen socket
*
* \param vhost: lws vhost
* \param type: OR-ed combinations of lws_adoption_type flags
* \param fd: union with either .sockfd or .filefd set
* \param vh_prot_name: NULL or vh protocol name to bind raw connection to
* \param parent: NULL or struct lws to attach new_wsi to as a child
*
* Either returns new wsi bound to accept_fd, or closes accept_fd and
* returns NULL, having cleaned up any new wsi pieces.
*
* If LWS_ADOPT_SOCKET is set, LWS adopts the socket in http serving mode, it's
* ready to accept an upgrade to ws or just serve http.
*
* parent may be NULL, if given it should be an existing wsi that will become the
* parent of the new wsi created by this call.
*/
LWS_VISIBLE LWS_EXTERN struct lws *
lws_adopt_descriptor_vhost(struct lws_vhost *vh, lws_adoption_type type,
                           lws_sock_file_fd_type fd, const char *vh_prot_name,
                           struct lws *parent);
```

So you would use LWS_ADOPT_RAW_FILE_DESC and pass a lws_sock_file_fd_type with the .filefd set to the fd you opened on the device.

Then, when the device has something to be read or some other event, you will get these callbacks in the callback for the protocol name you gave when you adopted it

```
        LWS_CALLBACK_RAW_ADOPT_FILE                             = 63,
        /**< RAW mode file was adopted (equivalent to 'wsi created') */
        LWS_CALLBACK_RAW_RX_FILE                                = 64,
        /**< RAW mode file has something to read */
        LWS_CALLBACK_RAW_WRITEABLE_FILE                         = 65,
        /**< RAW mode file is writeable */
        LWS_CALLBACK_RAW_CLOSE_FILE                             = 66,
        /**< RAW mode wsi that adopted a file is closing */
```

With this you can process what your device is saying and talk to it in the saw lws service thread that handles the connections.

**Comment by xmanmax** [comment] 2018-03-02 03:26
Hi, @lws-team , thanks for your suggestion and say sorry for the trouble :

'device' a physical device, eg, a electricity meter , an intelligent device , even our mobil phone. 
they will keep long-term connection with my server which based on lws.

and 'other web server' is a web server which is my manage platform not based on lws.
so,  take an example，I will send an control command to a 'device'. it will send to lws-server first and ,lws-server transfer the message to 'device', lws-server used as a proxy, like a bridge between 'device' and 'other web server'.

 that will met an scenario:
1) 'other web server' send msg to lws-server with http protocol 
2) lws-server hold the http socket , and send the msg to 'device' with websockets protocol,
3) lws-server wait 'device'`s response for 5s, if 'device' give response( content: xxx) , lws-server return http response(content same with 'device'`s response : xxx) to 'other web server' 
if 5s passed, send http response to 'other web server' with content "time out" directly

dataflow as below:
![dataflow](https://user-images.githubusercontent.com/29703035/36882009-54c6eda6-1e0c-11e8-8555-e50b585db05a.png)

so ,I can not control device`s behavior.
after receive http message, lws-server "return 1" in callback  will send FIN to 'other web server' directly. 
I tried to 'return 0' ,but it will hung up the callback you know, that block me here.

**Comment by xmanmax** [comment] 2018-03-02 03:57
Furthermore, there was a strange phenomenon， after changed 'return 1' --> 'return 0', used ab to test  like :ab -c 700 -n 200000 http://127.0.0.1:7681/test.html,
it will sned http response 4 by 4. that looks strange

**Comment by xmanmax** [comment] 2018-03-05 08:10
hi, @lws-team , that`s my fault, I set lws creation info "max_http_header_pool = 4", then it process 4 messages once...
I used the method you mentioned  , that`s ok now, thank you very much and sorry for the inconvenience.

**Comment by lws-team** [comment] 2018-03-05 08:32
No worries, I am glad you are working.
