### ISSUE TITLE
Server closed wsi right after connection established without sending LWS_CALLBACK_CLOSED callback

### ISSUE THREAD

**Issue by orenzvuluni** [warmcat/libwebsockets#1156] opened 2018-01-17 12:52 UTC
Hi,
I am using web-sockets server 2.2 version.
my scenario is very specific:
1. open first JavaScript client --> connection established 
2. the server is sending data to all clients(now only one is connected) every half second
3. open second JavaScript client -- > connection established
4. a little bit data successfully sended from the client to the new client. 
4.the server closing the second client  wsi(with no actual reason) and no LWS_CALLBACK_CLOSED callback arrived.
5. when i am trying to open again new client the server crash with error printing:

>  libwebsocketss-  error: “insert_wsi_socket_into_fds: Assertion `context->lws_lookup[wsi->desc.sockfd]  == 0' failed”.

this happens only when the server sending data sequentially for all the clients(in my case only one connected), and a new client connected successfully and receiving the data from the server.

it's not happens when:
I open one client and the server is not sending data sequentially, and then i open another client,                    everything is O.K and working as accepted. also if now the server will start to send data sequentially to the clients, everything is working O.K.

Thanks a lot,
Oren

**Comment by lws-team** [comment] 2018-01-17 12:58
1) Still have a problem with current master lws?  V2.2 is too old for debugging attention.

2) Problem can be reproduced with, eg, mirror protocol on test server?

3) Threads involved on your side?

**Comment by orenzvuluni** [comment] 2018-01-17 13:20
1-2. I need to check it, it's will take me some time.
3.Only one thread is running the server.

I will check with the latest stable version and with the tests clients and i will write here again.

Thanks, 
 Oren

**Comment by lws-team** [comment] 2018-01-18 01:20
Also... what platform is this on?

**Comment by orenzvuluni** [comment] 2018-01-18 06:56
Linux platform

**Comment by lws-team** [comment] 2018-01-18 07:00
Linux is good since that's what it's developed and tested on.  But it's kind of even harder to understand... seems the fd closed but no reaction from lws.  If you still see it with later lws, please try the test server and see if you get the same.

Anything strange about the libc?

**Comment by orenzvuluni** [comment] 2018-01-18 07:13
O.K, I will try it with the latest version and the tests server.
Sorry, I didn't understand your question about the libc..

Oren

**Comment by lws-team** [comment] 2018-01-19 13:55
There's nothing for me to do about this, so I will close it.  But I will still see any new replies on the issue and happy to look into it if more info coming.

**Closed by lws-team** 2018-01-19 13:55 UTC

**Comment by orenzvuluni** [comment] 2018-01-23 08:38
Hi,
I forgot to say that my platform is not linux PC, its linux embedded and i am using the cross compiled static library.

**So i Checked Other versions:**
1. my embedded Linux device  with  master version cross compiled static library  and i can't  even      established single connection with  the server (with same JavaScript client)
 the server is running and everything seems O.K but the connection is always closed, it's even not getting into the callback with "LWS_CALLBACK_ESTABLISHED" .
Can you point on something that make this problem?

2. My Linux PC with version 2.2 static library and application that i made that is very similar to my embedded application -  everything works as exacted.

3. My Linux PC with master version static library and application that i made that is very similar to my embedded application -  everything works as exacted.

I will make test on Beagle-bone black that is more powerful than my device and write here the results.

**Comment by lws-team** [comment] 2018-01-23 08:41
lws works with ESP32.  So it doesn't have some huge expectation about resources.

> cross compiled static library.

What is the libc?  Because it sounds something broken there, not with lws.

> Can you point on something that make this problem?

Does it really seem that lws makes this problem or something on your side?

**Comment by orenzvuluni** [comment] 2018-01-23 09:01
**glibc version:** 
GNU C Library (Ubuntu EGLIBC 2.15-0ubuntu10) stable release version 2.15, by Ro.

**Comment by lws-team** [comment] 2018-01-23 09:04
You're statically linking against that?  The binary must be pretty big.

If not, and it dynamically links to it (check with ldd or objdump -x ) is there possibly some mismatch between the glibc headers you are using on the cross-build machine (stdio.h etc) and the glibc that is on the target device?

**Comment by orenzvuluni** [comment] 2018-01-23 10:56
**it's dynamically allocated:**
objdump -x <MY_BINARY_FILE>  | grep libc
  NEEDED               libc.so.6

**I checked the libc version in the cross build directory(on my build machin):**
oren_pv@oren-ubuntu: ls -l /opt/arm-linux-gnueabihf/libc/lib/arm-linux-gnueabihf/libc.so.6
lrwxrwxrwx 1 pv_server pv_server 12 Mar 14  2013 /opt/arm-linux-gnueabihf/libc/lib/arm-linux-gnueabihf/libc.so.6 -> libc-2.15.so

**i checked the libc version in the target device:**
root@varsomam33:~# /lib/libc.so.6 
GNU C Library (Ubuntu EGLIBC 2.15-0ubuntu10) stable release version 2.15, by Roland McGrath et al.


also i checked it on runtime in my application c code and i'ts  2.15 version.

**Comment by lws-team** [comment] 2018-01-23 11:02
Okie but are you sure when lws builds, it builds using the glibc **headers** from the cross build root?

I would assume the build machine has a much different glibc version and modern includes in its own /usr/include.  If some things don't match at dynamic link time, it can break things.  (Although to be honest I dunno why it would break open / read etc).

You can check it quickly, just put a syntax error at the top of /usr/include/stdio.h temporarily and see if remake cross-lws is still happy to build.

If that isn't it, also think about run the lws test under strace, and look for strange things coming with the related syscalls in strace dump.

**Comment by orenzvuluni** [comment] 2018-01-28 07:18
I am sorry about the late response.

> You can check it quickly, just put a syntax error at the top of /usr/include/stdio.h temporarily and see if remake cross-lws is still happy to build.

I tried this  and there is no error --> it builds using the glibc headers from the cross build root.

I wiil run lws test and my application under strace and see what i get.

Oren
