### ISSUE TITLE
Looking for an ESP32 version ...

### ISSUE THREAD

**Issue by nkolban** [warmcat/libwebsockets#776] opened 2017-02-07 16:43 UTC
Is there a plan to provide an ESP32 version?  If I can offer assistance on a port, I'd be delighted ...

**Comment by lws-team** [comment] 2017-02-07 22:26
Yeah... I have ordered some esp32 a couple of days ago.

Esp8266 is very cool but it was only just able to deal in the real world with network scenarios as complex as the lws test server.  I didn't have tls support and the whole thing is at danger of transient global heap underrun with complex apps on top of the networking.

ESP32 sounds like it has enough sram to be really useful.

What is the situation with tls stack in the sdk?

**Comment by nkolban** [comment] 2017-02-08 01:25
The software stack on ESP32 is called "ESP-SDK" and includes full sockets API support plus threading.  The TLS stack is mbedtls but there is also an OpenSSL mapping too.  All reports say that it works as hoped.  I speak ESP32 quite well so please feel free to use me in any way you might need.  I don't particularly want to learn LWS internals but perhaps I can help with build environments, or other mechanical aspects of building, testing and debugging on the ESP32.

**Comment by lws-team** [comment] 2017-02-08 01:30
Yeah I appreciate the offer... ESP8266 was very painful.

I am very glad to hear about OpenSSL mapping, that will make things a lot simpler.

I ordered some on Feb 6, I am based in Taiwan so usually not a big delay getting small things from the mainland.  I have a design using ESP8266 + lws, I would much prefer to upgrade that to ESP32 + lws and get proper TLS coming that way.

If you have a quick start link to get known-good toolchain + sdk you can recommend that'd be helpful.

**Comment by nkolban** [comment] 2017-02-08 03:14
I author a free book on the ESP32 that contains toolchain, SDK and other instructions ... see   https://leanpub.com/kolban-ESP32

The formal docs can be found here ... 

http://esp-idf.readthedocs.io/en/latest/

The community forum here ... 

http://esp32.com/index.php


And my direct email is kolban1@kolban.com .... so if you need, just email and I'll do what I can.

**Comment by lws-team** [comment] 2017-02-08 17:36
Thanks... the ESP32 are supposed to be here later today (Thu) so I'll meddle with them over the weekend and update then.  From a quick glance it looks like it's the same basic approach as esp8266 just going to be easier to get started.

**Comment by lws-team** [comment] 2017-02-10 13:53
The boards arrived and I built the toolchain, wired up a module and start to look at building the first app, although that will probably be a job for tomorrow.

In the new buildconfig thing, FreeRTOS is a selectable option... in your opinion how does that play with the tcp/ip stack?  It's a requirement for proper operation?  If it's not selected, we get an event loop as on ESP8266 or something else?

**Comment by nkolban** [comment] 2017-02-10 16:01
Howdy ... feel free to ping me on skype at neil.kolban or on IRC channel `#ESP32` as user "kolban".  I think its probably best we chat rather than trade these issue emails.

Since I understand LWS is a library that can be linked with user applications, then you'll want to embrace FreeRTOS.

**Comment by johsely1234** [comment] 2017-02-14 08:06
Hi,
do you plan to support also the secure version of Websockets (=WSS) ?
And do you also plan to support multiple Websocket-Frames, meaning sending data splitted into multiple frames?

**Comment by lws-team** [comment] 2017-02-14 08:08
Yes, lws is planning to use the OpenSSL wrapper stuff in esp-idf.

lws already natively supports fragmented messages.  The user code can choose the size of each fragment and when to end the message (including endless messages).

**Comment by johsely1234** [comment] 2017-02-14 08:16
Ok, that is very nice! Thanks for the work!

**Comment by johsely1234** [comment] 2017-02-15 08:43
Hello again! 
Do you have an approximate schedule when the port will be finished?

**Comment by lws-team** [comment] 2017-02-15 08:45
Are you offering to help?

**Comment by lws-team** [comment] 2017-02-15 20:38
There seems to be a lof of interest in the status of this.  It's an incomplete WIP but the pieces are public.

I have ported lws to esp-idf

https://github.com/lws-team/lws-esp-idf

and made a test project to use it

https://github.com/lws-team/lws-esp32

The lws patches are already in master and will be updated there as we go.  The plat is incomplete inside but it builds.

The test app can create a context, but when I try to manipulate the fops struct, ESP32 crashes with 'illegal instruction'.  I asked @nkolban about it, he thinks something in the wrong RAM, which sounds feasible, although I dunno how.  However the related code

https://github.com/lws-team/lws-esp32/blob/master/main/main.c#L211

worked on esp8266 and is just setting function pointers in a malloc'd struct.  Commenting that line stops the crash and we continue normally; adding the vhosts also works after that.

I'll have time to look at it again Sat, then I will be traveling and blocked for a few days.  But after that this will probably be a high priority for me since I also want to use it.

If somebody wants to check out the crash problem with the pieces above it'd be a big help and I can spend time on the actual porting not trying to understand whatever quirk is behind that.

**Comment by johsely1234** [comment] 2017-02-16 09:07
Hey,
I am looking into it. Could you push the latest libwebsocket commit?
I get error 'fatal: reference is not a tree: 4ff886ae7af......' when i try to update the submodule 'components/libwebsockets'. 
I tried to checkout the branch 'origin/README_fix' but it is not the correct one i guess.

**Comment by lws-team** [comment] 2017-02-16 09:22
Great.

Yes it's my fault... please pull from lws-esp-idf again then `git submodule update --recursive`

**Comment by johsely1234** [comment] 2017-02-16 13:14
I think the problem is the esp32_lws_fops_open(...) function itself. If i just put a return in the function, I can assign it.

**Comment by johsely1234** [comment] 2017-02-16 13:18
The romfs_get_info(romfs, filename, &len); line seems to crash it.

**Comment by lws-team** [comment] 2017-02-16 13:36
Thanks.. I interpreted the crash as occurring at the setting of the pointer... I "debug by printf" but it can be very misleading if the crash doesn't dump the cached printf data :-/

I enabled bringing in the romfs properly and it seems the crash is gone... I updated esp-lws32 project.

Thanks a lot for the help.

**Comment by johsely1234** [comment] 2017-02-16 15:58
Yes it was kind of hard to debug because the 'invoke the gdb stub' did not work. This is normally a very nice tool to exactly see where the error occured. 
But in this project the esp32 keeps restarting without stopping, I could not figure out why...

**Comment by nkolban** [comment] 2017-02-16 16:41
There is an option in make menuconfig that allows one to define what happens in the event of a panic (crash).  The default is to print the registers and reboot.  This can be changed to enter GDB stub at which point when an exception occurs, the ESP32 halts and you can attach a GDB client.

**Comment by lws-team** [comment] 2017-02-16 18:06
That is the theory, but as @johsely1234 (thanks again) said the practice on this one was a sticky loop of exceptions that also affected the gdb stub entry and had me completely fooled on the where and why.  Anyway it seems unstuck so I'll update with progress Sat.

**Comment by lws-team** [comment] 2017-02-17 12:05
What put it back to normal in the end was marking the functions pointed to as being `IRAM_ATTR`... since pointed-to functions may be called without warning I guess they maybe are all required to be in IRAM.

I pushed an update that builds as far as it got and runs cleanly.  Now try to get it listening...

**Comment by lws-team** [comment] 2017-02-17 14:14
I updated the repos with the current situation, it can listen on port 80, and it processes the incoming headers and tries to serve a file.

But my romfs stuff just crashes after trying to find the file.  I am only trying to use it because that was working on esp8266, it does not have to be.

Looking around in esp-idf, it seems what it wants me to do is wire it up to the vfs component in there, and then, eg, the fat fs parser also provided.  Then somehow bind the fat parser to a "partition".

I will pick this up tomorrow morning as it is late Fri here, if anyone has advice on that plan, or how to set up the partitions, it's very welcome.

It looks like the socket part will be OK it's the filesystem part that is making trouble.

**Comment by lws-team** [comment] 2017-02-18 07:12
OK... it's now able to run in station mode and serve the same set of lws test pieces as other platforms.  In particular the mirror protocol test works stably which is a very good sign.

The main thing was fixing the romfs code to use the spi flash apis and put it in its own partition.

After that, it made almost no trouble on the sockets front in contrast to esp8266.

1)  ESP-IDF
` $ git clone --int --recursive https://github.com/lws-team/lws-esp-idf`

2) Application including the test plugins
` $ git clone https://github.com/lws-team/lws-esp32`

Set your `IDF_PATH` to point to the esp-idf you downloaded in 1)

There's docs for how to build the lws-esp32 test app and reproduce it in the `README.md` here

https://github.com/lws-team/lws-esp32/blob/master/README.md

Next jobs are AP / setup mode like I had on 8266, where you could enter your AP details and it stored them for subsequent boots, and see what the OpenSSL wrapper is like.

**Closed** 2017-03-06 07:45 UTC

**Comment by johsely1234** [comment] 2017-03-06 16:04
Closing means you wont work on it anymore?
Best Regards

**Comment by lws-team** [comment] 2017-03-06 18:41
Not at all... it means I have the non-SSL serving support fully working since my last post and will shortly make a release of lws with it.  So the original issue about ESP32 support is solved.

I started on the SSL stuff last week and will push it when it works.

**Comment by johsely1234** [comment] 2017-03-08 09:02
Ok nice, great to know!

**Comment by lws-team** [comment] 2017-03-10 07:50
An update on this...

 - AP mode now works, and brings up a ws-based scan UI where you can select your AP and give any password, set the device serial number and regulatory region.  This appears by default since the AP info is not set yet.

![lws AP mode config page](https://libwebsockets.org/lws-esp32-ap.png)

 - I refactored all the esp32 generic lws support code into libwebsockets itself, that includes the AP mode protocol and nvs stuff.  That means only stuff related to the user web services is needed in main/main.c

https://github.com/lws-team/lws-esp32/blob/master/main/main.c

since lws provides the test protocols as plugins, we are included into main.c, it makes the lws overhad very small.

There's more info in https://github.com/lws-team/lws-esp32/blob/master/README.md

... now back on ssl...

**Comment by johsely1234** [comment] 2017-03-14 09:16
Its working fine so far!

I used the http-dummy-callback for my connection, because I don't need any protocols. I wonder how I can limit the server to only accept one client at a time? Is there an option for this?

**Comment by lws-team** [comment] 2017-03-14 09:36
Great.

What does "limit... one connection at a time" mean in the context of REST type http connections though?  It's about restricting the max memory usage, or making sure only one guy can use the UI at a time?

**Comment by johsely1234** [comment] 2017-03-14 10:11
Only one guy should be able to connect to the websocket server. Others should not be able to connect at the same time.  In my websocket implementation only one client can be accepted by the underlying (standard) socket at a time.

**Comment by lws-team** [comment] 2017-03-14 13:27
I don't really understand your setup to be sure I get the idea of what you are asking for.

The thing lws connects to has a restriction it can only accept one connection at a time IIUI.

It sounded like you are only using HTTP and not WS, but I guess you are using exactly one WS link in the JS is it?  In that case you would normally handle this kind of thing with an lws protocol.  The protocol would keep a counter in the vhost struct for how many connections are using it... if any are already using it, it can reject the connection in an early callback.  Bump the counter in ESTABLISHED callback and decrement it in CLOSE.

**Comment by johsely1234** [comment] 2017-03-14 15:50
Thanks for your help, I found a solution now that works for me.

I use the esp32 with lws as my websocket server. The client can't use ws-subprotocols, so I can just use a normal websocket connection. (I used websocket.org client for testing)

What works now for me is:
in http-dummy-callback(...):
LWS_CALLBACK_FILTER_NETWORK_CONNECTION -> check client counter, if 0 we can get new client, otherwise just return -1 (quits the connection on network level)

LWS_CALLBACK_ESTABLISHED: -> nothing
LWS_CALLBACK_CLOSED -> set client counter to 0

Best Regards

**Comment by johsely1234** [comment] 2017-03-16 12:46
What is the maximum Payload length that you can send. I tested the esp32 as lws-server and used python as client.

The maximum I found out is 4088 Bytes. Over 4089 Bytes, the RECEIVE callback does not get called.

I set the rx_buffer_size to 65535 Byte (in the lws_protocol) and the info.pt_serv_buf_size to 8192 Byte.

**Comment by lws-team** [comment] 2017-03-16 15:01
I dunno, since that's decided by lwip mtu, the 80211 stack etc.

"Payload" is a bit ambiguous... when you send something over tcp actually it's chopped into packets at or below the link mtu... that's like 1480 or something for Ethernet typically.  For esp32 it seemed to be around 900 here.

As soon as lws receives anything, it passes it up to the RECEIVE callback in whatever size fragment appeared.  So no callbacks, no packet appeared for lws... you should look at lwip I think.

If you talk about ws messages, if you send using ws fragmentation there is no limit to the message size, although it will appear at RECEIVE as it comes and not be assembled in one place first.

**Comment by johsely1234** [comment] 2017-03-16 15:43
Yes it is the TLS mbed maximum message content length. I set it to 8192 and it worked till this point. (possible to set it in make menuconfig)
