### ISSUE TITLE
Get repeated GLib-CRITICAL in console with GLib support enabled.

### ISSUE THREAD

**Issue by RSATom** [warmcat/libwebsockets#1976] opened 2020-07-18 08:34 UTC
When use latest `master` I get

```
GLib-CRITICAL **: 15:28:15.196: Source ID 1 was not found when attempting to remove it
GLib-CRITICAL **: 15:28:16.195: Source ID 5 was not found when attempting to remove it
GLib-CRITICAL **: 15:28:16.195: Source ID 6 was not found when attempting to remove it
<..skipped...>
GLib-CRITICAL **: 15:31:48.611: Source ID 43049 was not found when attempting to remove it
GLib-CRITICAL **: 15:31:48.611: Source ID 43050 was not found when attempting to remove it
GLib-CRITICAL **: 15:31:48.612: Source ID 43051 was not found when attempting to remove it
<..and so on...>
```

On other side, it works fine with latest `v4.0-stable`

**Comment by RSATom** [comment] 2020-07-18 09:30
`git bisect` gave me https://github.com/warmcat/libwebsockets/commit/dfed5475295e552bdbf5165193eb7e40ece71a45 as source of problem

**Comment by lws-team** [comment] 2020-07-18 10:31
Unfortunately that patch is definitely fixing leaks and making things better.

How can I see this problem coming with the minimal examples?

**Comment by RSATom** [comment] 2020-07-18 12:53
I'll try to make minimal example. Right now I can say, I'm using http server and libwebsockets server in my application.

**Comment by RSATom** [comment] 2020-07-18 13:44
After some debugging I found warning come from https://github.com/warmcat/libwebsockets/blob/master/lib/event-libs/glib/glib.c#L220 call.

**Comment by lws-team** [comment] 2020-07-18 13:56
Thanks... is it coming even in the existing minimal examples for this?  If so what's your OS version etc so I can try to reproduce?

**Comment by RSATom** [comment] 2020-07-18 15:21
I found only one minimal example with glib support - minimal-http-server-eventlib-foreign. Tried run it, and it works fine. It looks like I do something different in my code. Investigating...

**Comment by RSATom** [comment] 2020-07-18 16:24
I think I found the reason. In my code I don't use default `GMainContext`, i.e. I do `g_main_context_new` and use it in `g_main_loop_new` (and also do `g_main_context_push_thread_default`). And that's why your code can't destroy idle GSource - it's just looking in wrong context. I'll try to figure out possible workaround.

**Comment by lws-team** [comment] 2020-07-18 16:36
If I understand it, it refers to the loop that you give it (if foreign) to understand what main context to use for the pt that is wanting to do the idle action

https://libwebsockets.org/git/libwebsockets/tree/lib/event-libs/glib/glib.c#n36

assuming your loop is foreign, it's that your loop isn't on your new GMainContext?  or you mean something else?

**Comment by RSATom** [comment] 2020-07-19 02:42
Yes, I use foreign glib loop. You can look at code here: https://github.com/WebRTSP/Native/blob/master/Apps/Proxy/Proxy/Proxy.cpp#L31

**Comment by lws-team** [comment] 2020-07-19 05:10
If you can align the foreign example to make the problem I can definitely try to solve it.  It should have most of the pieces there since it also creates its own external loop etc.

But AFAIK it's always trying to reference the main context via the foreign loop's idea of the main context, not with magic defaults.  That's also true when it creates the idle object, it binds it to the main context given by the foreign loop's idea of the main_context().

```
#define pt_to_loop(_pt)		  ((_pt)->glib.loop)
#define pt_to_g_main_context(_pt) g_main_loop_get_context(pt_to_loop(_pt))
...
	pt->glib.idle.tag = g_source_attach(pt->glib.idle.gs,
					    pt_to_g_main_context(pt));
```

the -foreign example can work OK without errors coming for actual functionality like web serving while the lws_context is up as it is, it seems something missing (compared to your app) from the example that is able to work end-to-end to make the problem.

**Comment by RSATom** [comment] 2020-07-19 05:15
Please don't care about it right now. I'll try to make PR to fix this issue. Don't promise to do it today, but will do it definitely.

**Comment by lws-team** [comment] 2020-07-19 05:16
Thanks, I will leave this open in the meanwhile.

**Comment by lws-team** [comment] 2020-07-19 10:29
Thanks for the patch, it's on master... I guess we can close this too then.

**Closed by lws-team** 2020-07-19 10:29 UTC

**Comment by triplemaya** [comment] 2022-07-28 12:06
Still a problem July 2022

(mate-screensaver:35754): GLib-CRITICAL **: 10:52:37.820: Source ID 461 was not found when attempting to remove it

(mate-screensaver:35754): GLib-CRITICAL **: 10:57:13.130: Source ID 549 was not found when attempting to remove it

(mate-screensaver:35754): GLib-CRITICAL **: 11:04:19.829: Source ID 591 was not found when attempting to remove it

(mate-screensaver:35754): GLib-CRITICAL **: 11:56:58.229: Source ID 637 was not found when attempting to remove it

(mate-screensaver:35754): GLib-CRITICAL **: 12:08:12.829: Source ID 682 was not found when attempting to remove it
