### ISSUE TITLE
1.7 websocket closes without LWS_CALLBACK_CLOSED

### ISSUE THREAD

**Issue by Babel-Fish** [warmcat/libwebsockets#1083] opened 2017-11-01 18:09 UTC
We have encountered scenarios where it seems that the websocket is closed/terminated but we were not notified with LWS_CALLBACK_CLOSED on the server. We seem to observe this when the client is very slow / overwhelmed. I believe the condition is that we have just done a write from the server to the client but this write results in lws_send_pipe_choked now reporting true. The client then disconnects while in this state and we never receive the LWS_CALLBACK_CLOSED. This leaves our application in thinking the connection is still open. We never receive a LWS_CALLBACK_CLOSED nor poll from our pipe write so we can't trigger our own close via lws callback. I believe the issue is if a client disconnects while lws_send_pipe_choked is true.

We were able to reproduce this manually with a fake client app (written using your library) connecting to our server. We block the client in LWS_CALLBACK_CLIENT_RECEIVE and wait for the server to fully backup (lws_send_pipe_choked == true). We then Ctrl+C/Ctrl+Z the process. What is observed is the connection remains open on the server. Wire captures show FIN packet though. 

Is there a way to fix this so that we always get the LWS_CALLBACK_CLOSED? 
Also, is there a way to close the websocket outside of the lws callback? I know it can be done via return code within the lws callback but with lws 1.7, can this be done via api outside of the callbacks? I noticed new apis but according to this post (https://github.com/warmcat/libwebsockets/issues/583) you recommend the WRITEABLE approach.

**Comment by lws-team** [comment] 2017-11-01 22:47
- What platform is this?  Linux?

 - Is it using SSL?

 - Using the compression extension on the connection?

 - Does the problem exist in current lws?

 - Why is there a FIN coming at all if you stalled the test client and background it?  It should just sit there, shouldn't it?  Who sent the FIN?

 - the state of "being choked" mainly means that testing the connection with poll() and no wait, POLLOUT was not coming, ie, it has no way to create your situation directly.  It can have some other reasons to signal choked like being in the middle of a partial write, or the state of things logically inbetween the two peers though.

 - what does netstat (or equivalent) show about the actual state of the connection at the server and client?

About closing outside the event loop, you can set the timeout on the wsi to -1.  It will be closed on the next timeout check, around once per second.  On later lws, you can set it to -2, and it will be closed synchronously before returning from the set timeout api.

**Comment by Babel-Fish** [comment] 2017-11-02 17:53
- Linux
- No ssl
- Yes compression
- Not sure as we are on 1.7
- FIN would not come while blocked but rather after Ctrl+C/Ctrl+Z
- Not sure on netstat and will report back when I have info

I like the idea of timeout and will look into that on the side.

**Comment by lws-team** [comment] 2017-11-02 22:18
If the problem exists in current lws it's a lot more interesting to spend time on it.  v1.7 is from 21 months ago, there have been 5 releases since then.

Ctrl-C and Ctrl-Z do different things... if you are Ctrl-C-ing the client yes it will send a FIN.

Please try disabling the compression extension and see if the problem is still coming (return 1 from LWS_CALLBACK_CLIENT_CONFIRM_EXTENSION_SUPPORTED in protocols[0]) or build lws with -DLWS_WITHOUT_EXTENSIONS=1 ) that will narrow it down.

**Comment by Babel-Fish** [comment] 2017-11-06 21:06
@lws-team Sorry for the delayed response as I was pulled away. Can you quickly elaborate on the timeout suggestion? Is that:
`libwebsocket_set_timeout` or `libwebsocket_service`

Do you have an example code sample?

**Comment by Babel-Fish** [comment] 2017-11-07 16:00
@lws-team Can you confirm which API and params I should be using? I am not finding the following making a difference. Thanks

`lws_set_timeout(m_wsi, NO_PENDING_TIMEOUT, -1);`

**Comment by lws-team** [comment] 2017-11-07 16:12
Anything except NO_PENDING_TIMEOUT, which means... there is no pending timeout.  Replace that with, eg, 1.

**Comment by Babel-Fish** [comment] 2017-11-07 16:13
@lws-team this is why I avoid vegas...... Retrying now. thanks

**Comment by lws-team** [comment] 2017-11-09 00:22
Any news on if disabling compression helped?  Or how to reproduce on master?

**Closed** 2017-11-10 10:38 UTC
