### ISSUE TITLE
Less than 1 milliseconds waits to next event are done with high CPU load

### ISSUE THREAD

**Issue by martlaak-gmail** [warmcat/libwebsockets#2039] opened 2020-09-08 06:27 UTC
In cases there is less than millisecond to wait to next event, lws_service() exits immediately without any wait, causing high CPU load.

For example we experienced considerable CPU load increase after migrating to libwebsockets 4.x with code like this:
```
static void cancelLwsServiceLoop(lws_sorted_usec_list_t *sul)
{
  auto d = lws_container_of(sul, struct WebSocketContext::Private, lwsSul);
  d->cancelService();
}
...
void OurWrapperClassToLibWebsockets::service(int ms)
{
  d->serviceTimedOut = false;
  lws_sul_schedule(d->lwscontext, 0, &d->lwsSul, d->cancelLwsServiceLoop, ms * 1000);
  while (lws_service(d->lwscontext, 0) >= 0 && !d->serviceTimedOut)
    ;
}
```
IMO poll() with 0 timeout should be avoided, eg like that:
```
diff --git a/lib/plat/unix/unix-service.c b/lib/plat/unix/unix-service.c
index 7bb22ed6..1469cb58 100644
--- a/lib/plat/unix/unix-service.c
+++ b/lib/plat/unix/unix-service.c
@@ -127,7 +127,10 @@ _lws_plat_service_tsi(struct lws_context *context, int timeout_ms, int tsi)
 
        /* ensure we don't wrap at 2^31 with poll()'s signed int ms */
 
-       timeout_us /= LWS_US_PER_MS; /* ms now */
+       if (timeout_us > 0 && timeout_us < LWS_US_PER_MS)
+               timeout_us = 1; // timeout between 0..1000 us should be rounded to 1 ms - otherwise we end up with CPU-based wait
+       else
+               timeout_us /= LWS_US_PER_MS; /* ms now */
 
        vpt->inside_poll = 1;
        lws_memory_barrier();
diff --git a/lib/plat/windows/windows-service.c b/lib/plat/windows/windows-service.c
index 1b8313fb..f4ce3bf6 100644
--- a/lib/plat/windows/windows-service.c
+++ b/lib/plat/windows/windows-service.c
@@ -159,8 +159,13 @@ _lws_plat_service_tsi(struct lws_context *context, int timeout_ms, int tsi)
                       FD_ROUTING_INTERFACE_CHANGE |
                       FD_ADDRESS_LIST_CHANGE);
 
+       if (timeout_us > 0 && timeout_us < LWS_US_PER_MS)
+               timeout_us = 1; // timeout between 0..1000 us should be rounded to 1 ms - otherwise we end up with CPU-based wait
+       else
+               timeout_us /= LWS_US_PER_MS; /* ms now */
+
        ev = WSAWaitForMultipleEvents(1, &pt->events, FALSE,
-                                     (DWORD)(timeout_us / LWS_US_PER_MS), FALSE);
+                                     (DWORD)timeout_us, FALSE);
        if (ev != WSA_WAIT_EVENT_0)
                return 0;
 ```

**Comment by lws-team** [comment] 2020-09-08 08:09
> In cases there is less than millisecond to wait to next event, lws_service() exits immediately without any wait, causing high CPU load.

You're right, but the difficulty with this is there are also pathological cases (eg, callback reschedules with a few us interval) that are unable to perform above 1000/s if they are rounded up to 1000us.  In fact poll() seems to cost around 150us on a typical linux system so that's the difference between 150us and 1000us interval, or 6x reduction in throughput for small interval case.

lws_sul() was mainly designed with facilitating UDP retries in mind, for these since they go out directly, serialized the network interface, it's definitely better latency- and mbuf- wise if they are happening staggered inside 1ms rather than all passed to the IP stack at 1ms boundaries.

Ideally poll() would have accepted us-resolution timeouts like select() did, but it doesn't, and select() doesn't scale well to large numbers of fds.  For freertos platform, where it will care most about power typically, actually it uses native us-resolution select() and doesn't have this problem.

The actual problem is if we wake < 1ms early, we may spin for 500us on average (it means ~3 times around the poll() event wait) until we reach the sul timeout and clear it.  For typical user code, this isn't going to affect power consumption much because they don't have lws_sul coming ripe very often... there may be many lws_sul but they are things like timeouts, which are cancelled before coming ripe.

I think maybe it's good to look instead at why your outer code looks like it does... you seem to be concealing that lws uses event loop semantics, but that's quite an impedance mismatch then (one that I have seen repeated over and over by C++ users of lws over the years).  Why not just have the C++ code on the event loop and this lws_sul can go away?

**Comment by martlaak-gmail** [comment] 2020-09-08 08:55
Our code is that way because it tries to balance the load evenly between our code and lws_service(). If we call lws_service() just once in every our processing cycle it will stay way behind because lws_service() exits after every single packet or event.

Can you point some example code how to solve this our need without lws_sul?

**Comment by martlaak-gmail** [comment] 2020-09-08 08:59
> The actual problem is if we wake < 1ms early,
BTW. The patch suggestion I was proposing is making poll() to wake maybe little late (in case nothing is waking poll() during 1 ms), but never too early.

**Comment by lws-team** [comment] 2020-09-08 09:03
> Our code is that way because it tries to balance the load evenly between our code and lws_service().

Well, the obvious issue is lws wants to sleep its thread when nothing happening.  But your solution is keep waking it so it can "share", and then point at "high CPU load".  That's coming because you keep waking it, regardless of this 1ms thing.

If your code needs to run independently, the normal way to achieve that is put it in its own thread, that will "balance the load" using thread semantics.  You can find a minimal example showing one way to handle that here

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threads/protocol_lws_minimal.c

Depending on what you're doing there's also threadpool, which does most of the work to bind a threaded task to a wsi cleanly

https://libwebsockets.org/git/libwebsockets/tree/lib/misc/threadpool
https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/ws-server/minimal-ws-server-threadpool

**Comment by martlaak-gmail** [comment] 2020-09-08 09:15
But despite the fact you run the while+lws_service() loop in thread or with lws_sul event the CPU-based wait problem is there anyway -- every time next event is be less than 1 ms ahead (like housekeeping or whatever other lws event) then CPU goes high for that less than millisecond.

Maybe you should make it configurable, if user requires current CPU-based micro-ms-precision event timing or he better fancies CPU-friendly milli-ms-precision behavior?

In our case we could definitely choose the latter...

**Comment by orgads** [comment] 2020-09-21 13:24
We faced a similar but seemingly different problem. In our case, we pass 0 because we want only events that are already in the queue to be handled without any timeout, but the handling of 0 (or any positive number) is now translated to a timeout of 23 days. I see this was introduced in 498a4e2bd7 and refined in a97347a18e. Why is that? Should we call another API instead of lws_service?

**Comment by lws-team** [comment] 2020-09-21 13:29
The change of 0 to mean stay in the wait is to align lws default loop behaviour to be more like the behaviour with an event loop... you start the loop and don't come back until you stop the loop.

Trying to share a wait is messy, but you can try passing -1 to return immediately.  It's much better to use an event lib in your code and have lws join it using its event lib support.  You do not need to spin the cpu trying to share a loop then.

**Comment by orgads** [comment] 2020-09-21 18:52
Yes, I changed it to -1 and it solved the issue. Does it appear in the release notes?

**Comment by lws-team** [comment] 2020-09-21 19:02
> Does it appear in the release notes?

No.  It's not officially supported and will go away in future versions.

**Comment by lws-team** [comment] 2020-11-21 08:02
So to summarize. a few things are mixed together here

 - OP attempt to share event loop, the issue is reported in terms of impact on that implementation
 - orgads attempt to share event loop (unrelated and worked around)
 - intrinsic behaviour with ms-resolution poll wait and us-resolution intervals

There isn't a good way to share event loops outside of a common event library, in which case it is seamless.  Lws supports four of them which is more than any other project I heard of in order to simplify that.

ms-resolution poll wait is more of a head-scratcher, however modern protocols are moving to UDP where the app layer / lws is responsible to "be the tcp stack" and require sub-ms retry scheduling for throughput, which works as it is.

The actual cost of it in power / cpu is  ameliorated because:

 - few timers come ripe, the most common pattern by far is a timeout-type schedule, which is removed before becoming ripe on a network-triggered event.  It doesn't cause this behaviour then.
 - when timeout-type timers do fire, by definition it is after a long interval, so the density of it is very low
 - an idle system generally only has long-term timers and is not seeing this behaviour but staying asleep
 - the number of times around the event loop id mediated by the poll syscall time which is typically 150-200ms, it means we can only exit the event loop a maximum of 6 and average of 3 times for each case
 - if any other work is ongoing in the event loop during this, it is performed, so latency does not increase and the time is not wasted; if the loop already has events the time is spent doing those instead of entry-exit until the ripe time
- libuv at least (and probably the others) doesn't have this problem since it only exposes ms-resolution intervals and lws truncates the native us ones
- rtos does not have this problem since it exposes us-resolution intervals (via select) and gets all the benefit

So at the moment I think this is OK as it is, after more stuff is using UDP retries it may get revisited.

**Closed by lws-team** 2020-11-21 08:02 UTC
