### ISSUE TITLE
the newest version will parse the url path error 

### ISSUE THREAD

**Issue by sofu456** [warmcat/libwebsockets#2140] opened 2020-12-08 15:16 UTC
html request two files,and one url lost and request to /

**Comment by lws-team** [comment] 2020-12-08 15:25
So how can I reproduce this using the minimal examples?

**Comment by lws-team** [comment] 2020-12-10 03:27
I can't understand what I need to look at from the description of this, or even what we are talking about.

It's "requesting two files" "in HTML" but it says "parse the url path" wrongly... there's some log showing the right URL came to lws but we did something "wrong"?  What is the structure of the url?

It got replaced to / because it was redirected http -> https?  In later lws, the path is retained during this now if so.

Closing but happy to look at if if you can provide more info.

**Closed by lws-team** 2020-12-10 03:27 UTC

**Comment by sofu456** [comment] 2020-12-10 03:59
thank you for you help, maybe something i do not find, i upgrade the jsmpeg-vnc project and find this bug,now i guess maybe i make a mistake and should debug it more
