### ISSUE TITLE
libwebsockets in Windows crashes in lws_plat_service() function

### ISSUE THREAD

**Issue by haitetra** [warmcat/libwebsockets#343] opened 2015-11-13 00:54 UTC
Hello,

I have observed multiple crashes in lws_plat_service() function (lws-plat-win.c) when building an application on Windows linking statically with libwebsocket (v1.5-chrome47-firefox41). The problem is that when we call:

```
if (pfd->events & LWS_POLLOUT) {
  if (wsi_from_fd(context,pfd->fd)->sock_send_blocking) { ... }
```

the function wsi_from_fd() could returns NULL, and the above code crashes.

I put in a simple fix below and it no longer crashes:

```
if (pfd->events & LWS_POLLOUT) {
  // old code: if (wsi_from_fd(context,pfd->fd)->sock_send_blocking)
  lws = wsi_from_fd(context,pfd->fd);
  if (!lws || lws->sock_send_blocking)
```

Note that crash does not always happen. It happens in a special scenario as follows:
- Start the application
- Connect the network to VPN
- Disconnect the VPN (app is still running fine, socket is disconnected)
- Connect the VPN again
- After a short moment, app crashes and the stack trace points to the above function.

My question is that: is it expected that this function could return NULL? Or if that is a bad situation, what would be the right fix to clean up the memory and return?

Please advice.
Thanks,
Hai

**Comment by lws-team** [comment] 2015-11-13 02:23
I think it's wrong not dealing with NULL anyway, so I pushed a fix based on your snippet here.

However something else must also be wrong as you say to get to that situation.  It seems like the connection is closed or failed, the wsi is gone, but the old fd was left in the fd list, and so is subject to being serviced, exposing this problem.  However that is not really going wrong in this code but in close / fail handling somewhere else.

Do you have this fix from Oct 18?

http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/commit/?id=b5cf69fdb57c4025572cde1007e0ff16108d4f80

We could add code at the place patched to detect NULL to do the removal from the fd list.  But that is a distant second in desirability to fixing the root cause.

**Comment by lws-team** [comment] 2015-11-13 02:35
Sorry I had a stray typo in the patch (had to wait for Appveyor to build-test it) I amended it.

**Comment by haitetra** [comment] 2015-11-13 02:51
I do have this fix (http://git.libwebsockets.org/cgi-bin/cgit/libwebsockets/commit/?id=b5cf69fdb57c4025572cde1007e0ff16108d4f80) in the code, so I don't think it's the issue.

I agree with you that the long term fix would be to detect NULL and cleanup. With this fix, however, do you think we will end up with memory leaks/out-of-resource situation? (say in case the network is flaky, VPN goes up and down for multiple times)

Thanks for patching the fix. Could you please also fix it here (same function, just a bit below):

```
@@ -195,8 +197,10 @@ lws_plat_service(struct libwebsocket_context *context, int timeout_ms)

        pfd->revents = networkevents.lNetworkEvents;

-       if (pfd->revents & LWS_POLLOUT)
-               wsi_from_fd(context,pfd->fd)->sock_send_blocking = FALSE;
+       if (pfd->revents & LWS_POLLOUT) {
+               lws = wsi_from_fd(context,pfd->fd);
+               if (lws) lws->sock_send_blocking = FALSE;
+   }
```

**Comment by lws-team** [comment] 2015-11-13 03:47
Actually I was saying the opposite, detecting the NULL and fixing it up is not the long term solution, we need to find the root cause.

To do that make sure _DEBUG is defined so you can see lwsl_info and below, and capture the logs (with the logging set to 31 or so) around the sequence that provokes the problem.  That might give us a clue where to look.

I pushed a patch for this other instance as well thanks.

**Comment by haitetra** [comment] 2015-11-13 06:52
Ah, misunderstanding. Agree, it's better to find the right fix than getting away with the NULL check.

Let me turn on debug flag and see if I could reproduce the crash with more logs. Will get back once I find more info. Btw, how to set logging value to 31?

Thanks for your help.

**Comment by lws-team** [comment] 2015-11-13 07:22
Not sure what windows does but on everything else uses lws_set_log_level() and sets an emit callback.

**Comment by haitetra** [comment] 2015-11-13 07:35
:+1: trying it now. A bit complicated since in Windows I compiled libwebsocket() in debug mode (_DEBUG on), then in my app will statically link to it.

**Comment by haitetra** [comment] 2015-11-13 09:14
Found another crash (after reverting to the original code and run debug mode). Here is the log when it happened:
```
...
[11927428272:0916] INFO: insert_wsi_socket_into_fds: wsi=000000AEDFE198D0, sock=520, fds pos=0
[11927428278:0283] INFO: TIMEDOUT WAITING on 2
[11927428278:0283] DEBUG: close: just_kill_connection
[11927428278:0283] INFO: remove_wsi_socket_from_fds: wsi=000000AEDFE198D0, sock=520, fds pos=0
[11927428278:0283] DEBUG: Connection closed before server reply
[11927428278:0283] DEBUG: closing: shutdown ret 10057
[11927428278:0283] INFO: insert_wsi_socket_into_fds: wsi=000000AEDFE198D0, sock=516, fds pos=0
[11927428284:0752] INFO: TIMEDOUT WAITING on 2
[11927428284:0752] DEBUG: close: just_kill_connection
[11927428284:0752] INFO: remove_wsi_socket_from_fds: wsi=000000AEDFE198D0, sock=516, fds pos=0
[11927428284:0752] DEBUG: Connection closed before server reply
[11927428284:0752] DEBUG: closing: shutdown ret 10057
*[11927428284:0752] INFO: insert_wsi_socket_into_fds: wsi=000000AEDFE198D0, sock=344, fds pos=0*
*1447402048 - Client failed to connect to x.y.z:443 (this is my app's log)*
*[11927428298:9502] INFO: insert_wsi_socket_into_fds: wsi=000000AEDFE198D0, sock=176, fds pos=1*
==> crashed here
```

I have only one server (at the hypothetical address x.y.z), so only one connection should be made at a time. There seems to be a pattern, that lws opens a socket and closes the same socket.
- open 520, close 520
- open 516, close 516
- open 344, *app-log*, open 176

My app spits a log in the following condition:
```
wsi = libwebsocket_client_connect_extended(..);
if (!wsi) printlog(...);
```
Looks like we should have closed socket 344, before opening 176. Not sure if we could have more than one opened sockets. At the crash, the context looks as follows:
```
context
  -> fds_count = 2
  -> fds = { fd = 344, event = 11, revent = 0 }
  -> fd_hashtable (all entries empty, except these two)
    -> [16] => wsi = 0x000000AEDFE198D0 (sock = 176, sock_send_blocking = 0)
    -> [25] => wsi = 0x000000AEDFE198D0 (sock = 176, sock_send_blocking = 0)
    (these two entries have the same pointers)
```

According to this data, the function call wsi_from_fd(context,pfd->fd==344) will return NULL since LWS_FD_HASH(344)=25. This will lead to a crash if we call wsi_from_fd(context,pfd->fd)->sock_send_blocking.

The question that arises is that why both of these hash entries point to same pointer, and why there is no entries for fd=344, while fds->fd=344. I think 344 should have been closed and cleaned-up by now, before 176 is opened.

Also a mystery is why wsi returns NULL in the middle (when my app spits the log). It should have returned the same address, 000000AEDFE198D0.

Any ideas? If you know what to look for, I could get the data. I could reproduce this crash very consistently. Thanks.

**Comment by lws-team** [comment] 2015-11-13 23:37
Please try the patch I just pushed... it looks like it might be due to different opinion on what an invalid socket fd looks like between *nix and windows.

**Comment by haitetra** [comment] 2015-11-14 04:58
Thanks for helping. Unfortunately, this doesn't look like a good fix. My app crashes soon after starts (happens every time). It crashes here:

```
remove_wsi_socket_from_fds()
libwebsocket_close_and_free_session()
libwebsocket_client_connect_2()
libwebsocket_client_connect()
libwebsocket_client_connect_extended()
```
```
int
remove_wsi_socket_from_fds(struct libwebsocket_context *context,
                        struct libwebsocket *wsi)
{
...
   lws_plat_delete_socket_from_fds(context, wsi, m);

   /*
    * end guy's fds_lookup entry remains unchanged
    * (still same fd pointing to same wsi)
    */
   /* end guy's "position in fds table" changed */
   wsi_from_fd(context,context->fds[context->fds_count].fd)->
               position_in_fds_table = m;
```
Debug log:
```
[11927501774:3989] INFO:  LWS_MAX_EXTENSIONS_ACTIVE: 3
[11927501774:4009] NOTICE:  canonical_hostname = <xyz>
[11927501774:4019] NOTICE:  per-conn mem: 280 + 2140 headers + protocol rx buf
[11927501774:4058] DEBUG: Connect failed errno=10038
[11927501774:4077] DEBUG: close: just_kill_connection
[11927501774:4097] INFO: remove_wsi_socket_from_fds: wsi=0000009AB80182C0, sock=-1, fds pos=0
==> crash here 
```
Data dump:

![libwebsocket_crash_1_data](https://cloud.githubusercontent.com/assets/10442256/11162095/af7e5a1a-8a46-11e5-9671-7f1e06325ec5.PNG)

It crashes obviously because context->fds_count = -1.

**Comment by lws-team** [comment] 2015-11-14 05:15
I think it's a good fix for what it fixes.  But now that's fixed, we get new things happening.

None of this occurs on Linux though.  Which is a good clue it's probably more of the same problem.

**Comment by haitetra** [comment] 2015-11-14 05:23
I know it's not happening on Linux. I have the same app running on Linux, and it never crashed even with a fairly old version of libwebsocket (awesome job, btw :-) )

**Comment by lws-team** [comment] 2015-11-14 05:33
Thanks... I don't mean to minimize the problem by observing Linux is okay, but actually this code is part of the common, non-platform-specific code.  So it means the problem is related to platform-specifc defines or code somehow, which narrows it down.

I'll audit all the referenced to socket fds I can find first and apply the previous platform-specific macros on them.

**Comment by haitetra** [comment] 2015-11-14 05:52
Thanks. For now, I have to revert the code back to only checking for NULL, otherwise my app couldn't proceed (crash every time).

**Comment by lws-team** [comment] 2015-11-14 05:54
I pushed a patch that should solve the new problem.  To get a new new problem maybe...

**Comment by haitetra** [comment] 2015-11-14 05:59
super quick ! trying it now.

**Comment by haitetra** [comment] 2015-11-15 00:42
After cooking it for a day, I would say this problem got fixed !!! Thanks so much @lws-team I owe you a drink ! :-)

(shall I close this issue?, hopefully no more coming)

**Comment by lws-team** [comment] 2015-11-15 00:48
Great... yes I can close it then.  Thanks a lot for the logs and testing.

**Closed by lws-team** 2015-11-15 00:48 UTC
