### ISSUE TITLE
Delay/timeout when re-connecting

### ISSUE THREAD

**Issue by jeffreytai** [warmcat/libwebsockets#2583] opened 2022-03-03 04:47 UTC
I'm testing some functionality to:
- connect to an endpoint
- stream data
- stop
- connect again after a few seconds
- attempt to stream data

I'm seeing a ~20 second delay on the re-connection and attempt to stream data. The debug logs reveal that lws is setting timeouts for various reasons: `PENDING_TIMEOUT_HOLDING_AH`, `PENDING_TIMEOUT_SENT_CLIENT_HANDSHAKE` and `PENDING_TIMEOUT_AWAITING_SERVER_RESPONSE`. Although if I kill the program and immediately restart, it once again is able to connect and stream data immediately, leading me to believe there is some cleanup that I'm not performing correctly.

Since a dump of my class might not be very effective, this is a heavily stripped down (slight pseudocode) version of my websocket class
```
class Ws

constructor() {
  // create context
}

connect() {
  struct lws_client_connect_info i;
  ...
  lws_client_connect_via_info(&i);
}

stop() {
  // sets disconnect flag
}

callback(...) {
   // handles various reasons
   // if disconnect flag is set, return -1 to kill connection
}

struct lws_context* m_context;
struct lws* m_client_wsi;
```

Debug logs
```
// call connect()
[2022/03/02 23:01:29:6361] D: lws_vhost_bind_wsi: vh default: wsi none/none, count_bound_wsi 1
[2022/03/02 23:01:29:6361] D: _realloc: size 240: client ws struct
[2022/03/02 23:01:29:6361] D: lws_role_transition: 0x14e8480: wsistate 0x10000200, ops h1
[2022/03/02 23:01:29:6361] D: lws_ensure_user_space: 0x14e8480 protocol pss 0, user_space=(nil)
[2022/03/02 23:01:29:6361] D: _realloc: size 155: client stash
[2022/03/02 23:01:29:6361] D: _realloc: size 976: ah struct
[2022/03/02 23:01:29:6361] D: _realloc: size 4096: ah data
[2022/03/02 23:01:29:6361] D: __lws_set_timeout: 0x14e8480: 10 secs, reason 25
[2022/03/02 23:01:29:6361] D: lws_http_client_connect_via_info2: 0x14e8480 (stash 0x14dfc10)
[2022/03/02 23:01:29:6361] D: lws_client_connect_2_dnsreq: new conn on no pipeline flag
[2022/03/02 23:01:29:6361] D: _realloc: size 18: strdup
[2022/03/02 23:01:29:6361] D: lwsi_set_state(0x14e8480, 0x10000201)
[2022/03/02 23:01:29:6367] D: lws_client_connect_3_connect: result 0x14ab6c0 result->ai_next 0x14ad450
[2022/03/02 23:01:29:6367] D: lws_client_connect_3_connect: 0x14e8480: WAITING_CONNECT
[2022/03/02 23:01:29:6367] D: lwsi_set_state(0x14e8480, 0x10000202)
[2022/03/02 23:01:29:6367] D: __insert_wsi_socket_into_fds: 0x14e8480: tsi=0, sock=5, pos-in-fds=1
[2022/03/02 23:01:29:6367] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 1 -> 1
[2022/03/02 23:01:29:6367] D: __lws_set_timeout: 0x14e8480: 20 secs, reason 2
[2022/03/02 23:01:29:6367] D: lws_client_connect_3_connect: connect says errno: 115
[2022/03/02 23:01:29:6367] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 1 -> 5
[2022/03/02 23:01:29:6367] D: lws_client_connect_via_info: wsi 0x14e8480: adoption cb 19 to h1 handle-exchange-protocol
[2022/03/02 23:01:29:6548] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 5 -> 1
[2022/03/02 23:01:29:6548] D: lws_client_connect_3_connect: getsockopt check: conn OK errno 0
[2022/03/02 23:01:29:6548] D: lws_client_connect_3_connect: going into connect_4
[2022/03/02 23:01:29:6548] D: lwsi_set_state(0x14e8480, 0x10000012)
[2022/03/02 23:01:29:6548] D: __lws_set_timeout: 0x14e8480: 5 secs, reason 8
[2022/03/02 23:01:29:6548] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 1 -> 1
[2022/03/02 23:01:29:6549] D: lws_ssl_get_error: 0x7fd1d4000b60 -1 -> 2 (errno 11)
[2022/03/02 23:01:29:6549] D: lwsi_set_state(0x14e8480, 0x10000204)
[2022/03/02 23:01:29:6549] D: lws_client_create_tls: lws_ssl_client_connect1: 0
[2022/03/02 23:01:29:6722] D: lws_ssl_get_error: 0x7fd1d4000b60 -1 -> 2 (errno 11)
[2022/03/02 23:01:29:6722] D: lws_ssl_client_connect2: SSL_connect says -2
[2022/03/02 23:01:29:6722] D: lwsi_set_state(0x14e8480, 0x10000204)
[2022/03/02 23:01:29:6729] D: lws_ssl_get_error: 0x7fd1d4000b60 -1 -> 2 (errno 11)
[2022/03/02 23:01:29:6729] D: lws_ssl_client_connect2: SSL_connect says -2
[2022/03/02 23:01:29:6730] D: lwsi_set_state(0x14e8480, 0x10000204)
[2022/03/02 23:01:29:6888] D: lws_ssl_get_error: 0x7fd1d4000b60 1 -> 0 (errno 0)
[2022/03/02 23:01:29:6888] D: rops_alpn_negotiated_h1: client 1
[2022/03/02 23:01:29:6888] D: lws_ssl_client_connect2: SSL_connect says 0
[2022/03/02 23:01:29:6888] D: get_verify says 0
[2022/03/02 23:01:29:6889] D: lwsi_set_state(0x14e8480, 0x1000020b)
[2022/03/02 23:01:29:6890] D: __lws_set_timeout: 0x14e8480: 5 secs, reason 4
[2022/03/02 23:01:29:6890] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 1 -> 5
[2022/03/02 23:01:29:6890] D: lwsi_set_state(0x14e8480, 0x1000020b)
[2022/03/02 23:01:29:6890] D: __lws_set_timeout: 0x14e8480: 5 secs, reason 4
[2022/03/02 23:01:29:6890] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 5 -> 1
[2022/03/02 23:01:29:9876] D: 0x14e8480: SSL_read says 166
[2022/03/02 23:01:29:9876] D: lws_buflist_aware_read: wsi 0x14e8480: lws_client_socket_service: ssl_capable_read 166
[2022/03/02 23:01:29:9876] D: lws_client_socket_service: buflist-aware-read 0 166
[2022/03/02 23:01:29:9877] D: lws_client_interpret_server_handshake: no content length
[2022/03/02 23:01:29:9877] D: Selected protocol handle-exchange-protocol
[2022/03/02 23:01:29:9877] D: lws_ensure_user_space: 0x14e8480 protocol pss 0, user_space=(nil)
[2022/03/02 23:01:29:9877] D: lws_role_transition: 0x14e8480: wsistate 0x10000119, ops ws
[2022/03/02 23:01:29:9877] D: _realloc: size 4116: client frame buffer
[2022/03/02 23:01:29:9877] D: handshake OK for protocol handle-exchange-protocol

// LWS_CALLBACK_CLIENT_ESTABLISHED callback reached
[2022/03/02 23:01:29:9877] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 1 -> 5
[2022/03/02 23:01:29:9878] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 5 -> 1
[2022/03/02 23:01:29:9878] D: lws_handle_POLLOUT_event: 0x14e8480: non mux: wsistate 0x10000119, ops ws

// send message over websocket to subscribe 
[2022/03/02 23:01:32:6369] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 1 -> 5

// NOTE the ~20 second delay here
[2022/03/02 23:01:53:6137] D: _lws_change_pollfd: wsi 0x14e8480: fd 5 events 5 -> 1
[2022/03/02 23:01:53:6137] D: lws_handle_POLLOUT_event: 0x14e8480: non mux: wsistate 0x10000119, ops ws
```

is there any cleanup required when closing and re-opening a connection?

**Comment by lws-team** [comment] 2022-03-03 06:01
This seems to be somewhat outdated lws... but I doubt it's the problem.

Your pseudocode talks about a "disconnect flag" but the logs do not show any disconnection.

If you really want to drop a wsi, you can call `lws_wsi_close(wsi, LWS_TO_KILL_ASYNC);` on it safely, it will force an immediate timeout that will be handled next time around the event loop.

And... lws is predicated around a single threaded event loop.  Putting C++ semantics on top that, does not change anything about it being deliberately non-threadsafe,  If that sounds related, have a read through this

https://libwebsockets.org/git/libwebsockets/tree/READMEs/README.event-loops-intro.md

**Comment by jeffreytai** [comment] 2022-03-03 06:23
Thanks for the quick reply, for the sake of completeness:
> This seems to be somewhat outdated lws... but I doubt it's the problem.
That's correct, I'm currently on 4.1.6, not too outdated but perhaps I'm due for an upgrade

> Your pseudocode talks about a "disconnect flag" but the logs do not show any disconnection.
I hadn't previously included it since the close looked clean to me, attached are the debug logs from the same session but from right after closing the connection
```
[2022/03/02 23:01:26:7131] D: 0x14e8480: SSL_read says 376
[2022/03/02 23:01:26:7131] D: lws_read_h1: h1 path: wsi state 0x119
[2022/03/02 23:01:26:7131] D: lws_ws_handshake_client: hs client feels it has 376 in
[2022/03/02 23:01:26:7131] D: lws_ws_client_rx_sm: spilling as we have the whole frame
[2022/03/02 23:01:26:7131] D: lws_ws_client_rx_sm: starting disbursal of 372 deframed rx
[2022/03/02 23:01:26:7132] D: lws_ws_client_rx_sm: bulk ws rx: inp used 372, output 372
[2022/03/02 23:01:26:7132] D: __lws_close_free_wsi: real just_kill_connection: 0x14e8480 (sockfd 5)
[2022/03/02 23:01:26:7132] D: lwsi_set_state(0x14e8480, 0x10000020)
```

I'll be trying out `lws_wsi_close` and I appreciate you sharing the event loops link!

**Comment by lws-team** [comment] 2022-03-03 06:35
I thought the logs were showing me what happened from the initial connect, the disconnect and the reconnect... but they just show from the reconnect.

The wsi closing should clean everything up on lws side.

Are you possibly asking to write for the subscribe action from another thread?

**Comment by jeffreytai** [comment] 2022-03-03 06:50
> Are you possibly asking to write for the subscribe action from another thread?

i have my main process creating a thread that starts and runs the websocket class, but it doesn't ask to write from this thread. it does call into the websocket class to send a subscription message, but that gets buffered until the `LWS_CALLBACK_CLIENT_WRITEABLE` callback is received and then the message is sent. i only call `lws_callback_on_writable` once the connection is established (`LWS_CALLBACK_CLIENT_ESTABLISHED`)

more pseudocode
```
   static void* threadStart(void* arg)
  {
      ((feed::Ws*)arg)->start();
      return arg;
  }
  
  int main() {
   ws = Ws(...);

    pthread_create(&m_thread, NULL, &threadStart, &ws);

    ws.connect();

    // send msg
    std::string req = <some message to subscribe>
    ws.send(req);

    // wait some time
    sleep(1);
    ws.stop();

    // wait some time
    sleep(1);
    ws.connect();

    // wait som etime
    ws.send(<some subscription message>);

    while (true) { }
  }
```

and one section i was missing previously, was that the Ws class has a start function that just loops and services the lws
```
class Ws ...

start() {
  while (true) {
    while (m_client_wsi) {
      lws_service(m_context, 0);
    }
  }
}
```

**Comment by lws-team** [comment] 2022-03-03 07:45
Why don't we turn this around... I don't have any interest in debugging your class / trying to guess what the psuedocode really looks like.

If there's a problem in lws, you should be able to adapt an example to demonstrate it in C, send me the diff and I'll be happy to try to reproduce it if so (but please use v4.3-stable or main branches).

**Closed** 2022-03-03 21:42 UTC
