### ISSUE TITLE
WSS over HTTP/2 returns invalid RST_STREAM frame

### ISSUE THREAD

**Issue by mconca** [warmcat/libwebsockets#1752] opened 2019-11-04 20:46 UTC
This issue was first reported to Mozilla in [bug 1590299](https://bugzilla.mozilla.org/show_bug.cgi?id=1590299).

> The http2 session is closed because we receive invalid RST_STREAM frame:
> 00 00 04 03 00 00 00 00 00
> According to spec the stream id must not be 0. If it is, then it's a protocol error.

**Comment by lws-team** [comment] 2019-11-04 21:45
I pushed a patch on master and v3.2-stable that should solve the wrong sid on RST_STREAM when it's ws-over-h2 (only).  I'm not sure that's the root cause of the problem, since it's already decided to close the wsi at that point and the bugzilla bug is complaining the ws link is closing unexpectedly.

Also I opened a firefox bugzilla 9 months ago about ws-over-h2 behaviour I can still see from the lws testserver even with this patch, it may be related

https://bugzilla.mozilla.org/show_bug.cgi?id=1528850

**Comment by lws-team** [comment] 2019-11-04 21:47
Btw https://libwebsockets.org/testserver is updated to current master and should demonstrate the RST_STREAM fix.  It still passes all h2spec tests in CI as well.

**Closed** 2019-11-07 09:26 UTC
