### ISSUE TITLE
lws_reset_header_table called with NULL wsi->u.hdr.ah

### ISSUE THREAD

**Issue by rdeg** [warmcat/libwebsockets#416] opened 2016-02-08 13:42 UTC
Hi all,

I recently compiled the libwebsockets stuff for Windows (no SSL, no daemonization) and had the libwebsockets-test-server failed with an exception in lws_reset_header_table.
It appeared that lws_reset_header_table can be called more than often with a NULL wsi->u.hdr.ah, and that the code can't work when it is the case.

I fixed it this way, by simply testing the value of ah before using it:

`void
lws_reset_header_table(struct lws *wsi)
{
  /* init the ah to reflect no headers or data have appeared yet */
  if (/*wsi && */wsi->u.hdr.ah)	/* lws_reset_header_table can be called with ah = 0 */
  {
    memset(wsi->u.hdr.ah->frag_index, 0, sizeof(wsi->u.hdr.ah->frag_index));
    wsi->u.hdr.ah->nfrag = 0;
    wsi->u.hdr.ah->pos = 0;
   }
}
`

I use Chrome 48 on Windows 7 as the client.

I did not tried to understand how the function was called with such a context but fixing it allowed me to run the sample, including multiple instances of it.

HTH
Remi

**Comment by lws-team** [comment] 2016-02-09 01:30
I added it, but from studying the code when this was reported on the ml a couple of days ago, unfortunately something more radical needs doing to properly solve it.  It's illegal this gets called without a valid ah, the underlying problem is that we are forced to sit and deal with http1.1 pipelining without going back to the event loop atm but we want to give up the ah as quickly as possible.  That's broken since http service can always require the event loop yet the next header set may have already arrived.

It needs some larger rework to remove this conflicting restriction that http1.1 next header set may have gone into a read buffer whose lifetime is only the first service action.

**Comment by rdeg** [comment] 2016-02-09 10:56
Hi Andy,

Thanks for the workaround officialisation, and for the explanation of the issue.
I guess it will be painful (and dangerous) to fix this...

Bon courage.
Remi

**Comment by lws-team** [comment] 2016-02-09 11:31
I dunno, but I do know it can't be done casually... I have to find time to look at all the related code at once.

One nice way is put an rx buffer in the ah, return to the event loop is allowed how you like and you can't detach the ah until you emptied it.  But I need to check it's workable under all conditions.

**Comment by lws-team** [comment] 2016-02-15 07:15
The ah holding the rx buffer seems to have worked out well and is pushed.

https://github.com/warmcat/libwebsockets/commit/2c218e705f6c77044d20ba276e98c0052d93d019

It can pass normal test server / client / Chrome operations, attack.sh and Autobahn (although that is testing client).

But I could only test it on Linux, I ported the platform-specific changes to windows platform code, but I can't check it.

**Comment by rdeg** [comment] 2016-02-15 08:55
Hi Andy,
I checked your new code under Windows 7 and I am sorry to say that it still fails in lws_header_table_reset, on the first assert().
Here is wsi content and the call stack (I added a 'if (!ah)' line before the assert() to put a breakpoint on it, thus it starts on line 70 of parsers.c, instead of line 69):

![wsi](https://cloud.githubusercontent.com/assets/2228222/13043651/b5699c9c-d3c9-11e5-9638-f4fe9a016af1.png)

![stack](https://cloud.githubusercontent.com/assets/2228222/13043652/b569c834-d3c9-11e5-8d66-1dfe6c849e8e.png)

Tell me if you feel I can help.
Remi

**Comment by lws-team** [comment] 2016-02-15 08:59
Thanks... actually acting the same is preferable to completely broken ^^  It just means there is some other path to understand.  Can you capture what is being sent on the network?  I added a pipelined http/1.1 test to attack.sh using wget to fetch 8 x test.html, he can pass OK.  Whatever it's doing it'd be good to be able to reproduce it.

**Comment by rdeg** [comment] 2016-02-15 09:10
Andy, I am not equipped to run .sh and wget, but I can see what I can do with Wireshark.

What I can say is that it fails with the test-server on the very first load of the test.html page, and this for each instance of localhost:7681 I try to launch under Chrome.

Once it has broken on the assert, I can resume the call to "wsi->hdr_parsing_completed = 0;" and it never breaks again for this instance, including when I ask to load leaf.jpg.

Gonna try to get some trace...

**Comment by lws-team** [comment] 2016-02-15 09:13
Thanks.  I just meant it will be good to add whatever this scenario is to the testing script.

On Linux, it doesn't get this failure.  So I think maybe your browser / OS does something in a different order on the wire that provokes it.  I can try reproduce it if I see whatever it is.

**Comment by rdeg** [comment] 2016-02-15 10:37
I put some extra trace in test-server:

int debug_level = 0x5F;	// RDG: LLL_HEADER, , DEBUG, ERR, INFO, NOTICE, WARN

I launch test-server first then refresh the test.html tab in Chrome and I produce this trace:

[trace1.txt](https://github.com/warmcat/libwebsockets/files/130488/trace1.txt)

If you have any idea of what's going on, i'm yours ;-)

**Comment by rdeg** [comment] 2016-02-15 10:53
With LLL_PARSER too:

[trace2.txt](https://github.com/warmcat/libwebsockets/files/130508/trace2.txt)

**Comment by lws-team** [comment] 2016-02-15 11:06
Does this help?

https://github.com/warmcat/libwebsockets/commit/c9259876d2e1f060640d6273babf62eda8bf93d2

**Comment by rdeg** [comment] 2016-02-15 11:16
Oh yes: is looks like it does :-)

Thanks for your nice work.

**Comment by lws-team** [comment] 2016-02-15 11:17
Super... then I'll close this, reopen or make a new issue if more problems are coming.

**Closed by lws-team** 2016-02-15 11:17 UTC
