### ISSUE TITLE
lws_callback_on_writable in concurrent environment

### ISSUE THREAD

**Issue by sorrowhill** [warmcat/libwebsockets#1064] opened 2017-10-23 06:02 UTC
Hi,

I'm facing the issue that writable function doesn't bump up `LWSSTATS_C_WRITEABLE_CB_REQ` in specific situation, here is the detail

1. when `LWS_CALLBACK_CLIENT_ESTABLISHED` is called on lws thread, it fires a signal to another thread.

2. when it receives the signal, it calls `lws_callback_on_writable` immediately.

3. `lws_callback_on_writable` is invoked, even before lws thread returned 0 in `LWS_CALLBACK_CLIENT_ESTABLISHED` callback.

4. sometimes `lws_callback_on_writable` is ignored if there are more threads(~60 threads),  here is the stats log right after `lws_callback_on_writable` 

```
[16:33:04.795449 14897] lws_callback_on_writable(1) / lws_stats_get(LWSSTATS_C_WRITEABLE_CB_REQ) (69)
[16:33:04.795449 14898] lws_callback_on_writable(1) / lws_stats_get(LWSSTATS_C_WRITEABLE_CB_REQ) (69)
```
static dumps are as follows:

```
[2017/10/20 16:33:48:6821] NOTICE: LWS internal statistics dump ----->
[2017/10/20 16:33:48:6821] NOTICE: LWSSTATS_C_CONNECTIONS:                           64
[2017/10/20 16:33:48:6821] NOTICE: LWSSTATS_C_API_CLOSE:                            126
[2017/10/20 16:33:48:6821] NOTICE: LWSSTATS_C_API_READ:                            8510
[2017/10/20 16:33:48:6821] NOTICE: LWSSTATS_C_API_LWS_WRITE:                        254
[2017/10/20 16:33:48:6821] NOTICE: LWSSTATS_C_API_WRITE:                            254
[2017/10/20 16:33:48:6821] NOTICE: LWSSTATS_C_WRITE_PARTIALS:                         0
[2017/10/20 16:33:48:6821] NOTICE: LWSSTATS_C_WRITEABLE_CB_REQ:                     253
[2017/10/20 16:33:48:6821] NOTICE: LWSSTATS_C_WRITEABLE_CB_EFF_REQ:                 253
[2017/10/20 16:33:48:6821] NOTICE: LWSSTATS_C_WRITEABLE_CB:                         253
```

so you can find that `LWSSTATS_C_API_LWS_WRITE` is 264 but `LWSSTATS_C_WRITEABLE_CB_REQ` is 253, i checked return value of  `lws_callback_on_writable` but it was all `1`

also tried to set MAX_SMP to 1, this also happened on Debug build. 

Actually, I had already handled this issue throughout queuing the callback and call them all on uv_loop. but performance is so bad :( 

Can you give me some advice to resolve this? i searched the code and tried to fix it but i don't want any surprises in production. so i'm asking your opinions..

thanks.

**Comment by lws-team** [comment] 2017-10-23 06:17
Can you maybe cut your code down to some example that shows the problem?

Serializing events should not be slow with libuv.  Do you have any clue where the time went, eg profiler?

**Comment by sorrowhill** [comment] 2017-10-23 06:54
here is the code, it runs on lws thread.

```
int WebSocketService::LWSCallbackGateway(
    lws *lws_socket, lws_callback_reasons reason,
    void *user, void *in, size_t len) {
  
  boost::unordered_map< lws*, WebSocket* >::const_iterator it = clients_.find(lws_socket);
  if (it == clients_.end()) {
    return kStatusOK;
  }
  WebSocket *websocket = it->second;
  ...
  switch (reason) {
    case LWS_CALLBACK_CLIENT_ESTABLISHED: {
          websocket->OnConnect(); // callback function
          //
          // what happened if lws_callback_on_writable is executed 
          // completely in here, on different thread?
          // some requests are ignored in my case but not confirmed...
          //
          return 0;
    }
    ...
 }
}
```

and this is the code that runs on different thread

```
// this invoked on lws thread
void OnConnected(const Ptr<WebSocket> &web_socket,
                 const boost::system::error_code &ec,
                 std::shared_ptr<boost::barrier> barrier) {
  barrier->wait(); // it fires to run lws_callback_on_writable
}

..
// this invoked on different thread
std::shared_ptr<boost::barrier> connection_barrier(new boost::barrier(2));

std::shared_ptr<WebSocketClient> client = WebSocketClient::Create(
    bind(OnConnected, _1, _2, connection_barrier),
    OnDisconnected,
    OnSend,
    OnReceived);

client->Connect("127.0.0.1/", 7682);

connection_barrier->wait();

// Once OnConnected() called, below code will execute immediately
// this thread is not same thread, which is websocket->OnConnect(); in above code snippet

client->Send(payload); // call lws_callback_on_writable

```

It it safe to call `lws_callback_on_writable` on OnConnected() but not safe on different thread.
and lws_stats_atomic_bump function () locks and bump up and unlocks but sometimes it doesn't count the `LWSSTATS_C_WRITEABLE_CB_REQ`


And I'm serializing the events into uv_loop, like this
```
uv_timer_init(&loop_, &timer_outer_);
uv_timer_start(&timer_outer_, OnTimerExpired, 0, 100);

lws_uv_initloop(lws_context_, &loop_, 0);
lws_libuv_run(lws_context_, 0);
```

```
void OnTimerExpired(uv_timer_t *t) {
  boost::mutex::scoped_lock send_lock(send_mutex_);
  while(!send_queue_.empty()) {
    lws *socket = send_queue_.front();
    lws_callback_on_writable(socket);
    send_queue_.pop();
  }
}

void OnSendFrame(const shared_ptr<WebSocket> &web_socket, const LWSPayload &payload) {
  ...
  boost::mutex::scoped_lock send_lock(send_mutex_);
  send_queue_.push(web_socket->lws_socket_);
}
```


there is no profile log for that, but you can assume that handling on `OnTimerExpired` is more slow because it handles all writable callbacks every 100ms but not immediately(i can't find any better solution for now).

**Comment by lws-team** [comment] 2017-10-23 06:58
You can't really complain "libuv" is slow if your strategy is poll things every 100ms.  Your strategy is slow.

Why don't you back up a bit and just explain what you are trying to do... not the problem or the symptom... what are these 60 connections you mentioned trying to do?

**Comment by sorrowhill** [comment] 2017-10-23 07:13
I agree with that. but there is no other way to call `lws_callback_on_writable` safely for now.

60 connections are just for unit-test. but it can happen in real environment. even more connections can.

In normally, it runs as just server but often my application has to connect to another websocket server. so both client and server feature are needed in my application.

Anyway, there is no performance issue for now because websocket implementation is not designed for performance. I just don't know why few `lws_callback_on_writable` callbacks are ignored in multi-threaded environment and want to know why. so i can improve my code later :)

**Comment by lws-team** [comment] 2017-10-23 08:17
>  Why don't you back up a bit and just explain what you are trying to do... not the problem or the symptom... what are these 60 connections you mentioned trying to do?

I still invite you to answer this so I can try to help you.

**Comment by sorrowhill** [comment] 2017-10-23 08:36
okay. i'm implementing libwebsockets into the application that runs on multi-threaded environment. perhaps i said before..so these features(connect, disconnect, send or receive packet) must runs concurrently.
 
Here's the issue. libwebsockets should run on singlethreaded , and i want to run on multi-threaded. that's why i'm using `lws_callback_on_writable` on different thread.

`lws_client_connect_via_info` has same issue but as you told me before in another issue ticket, i had fixed the issue throughout queuing and handling on uv_loop.

but officially `lws_callback_on_writable` can be invoked on other thread so i implemented it to call it on spawned session thread.

so most issues(include before) were implementing libwebsockets into multi-threaded environment. serializing is the only way to solve it, but i found that there is no APIs to handle that because it's not libwebsockets's role.

**Comment by lws-team** [comment] 2017-10-23 08:44
Okay... what I am asking is even more basic, this is a server, and those > 60 connections you might have are incoming client connections?  Or we are making >60 outgoing connections to other servers?

When the connections are successful, what does it look like?  They are websocket connections?  What happens when the connection is established?  How often does the peer send data?  How much data?

"Concurrent" can mean either truly simultaneous, like happening on different cores at the same time, or just "sequential but quickly enough".  I guess you do not need real concurrency, just "sequential quickly enough", because on a real network, you cannot control anything that tightly you can tell if you are being serviced by SMP or just "quickly enough".  But "quickly enough for what"?  That is why I am trying to get an idea of what the connections are "doing".  I don't need to know any secrets about why they do it.

**Comment by sorrowhill** [comment] 2017-10-23 23:56
let me explain it..60 client will connected at once, even more, as i said before. it's incoming client connection. i don't know number of connections exactly, because it will be used as front-end server.

meanwhile, it also has to connect to back-end server via web socket implementation. so it has both incoming, outgoing connections. but less than 10 connections will be used for outgoing.

I agree with that "concurrent" is not real thing, in this case. it will be run on single-thread regardless of it's design until i use more sockets. (performance it not the problem for now so I'm keeping this design).

Back to the basic question, it's good to use `uv_loop` every 100ms to handle the requests. but i just want to know if there is more better way to handle it(so i tried to use `lws_callback_on_writable` on different thread).

**Comment by lws-team** [comment] 2017-10-24 00:04
OK... with the default poll() backend we have to run a "service loop" to keep calling `poll()` to wait until something happened.  But libuv approach is different, once you start the loop he deals with the event loop, and lws just becomes the target of async callbacks from libuv.  lws doesn't stop his loop until lws is exiting, in fact lws supports piggybacking on a "foreign" libuv event loop object that lws does not own but shares with other code, it doesn't even try to stop that loop then.

So we don't "enter a service loop" any more, we just get a callback from libuv telling us something we wanted to know when there was POLLIN now has POLLIN... we respond by reading it.  Same with POLLOUT, we inform libuv some socket we are interested to hear if we can write on him, he calls us back from "libuv-land" when we can write on him.  It's "event triggered" from network events.

There's no "100ms" heartbeat or something in there, if an event happens on a socket we get the callback in lws and call the normal lws interface for that, callback user code there was RX or let him have a WRITEABLE callback.  So I don't understand

> it's good to use uv_loop every 100ms to handle the requests

that's not how the libuv stuff works.  Did I miss your point?

**Comment by sorrowhill** [comment] 2017-10-24 00:34
I know that it's little bit tricky.. the loop isn't for the event on socket. it is just a loop for calling `lws_client_connect_via_info` and `lws_callback_on_writable` on lws thread.

Well my point is...sending packet always happen on different thread regardless of the event while in connected status. so i tried to use `lws_callback_on_writable` on different thread. 

As i said before, the application also has to connect to back-end server at runtime. but `lws_client_connect_via_info` is not allowed on different thread(that's why i'm using the loop).

**Comment by lws-team** [comment] 2017-10-24 00:55
> I know that it's little bit tricky.. the loop isn't for the event on socket. it is just a loop for calling lws_client_connect_via_info and lws_callback_on_writable on lws thread.

... I am not sure what that would look like, but it doesn't sound good.  libuv itself is singlethreaded without internal locking.  If you have a second, temporary loop in another thread I dunno what will happen but nothing good.

> Well my point is...sending packet always happen on different thread regardless of the event while in connected status

Well, the "call from another thread" stuff is just for lws_callback_on_writable() and just for poll() backend.  What action or locking is needed inside the event libraries is opaque to lws... with poll() we know what action it takes, set a bit in a pollfd.

The way to communicate events between the threads generally is to cause an event on something in the lws event loop... for example a pipe.  Your other thread sends a character down the "other side" of the pipe when it wants attention, and on the lws side it notices it and does any callback_on_writable() stuff it sees is needed there, using your own locking to make it safe to access things against the other thread.  That completely removes any need for lws_ apis on the other thread.

This doesn't exist atm in lws but it could be added... do we agree this would solve your problem?

**Comment by sorrowhill** [comment] 2017-10-24 01:06
that loop is invoked in lws thread. the loop is initialized like this:
```
uv_timer_init(&loop_, &timer_outer_);
uv_timer_start(&timer_outer_, OnTimerExpired, 0, 100);

lws_uv_initloop(lws_context_, &loop_, 0);
lws_libuv_run(lws_context_, 0);
```
anyway, thanks for the information that i was looking for :+1:

**Comment by lws-team** [comment] 2017-10-24 01:33
Well, I am going to implement what was discussed above and will leave this open to track it.

**Comment by sorrowhill** [comment] 2017-10-24 01:38
Sounds good. please let me know if you need any help :)

**Comment by lws-team** [comment] 2017-10-24 01:42
If you're on Linux, the guts of it (the pipe) already exist in `LWS_VISIBLE LWS_EXTERN void
lws_cancel_service_pt(struct lws *wsi);`... it needs confirming it works on libuv and a new callback adding.

**Comment by lws-team** [comment] 2017-10-24 06:02
Please try current master.

You can call `lws_cancel_service(context)` from the other threads; you could always do this with the poll() event loop but now it also works on the other event loops like libuv.

It will now make lws generate a new callback `LWS_CALLBACK_EVENT_WAIT_CANCELLED` in the normal lws service thread as soon as possible; immediately if there was nothing else going on.  In there, you can look at the other thread's situation, using your own locking to protect that against the other thread changing it, and call any lws_ apis you could normally call.

I confirmed it works in the poll() test server by firing SIGUSR1 at it which calls the cancel api, and by adding test code to libwebsockets-test-server-libuv to call the api every 2s, and print a log when the callback is coming.

**Comment by lws-team** [comment] 2017-10-24 10:36
Welp, I believe this is fixed, so closing.

**Closed by lws-team** 2017-10-24 10:36 UTC

**Comment by sorrowhill** [comment] 2017-10-24 12:18
thanks for the patch. sorry i was busy. i'll let you know later :)
