### ISSUE TITLE
Does libwebsockets support Windows x64?

### ISSUE THREAD

**Issue by tom-seddon** [warmcat/libwebsockets#673] opened 2016-11-15 22:34 UTC
(commit 5da54c0761692e918034ed3e5cb3045c690becbc)

I'm getting a lot of warnings when building on Windows: conversion between [pointer/long](https://github.com/warmcat/libwebsockets/blob/master/lib/context.c#L415), [lws_sockfd_type/int](https://github.com/warmcat/libwebsockets/blob/master/lib/server.c#L134), [size_t/int](https://github.com/warmcat/libwebsockets/blob/master/lib/server.c#L222) - plus a few other types of warning here and there. Does libwebsockets support 64-bit Windows?

Thanks,

--Tom

Repro steps:

0. Run `VS2015 x64 Native Tools Command Prompt` from start menu
1. change to random folder, e.g., `c:\temp`, or whatever
2. `git clone https://github.com/warmcat/libwebsockets`
3. `md libwebsockets\.build`
4. `cd libwebsockets\.build`
5. `cmake -G "NMake Makefiles" ..`
6. `nmake`

Observe warnings.

**Comment by lws-team** [comment] 2016-11-16 01:14
Lws was designed and built on 64-bit Linux, from the very start.  So in terms of generic 32-bit-isms, there should be none at all.

I build-test it on Windows only with Appveyor.

https://ci.appveyor.com/project/lws-team/libwebsockets

I don't have windows and haven't used it for getting on for 15 years.  All of the windows support is contributed.

About the warnings you linked to:

 - At least for gcc, long is defined to be big enough to carry any pointer, so that code has no problems.  If windows needs something else, what is it?

 - Yes, that internal api should have used lws_sockfd_type instead of int... I pushed a patch

 - unless server_name[] is going to exceed 4GB (on the stack...), the warning of putting sizeof into an int is excessive.  I like compiler warnings, but this kind of "throw a cast on it to shut the compiler up" is actually another way to create bugs through "cast blindness".

If you want to send a patch cleaning these warnings it will probably be accepted.  Barring platform specific things like the minimum int size to carry a pointer though, these are probably not indicating issues with it being 64-bit clean, because most people are using it on 64-bit OSes for many years.

**Comment by tom-seddon** [comment] 2016-11-16 03:12
OK - thanks for the clarification - I'll have a go at fixing them up tomorrow. There's enough of them that it did give me pause, but not so many that it looks impractical. 

What I'll probably do, if this sounds sensible to you:

* `long` vs pointers - 64-bit Windows is LLP64, so longs are 32 bits. I usually use the C99 types `intptr_t` or `uintptr_t`, which are explicitly pointer-sized; though it looks like libwebsockets might be C89/C90, in which case `size_t` or `ptrdiff_t` could be a better bet

* `lws_sockfd_type` vs `int` - I'll fix up any more similarly if I see them

* `size_t` vs `int` - no specific plan for these - will have a quick look at each one, and change the code if it looks like it actually needs it

Thanks,

--Tom

**Comment by lws-team** [comment] 2016-11-16 04:14
Sounds good...

It might be worth making an `lws_intptr_t` typedef in libwebsockets.h, or maybe private-libwebsockets.h if it doesn't leak out of the internals anywhere.

lws builds on a lot of different platforms... ironically one of the main forces reducing it to the lowest common denominator C was the microsoft compiler.  You can't always bank on later stuff like native intptr_t being around in the toolchain.  size_t should be a good bet though.

**Comment by lws-team** [comment] 2016-11-23 12:38
I'll still be happy to take a patch, but since this is stuck for a week I will close it.

**Closed by lws-team** 2016-11-23 12:38 UTC

**Comment by tom-seddon** [comment] 2016-11-23 15:58
Crap, sorry about forgetting to respond to this :( - it's a long story, but I ended up using websocketspp, for unrelated reasons.

Thanks,

--Tom
