### ISSUE TITLE
Some suggestions for the documents

### ISSUE THREAD

**Issue by litterbear** [warmcat/libwebsockets#544] opened 2016-05-30 07:53 UTC
I found there are two same functions in https://libwebsockets.org/libwebsockets-api-doc.html
```
lws_cancel_service - Cancel servicing of pending websocket activity

void lws_cancel_service (struct lws_context * context)
Arguments
```
Is this a bug? 

And I think the documents is organized  hard for user to read.  
I think making  a classification for the apis will make it easier for users and make libwebsockets more popular. 

Thanks  :)

**Comment by JoakimSoderberg** [comment] 2016-05-30 09:56
@lws-team Maybe considering to moving to https://readthedocs.org/ would be a good idea...

It gives you a nice page that enables showing multiple documentation versions and so on.

Here is a nice C project that uses it:
https://jansson.readthedocs.io/en/2.7/

Code (uses reStructuredText as markup language):
https://github.com/akheron/jansson/tree/master/doc

You can even browse it directly on github, however github does not support some of the extensions reStructuredText uses:
https://github.com/akheron/jansson/blob/master/doc/apiref.rst

It allows generating HTML, PDF and man page. Both building it locally, and automatically updating a hosted version via the readthedocs web page.

Example of where the documentation is built:
https://github.com/akheron/jansson/blob/master/release.sh#L58-L60

---

If you instead prefer using Markdown as the markup language (fully supported on github), this is also possible.

From one of my projects:
http://cargo.readthedocs.io/en/latest/
https://github.com/JoakimSoderberg/cargo/tree/master/docs

Which uses: http://www.mkdocs.org/ ... instead of Sphinx

**Comment by lws-team** [comment] 2016-05-30 10:20
@joakimSoderberg managing doc variations per branch is not really the problem; when I push to a branch a script here updates the correct per-branch version on https://libwebsockets.org.

The docs are autogenerated already so keeping them in sync with the code is under control as well.  Since they come out as html, hosting them isn't the problem either they can just go on libwebsockets.org.

The problem (which I can see...) seems to be the autogenerated docs are unsorted and without and real categorization.  Probably the root cause is that I borrowed the script to generate them from the kernel....

Doxygen http://www.doxygen.org seems to have become the primary way of doing this, it's FOSS and can be run locally without dependency on third-party websites.  It seems to be able to solve the grouping / categorization problem

https://www.stack.nl/~dimitri/doxygen/manual/grouping.html

**Comment by JoakimSoderberg** [comment] 2016-05-30 11:35
Yes, the tools mentioned above all run locally as well... and the docs looks nice :) you have 100% control of where stuff is placed. But not auto-generated from headers unfortunately.

doxygen is not my favorite tool, but  it's the only one for C/C++ that generates the docs somewhat nicely from the source code. So yea that is probably a good option for this (I had forgotten the docs where in libwebsockets.h)

Not to be rude, but when it comes to design/usability and kernel developers that is not their strong side from my experience :) ... (I mean non-code related design of course).

**Comment by lws-team** [comment] 2016-05-30 11:44
No I agree... I wanted to start putting docs in without stopping what I was doing, and I was familiar working with that from the kernel.  It's not any affirmative choice more than that.  (Let's not forget though git came out of kernel devs)

I'll start fiddling with it in the next days.  It looks like it can directly leverage what's already there just add some kind of classifications to give it some structure and grouping.

**Comment by JoakimSoderberg** [comment] 2016-05-30 12:07
ok cool... Yea I understand where you were coming from :)

Yes I know git came from there, awesome. But hence mentioning the "bad design" part does not include code design ;)

**Comment by litterbear** [comment] 2016-05-31 13:25
And some useful functions can't be found in the documents.
Such as `lws_get_context` (With this function,  I can access context in the callback function now. Otherwise I must declare context as a global variable.)

**Comment by lws-team** [comment] 2016-05-31 13:29
If you could send a patch, it'd help.

**Comment by litterbear** [comment] 2016-05-31 13:52
#548
Of course, documents updated.

**Comment by lws-team** [comment] 2016-06-20 09:31
I started in on this today and will update master as I go.  The only way it seems to be happy is migrating all the doc comments into libwebsockets.h, but since that seems good anyway I will go along that road.

The comment format it likes is slightly different so they all need adapting, and libwebsockets.h needs a giant refactor after that is done to reflect the grouping (it anyway has some outdated comments to also good to revisit the whole thing).

It makes sense to have the api docs generated before they are pushed and live in the tree (it's just doxygen libwebsockets.dox to regenerate), so I removed the old script and related cmake business.

https://libwebsockets.org/lws-api-doc-master/html/index.html

**Comment by lws-team** [comment] 2016-06-22 02:05
It's mostly in shape now.

https://libwebsockets.org/lws-api-doc-master/html/index.html

**Comment by lws-team** [comment] 2016-06-23 01:01
I added the existing README.x.md and completed bringing the functions into categories, there's a tree view on the left.

The remaining things are

 - github markup != doxygen markup, it doesn't understand three backticks but that's basically cosmetic.

 - a handful of functions don't have a writeup, these are related to libev / uv integration, these can be used by cut and pasting from the samples or lwsws

 - search didn't work so I disabled it.

Anyway this is a million miles better than what we had, even for people just looking through libwebsockets.h it also reflects the groupings now.

**Closed by lws-team** 2016-06-23 01:01 UTC

**Comment by lws-team** [comment] 2016-06-23 02:22
The markdown for code block thing is a bit more subtle than just being incompatible, doxygen will recognize and snip the three backticks so long as the code block content is indented by whatever you have set "one tab" to in doxygen config.  I fixed them all up so they should still work in github and the doxygen docs.
