### ISSUE TITLE
Client sending large message issue using MbedTLS

### ISSUE THREAD

**Issue by reluWeb** [warmcat/libwebsockets#1084] opened 2017-11-02 15:38 UTC
I recently upgraded libwebsockets to 2.4.0 to use mbedtls for OpenWRT.  I call lws_write only on LWS_CALLBACK_CLIENT_WRITEABLE and the same code worked (and still works ) if I use OpenSSL instead of MBedTLS. 
When the message is large (10~30K) the server side library (Node JS ) gives the following error : **1002 'Unsupported usage of rsv bits without negotiated extension.'** and closes the connection.
My guess is it has somethings to do with truncated messages because this happens only on some devices ( RPi2, RPi3,  TL-MR3420 ).

**Comment by lws-team** [comment] 2017-11-02 16:17
"The message is large"... what does that mean in terms of how much you try to write at once?  Ie what is the  rx_buffer_size set to in your protocol struct?  If it's large, try reducing it.

Is the permessage-deflate extension active?

Complaints about rsv bits means data inside the tls tunnel has lost coherency, while the framing for the tunnel is intact.  That's obviously not normal...

**Comment by reluWeb** [comment] 2017-11-02 16:34
rx_buffer_size is set to 4096.
I get this error when I send more at once than 4k.
permessage-deflate extension is active.

**Comment by lws-team** [comment] 2017-11-02 16:37
To reduce the number of things in play, can you see if the problem is still coming if you temporarily set info.extensions to NULL to disable pmd?

**Comment by reluWeb** [comment] 2017-11-02 17:17
Will do and come back monday with an answear

**Comment by lws-team** [comment] 2017-11-06 07:16
FWIW over the weekend, on master I added a `-e` for echo switch to the test client.  It spams the mirror protocol part of the test server with 1024 x (3 x 4K) blocks filled with a PRNG sequence, waits for them to be returned and and then exits.  It works OK (on master at least).

To reproduce build master and then in one terminal

```
 $ libwebsockets-test-server
```

and the other

```
 $ libwebsockets-test-client 127.0.0.1 -e
```

he should tell something like this

```
[2017/11/06 15:12:32:7511] NOTICE: libwebsockets test client - license LGPL2.1+SLE
[2017/11/06 15:12:32:7512] NOTICE: (C) Copyright 2010-2017 Andy Green <andy@warmcat.com>
[2017/11/06 15:12:32:7512] NOTICE:  SSL disabled
[2017/11/06 15:12:32:7512] NOTICE:  Cert must validate correctly (use -s to allow selfsigned)
[2017/11/06 15:12:32:7512] NOTICE:  Requiring peer cert hostname matches
[2017/11/06 15:12:32:7513] NOTICE: Creating Vhost 'default' port -1, 3 protocols, IPv6 off
[2017/11/06 15:12:32:7514] NOTICE: created client ssl context for default
[2017/11/06 15:12:32:7555] NOTICE: using  mode (ws)
[2017/11/06 15:12:32:7555] NOTICE: mirror: connecting
[2017/11/06 15:12:32:7555] NOTICE: lws_client_connect_2: 0x8e0c60: address 127.0.0.1
[2017/11/06 15:12:32:7557] NOTICE: lws_client_connect_2: 0x8e0c60: address 127.0.0.1
[2017/11/06 15:12:32:7559] NOTICE: mirror: LWS_CALLBACK_CLIENT_ESTABLISHED
[2017/11/06 15:12:32:0000] NOTICE: rxb 303, rx_count 8192
[2017/11/06 15:12:33:5295] NOTICE: send completed: 1024 x 12288
[2017/11/06 15:12:33:5321] NOTICE: Everything received: errs 0
[2017/11/06 15:12:33:5322] ERR: Exiting
[2017/11/06 15:12:33:5322] NOTICE: mirror: LWS_CALLBACK_CLOSED mirror_lifetime=0, rxb 1024, rx_count 0
```

**Comment by reluWeb** [comment] 2017-11-06 13:44
1. I disabled the extension - I still get the same error on server side
2. Ran the tests:
- same host
`[2017/11/06 14:05:45:7372] NOTICE: libwebsockets test client - license LGPL2.1+SLE
[2017/11/06 14:05:45:7373] NOTICE: (C) Copyright 2010-2017 Andy Green <andy@warmcat.com>
[2017/11/06 14:05:45:7373] NOTICE:  SSL disabled
[2017/11/06 14:05:45:7373] NOTICE:  Cert must validate correctly (use -s to allow selfsigned)
[2017/11/06 14:05:45:7373] NOTICE:  Requiring peer cert hostname matches
[2017/11/06 14:05:45:7373] NOTICE: libuv support not compiled in
[2017/11/06 14:05:45:7386] NOTICE: Creating Vhost 'default' port -1, 3 protocols, IPv6 off
[2017/11/06 14:05:45:7387] NOTICE: created client ssl context for default
[2017/11/06 14:05:45:7387] NOTICE: using  mode (ws)
[2017/11/06 14:05:45:7387] NOTICE: mirror: connecting
[2017/11/06 14:05:45:7387] NOTICE: lws_client_connect_2: 0x21d6be0: address 127.0.0.1
[2017/11/06 14:05:45:7388] NOTICE: lws_client_connect_2: 0x21d6be0: address 127.0.0.1
[2017/11/06 14:05:45:7390] NOTICE: mirror: LWS_CALLBACK_CLIENT_ESTABLISHED
[2017/11/06 14:05:45:0001] NOTICE: rxb 818, rx_count 4096
[2017/11/06 14:05:46:0648] NOTICE: send completed: 1024 x 12288
[2017/11/06 14:05:46:0658] NOTICE: Everything received: errs 0
[2017/11/06 14:05:46:0658] ERR: Exiting
[2017/11/06 14:05:46:0658] NOTICE: mirror: LWS_CALLBACK_CLOSED mirror_lifetime=0, rxb 1024, rx_count 0`
- lan
`[2017/11/06 12:06:28:1345] NOTICE: libwebsockets test client - license LGPL2.1+SLE
[2017/11/06 12:06:28:1385] NOTICE: (C) Copyright 2010-2017 Andy Green <andy@warmcat.com>
[2017/11/06 12:06:28:1430] NOTICE:  SSL disabled
[2017/11/06 12:06:28:1469] NOTICE:  Cert must validate correctly (use -s to allow selfsigned)
[2017/11/06 12:06:28:1510] NOTICE:  Requiring peer cert hostname matches
[2017/11/06 12:06:28:1553] NOTICE: libuv support not compiled in
[2017/11/06 12:06:28:1594] NOTICE: Creating Vhost 'default' port -1, 3 protocols, IPv6 on
[2017/11/06 12:06:28:1633] NOTICE: created client ssl context for default
[2017/11/06 12:06:28:1680] NOTICE: using  mode (ws)
[2017/11/06 12:06:28:1717] NOTICE: mirror: connecting
[2017/11/06 12:06:28:1758] NOTICE: lws_client_connect_2: 0x76f159b0: address 10.86.200.216
[2017/11/06 12:06:28:1815] NOTICE: lws_client_connect_2: 0x76f159b0: address 10.86.200.216
[2017/11/06 12:06:28:1880] NOTICE: mirror: LWS_CALLBACK_CLIENT_ESTABLISHED
[2017/11/06 12:06:29:0023] NOTICE: rxb 50, rx_count 0
[2017/11/06 12:06:30:0018] NOTICE: rxb 121, rx_count 4096
[2017/11/06 12:06:31:0006] NOTICE: rxb 196, rx_count 0
[2017/11/06 12:06:32:0003] NOTICE: rxb 267, rx_count 4096
[2017/11/06 12:06:33:0015] NOTICE: rxb 342, rx_count 0
[2017/11/06 12:06:34:0019] NOTICE: rxb 403, rx_count 4096
[2017/11/06 12:06:35:0013] NOTICE: rxb 478, rx_count 8192
[2017/11/06 12:06:36:0030] NOTICE: rxb 556, rx_count 4096
[2017/11/06 12:06:37:0036] NOTICE: rxb 635, rx_count 0
[2017/11/06 12:06:38:0009] NOTICE: rxb 710, rx_count 8192
[2017/11/06 12:06:39:0009] NOTICE: rxb 779, rx_count 8192
[2017/11/06 12:06:40:0009] NOTICE: rxb 856, rx_count 8192
[2017/11/06 12:06:41:0009] NOTICE: rxb 937, rx_count 8192
[2017/11/06 12:06:41:5203] NOTICE: send completed: 1024 x 12288
[2017/11/06 12:06:42:0039] NOTICE: rxb 1010, rx_count 4096
[2017/11/06 12:06:42:1692] NOTICE: Everything received: errs 0
[2017/11/06 12:06:42:1744] ERR: Exiting
[2017/11/06 12:06:42:1788] NOTICE: mirror: LWS_CALLBACK_CLOSED mirror_lifetime=0, rxb 1024, rx_count 0`
- internet
`[2017/11/06 12:07:36:4276] NOTICE: libwebsockets test client - license LGPL2.1+SLE
[2017/11/06 12:07:36:4316] NOTICE: (C) Copyright 2010-2017 Andy Green <andy@warmcat.com>
[2017/11/06 12:07:36:4356] NOTICE:  SSL disabled
[2017/11/06 12:07:36:4394] NOTICE:  Cert must validate correctly (use -s to allow selfsigned)
[2017/11/06 12:07:36:4439] NOTICE:  Requiring peer cert hostname matches
[2017/11/06 12:07:36:4478] NOTICE: libuv support not compiled in
[2017/11/06 12:07:36:4521] NOTICE: Creating Vhost 'default' port -1, 3 protocols, IPv6 on
[2017/11/06 12:07:36:4563] NOTICE: created client ssl context for default
[2017/11/06 12:07:36:4603] NOTICE: using  mode (ws)
[2017/11/06 12:07:36:4641] NOTICE: mirror: connecting
[2017/11/06 12:07:36:4684] NOTICE: lws_client_connect_2: 0x76ef19b0: address 
[2017/11/06 12:07:36:5079] NOTICE: lws_client_connect_2: 0x76ef19b0: address 
[2017/11/06 12:07:36:5472] NOTICE: mirror: LWS_CALLBACK_CLIENT_ESTABLISHED
[2017/11/06 12:07:37:0127] NOTICE: rxb 4, rx_count 0
[2017/11/06 12:07:38:0029] NOTICE: rxb 13, rx_count 4096
[2017/11/06 12:07:39:0284] NOTICE: rxb 23, rx_count 0
[2017/11/06 12:07:40:0179] NOTICE: rxb 32, rx_count 4096
[2017/11/06 12:07:41:0123] NOTICE: rxb 41, rx_count 8192
[2017/11/06 12:07:42:0202] NOTICE: rxb 51, rx_count 0
[2017/11/06 12:07:43:0115] NOTICE: rxb 60, rx_count 4096
[2017/11/06 12:07:44:0056] NOTICE: rxb 69, rx_count 8192
[2017/11/06 12:07:45:0277] NOTICE: rxb 79, rx_count 4096
[2017/11/06 12:07:46:0255] NOTICE: rxb 88, rx_count 8192
[2017/11/06 12:07:47:0004] NOTICE: rxb 97, rx_count 8192
[2017/11/06 12:07:48:0239] NOTICE: rxb 107, rx_count 4096
[2017/11/06 12:07:49:0019] NOTICE: rxb 116, rx_count 4096
[2017/11/06 12:07:50:0003] NOTICE: rxb 125, rx_count 8192
[2017/11/06 12:07:51:0112] NOTICE: rxb 135, rx_count 0
[2017/11/06 12:07:52:0046] NOTICE: rxb 144, rx_count 4096
[2017/11/06 12:07:53:0336] NOTICE: rxb 154, rx_count 0
[2017/11/06 12:07:54:0230] NOTICE: rxb 163, rx_count 4096
[2017/11/06 12:07:55:0312] NOTICE: rxb 172, rx_count 8192
[2017/11/06 12:07:56:0230] NOTICE: rxb 182, rx_count 0
[2017/11/06 12:07:57:0131] NOTICE: rxb 191, rx_count 4096
[2017/11/06 12:07:58:0045] NOTICE: rxb 200, rx_count 8192
[2017/11/06 12:07:59:0154] NOTICE: rxb 210, rx_count 0
[2017/11/06 12:08:00:0060] NOTICE: rxb 219, rx_count 4096
[2017/11/06 12:08:01:0285] NOTICE: rxb 228, rx_count 8192
[2017/11/06 12:08:02:0194] NOTICE: rxb 238, rx_count 0
[2017/11/06 12:08:03:0094] NOTICE: rxb 247, rx_count 4096
[2017/11/06 12:08:04:0010] NOTICE: rxb 256, rx_count 8192
[2017/11/06 12:08:05:0080] NOTICE: rxb 266, rx_count 0
[2017/11/06 12:08:06:0304] NOTICE: rxb 275, rx_count 8192
[2017/11/06 12:08:07:0247] NOTICE: rxb 285, rx_count 0
[2017/11/06 12:08:08:0210] NOTICE: rxb 294, rx_count 4096
[2017/11/06 12:08:09:0115] NOTICE: rxb 303, rx_count 8192
[2017/11/06 12:08:10:0189] NOTICE: rxb 313, rx_count 0
[2017/11/06 12:08:11:0112] NOTICE: rxb 322, rx_count 4096
[2017/11/06 12:08:12:0299] NOTICE: rxb 331, rx_count 8192
[2017/11/06 12:08:13:0186] NOTICE: rxb 341, rx_count 0
[2017/11/06 12:08:14:0075] NOTICE: rxb 350, rx_count 4096
[2017/11/06 12:08:15:0143] NOTICE: rxb 359, rx_count 8192
[2017/11/06 12:08:16:0093] NOTICE: rxb 369, rx_count 0
[2017/11/06 12:08:17:0344] NOTICE: rxb 378, rx_count 8192
[2017/11/06 12:08:18:0244] NOTICE: rxb 388, rx_count 0
[2017/11/06 12:08:19:0210] NOTICE: rxb 397, rx_count 4096
[2017/11/06 12:08:20:0275] NOTICE: rxb 406, rx_count 8192
[2017/11/06 12:08:21:0170] NOTICE: rxb 416, rx_count 0
[2017/11/06 12:08:22:0332] NOTICE: rxb 425, rx_count 4096
[2017/11/06 12:08:23:0275] NOTICE: rxb 434, rx_count 8192
[2017/11/06 12:08:24:0198] NOTICE: rxb 444, rx_count 0
[2017/11/06 12:08:25:0094] NOTICE: rxb 453, rx_count 4096
[2017/11/06 12:08:26:0183] NOTICE: rxb 462, rx_count 8192
[2017/11/06 12:08:27:0125] NOTICE: rxb 472, rx_count 0
[2017/11/06 12:08:28:0260] NOTICE: rxb 481, rx_count 4096
[2017/11/06 12:08:29:0183] NOTICE: rxb 490, rx_count 8192
[2017/11/06 12:08:30:0105] NOTICE: rxb 500, rx_count 0
[2017/11/06 12:08:31:0011] NOTICE: rxb 509, rx_count 4096
[2017/11/06 12:08:32:0104] NOTICE: rxb 518, rx_count 8192
[2017/11/06 12:08:33:0035] NOTICE: rxb 528, rx_count 0
[2017/11/06 12:08:34:0188] NOTICE: rxb 537, rx_count 8192
[2017/11/06 12:08:35:0216] NOTICE: rxb 547, rx_count 0
[2017/11/06 12:08:36:0110] NOTICE: rxb 556, rx_count 4096
[2017/11/06 12:08:37:0270] NOTICE: rxb 565, rx_count 8192
[2017/11/06 12:08:38:0162] NOTICE: rxb 575, rx_count 0
[2017/11/06 12:08:39:0291] NOTICE: rxb 584, rx_count 4096
[2017/11/06 12:08:40:0199] NOTICE: rxb 593, rx_count 8192
[2017/11/06 12:08:41:0137] NOTICE: rxb 603, rx_count 0
[2017/11/06 12:08:42:0027] NOTICE: rxb 612, rx_count 4096
[2017/11/06 12:08:43:0114] NOTICE: rxb 621, rx_count 8192
[2017/11/06 12:08:44:0034] NOTICE: rxb 631, rx_count 0
[2017/11/06 12:08:45:0291] NOTICE: rxb 640, rx_count 8192
[2017/11/06 12:08:46:0282] NOTICE: rxb 650, rx_count 0
[2017/11/06 12:08:47:0300] NOTICE: rxb 659, rx_count 4096
[2017/11/06 12:08:48:0245] NOTICE: rxb 668, rx_count 8192
[2017/11/06 12:08:49:0067] NOTICE: rxb 677, rx_count 8192
[2017/11/06 12:08:50:0302] NOTICE: rxb 687, rx_count 4096
[2017/11/06 12:08:51:0282] NOTICE: rxb 696, rx_count 8192
[2017/11/06 12:08:52:0180] NOTICE: rxb 706, rx_count 0
[2017/11/06 12:08:53:0226] NOTICE: rxb 715, rx_count 4096
[2017/11/06 12:08:54:0149] NOTICE: rxb 724, rx_count 8192
[2017/11/06 12:08:55:0063] NOTICE: rxb 734, rx_count 0
[2017/11/06 12:08:56:0331] NOTICE: rxb 743, rx_count 8192
[2017/11/06 12:08:57:0056] NOTICE: rxb 752, rx_count 8192
[2017/11/06 12:08:58:0326] NOTICE: rxb 762, rx_count 4096
[2017/11/06 12:08:59:0131] NOTICE: rxb 771, rx_count 4096
[2017/11/06 12:09:00:0052] NOTICE: rxb 780, rx_count 8192
[2017/11/06 12:09:01:0306] NOTICE: rxb 790, rx_count 4096
[2017/11/06 12:09:02:0239] NOTICE: rxb 799, rx_count 8192
[2017/11/06 12:09:03:0146] NOTICE: rxb 809, rx_count 0
[2017/11/06 12:09:04:0246] NOTICE: rxb 818, rx_count 4096
[2017/11/06 12:09:05:0210] NOTICE: rxb 827, rx_count 8192
[2017/11/06 12:09:06:0081] NOTICE: rxb 836, rx_count 8192
[2017/11/06 12:09:07:0294] NOTICE: rxb 846, rx_count 4096
[2017/11/06 12:09:08:0124] NOTICE: rxb 855, rx_count 4096
[2017/11/06 12:09:09:0029] NOTICE: rxb 864, rx_count 8192
[2017/11/06 12:09:10:0003] NOTICE: rxb 874, rx_count 4096
[2017/11/06 12:09:11:0252] NOTICE: rxb 883, rx_count 8192
[2017/11/06 12:09:12:0272] NOTICE: rxb 893, rx_count 0
[2017/11/06 12:09:13:0173] NOTICE: rxb 902, rx_count 4096
[2017/11/06 12:09:14:0145] NOTICE: rxb 911, rx_count 8192
[2017/11/06 12:09:15:0102] NOTICE: rxb 921, rx_count 0
[2017/11/06 12:09:16:0103] NOTICE: rxb 930, rx_count 4096
[2017/11/06 12:09:17:0044] NOTICE: rxb 939, rx_count 8192
[2017/11/06 12:09:18:0176] NOTICE: rxb 949, rx_count 0
[2017/11/06 12:09:19:0169] NOTICE: rxb 958, rx_count 4096
[2017/11/06 12:09:20:0302] NOTICE: rxb 967, rx_count 8192
[2017/11/06 12:09:21:0016] NOTICE: rxb 976, rx_count 8192
[2017/11/06 12:09:22:0011] NOTICE: rxb 986, rx_count 0
[2017/11/06 12:09:23:0275] NOTICE: rxb 995, rx_count 8192
[2017/11/06 12:09:24:0181] NOTICE: rxb 1005, rx_count 0
[2017/11/06 12:09:25:0111] NOTICE: rxb 1014, rx_count 4096
[2017/11/06 12:09:25:8958] NOTICE: send completed: 1024 x 12288
[2017/11/06 12:09:26:0216] NOTICE: rxb 1023, rx_count 8192
[2017/11/06 12:09:26:0262] NOTICE: Everything received: errs 0
[2017/11/06 12:09:26:0301] ERR: Exiting
[2017/11/06 12:09:26:0343] NOTICE: mirror: LWS_CALLBACK_CLOSED mirror_lifetime=0, rxb 1024, rx_count 0`


Some tests that I did on my own:
1.  use libwebsockets-openssl - works
2.  server and the client are on the same lan - works
3.  send only JSON messages < 4k - works
4.  Linksys WRT1900ACS (arm cortex a9) - works, TPLink C7 V4 (mips_24kc) does not work

**Comment by lws-team** [comment] 2017-11-06 22:00
Just to make sure... this boils down it only fails on mbedTLS + Big Endian?  Or there are LE cases it fails?

**Comment by reluWeb** [comment] 2017-11-07 08:09
I can confirm that the Linksys is LE and has no issues and 2 BE TP-Link routers have this issue with mbedtls.

**Comment by lws-team** [comment] 2017-11-07 09:47
Well, I have an rpi3.  Is it going to be super complicated to reproduce your test on it?

**Comment by reluWeb** [comment] 2017-11-07 15:46
I made a simple test server and a client that send 2 json messages. I reproduced the issue with the server on a Ubuntu and the client on RPi3 in the same network. If the server and client are on RPi3, there is no issue.
[test.zip](https://github.com/warmcat/libwebsockets/files/1450620/test.zip)

**Comment by lws-team** [comment] 2017-11-08 11:02
After buying a new SD card and various other unrelated fiddling, your C++ code reminded me I shouldn't be using the keyword "private" in the public headers as a function parameter, I fixed it in master.

I can follow the instructions and reproduce the problem (this is with ws-client on the rpi3 along with lws + mbedtls).   node.js on my x86_64 box is Fedora 27 packaged one, so that will have been built against OpenSSL 1.1.10f also from Fedora.

```
$ node app.js
Wed Nov 08 2017 18:31:37 GMT+0800 (CST) Server is listening on port 8080
Wed Nov 08 2017 18:32:35 GMT+0800 (CST) Peer ::ffff:192.168.2.236 connected.
Received ->  { glossary: 
   { title: 'example glossary',
     GlossDiv: { title: 'S', GlossList: [Object] } } }
SEND -> FAILED SyntaxError: Unexpected string in JSON at position 4111
    at JSON.parse (<anonymous>)
    at WebSocketConnection.connection.on (/home/agreen/Downloads/qq/ws-server/app.js:38:35)
    at emitOne (events.js:115:13)
    at WebSocketConnection.emit (events.js:210:7)
    at WebSocketConnection.processFrame (/home/agreen/Downloads/qq/ws-server/node_modules/websocket/lib/WebSocketConnection.js:552:26)
    at /home/agreen/Downloads/qq/ws-server/node_modules/websocket/lib/WebSocketConnection.js:321:40
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
1002 'Unsupported usage of rsv bits without negotiated extension.'
Wed Nov 08 2017 18:32:55 GMT+0800 (CST) Peer ::ffff:192.168.2.236 disconnected.
Wed Nov 08 2017 18:32:55 GMT+0800 (CST) Peer ::ffff:192.168.2.236 connected.
```

There's a pause of 10s or so before it blows.

"Control frames cannot be fragmented" is just another symptom of the same problem, there's a loss of ws framing sync which can be noticed by one illegal thing or another happening.

I confirmed it can complete (?) a couple of times in a row with openssl instead of mbedtls  on the Rpi3 side; it prints `Client received:success`.

I'll continue looking at it tomorrow, but there seems to be a few 10ms usleep()s floating around.  These are necessary to make the problem come?

**Comment by lws-team** [comment] 2017-11-08 12:30
Hmm I found the underlying problem... it's a bug in the mbedtls / openssl wrapper.  I pushed a fix on master + v2.4-stable.  Please try it.

**Comment by reluWeb** [comment] 2017-11-08 14:32
Thank you very much for your effort. Now I have a new error on the server side when processing a text frame: **invalid UTF-8 Data Received**.

**Comment by lws-team** [comment] 2017-11-08 16:19
... so this is what I should see from your test app?  Or 'big JSONs' means something different?

I should see it with rpi3?  How can I reproduce?

**Comment by lws-team** [comment] 2017-11-08 23:46
... never mind I can reproduce it using the mirror test client thing on rpi3... I will study it thismorning.

**Comment by lws-team** [comment] 2017-11-09 00:04
There's a completely separate mbedtls restriction the wrapper also didn't take care about.  Please once again try master... this can pass the test client -s with mbedTLS on rpi3 now.

**Comment by reluWeb** [comment] 2017-11-09 12:13
I tested with the latest version. I can confirm that on the same network the test client and the server work, but if the server is in cloud ( still Ubuntu ) it still fails with 'Invalid UTF-8 Data Received' for the second JSON. 
Except rpi, on other devices I had no issue if the server was on the same lan. The problem was when sending over internet.
If it helps I can setup a test server.

**Comment by lws-team** [comment] 2017-11-09 12:26
I see.  I can implement the ws-server remotely myself I think, unless F26 node.js is radically different from f27.

As you can probably guess from the fact it's fine with lws + openssl, what we're fighting here isn't directly lws and it isn't directly mbedtls... it's an adaptation wrapper from espressif that presents mbedtls as openssl api.    It has a lot of bugs and the originators of the wrapper have no interest in cooperation to fix them, they just ignored my first PR with fixes for ~two months now, and since then I have a pile of fixes.  Broadly it works well, but it has not had the right kind of attention to these scenarios and simply doesn't support them correctly.  It's a shame they can't imagine to cooperate... in the medium term I want to eliminate the wrapper gradually but it's a serious amount of work.  So fixing our fork of the wrapper is the way forward for now.

Anyway these last two fixes did solve two bugs with the wrapper and made it much more solid, thanks a lot for your debugging help.  I'll try it with a France <-> Taiwan server / client tomorrow and see what happens.

**Comment by reluWeb** [comment] 2017-11-09 12:31
Thank you very much for your effort and let me know if I can help with anything else.

**Comment by lws-team** [comment] 2017-11-10 03:03
Please try master once again.  I could reproduce it using the mirror echo mode and now it's working fine from the Rpi3 in Taipei using mbedTLS to libwebsockets.org in France.

**Comment by lws-team** [comment] 2017-11-12 08:55
Any news about this?

**Comment by reluWeb** [comment] 2017-11-13 16:10
I have tested on all my devices and not mbedtls works perfectly.

**Comment by lws-team** [comment] 2017-11-13 16:57
Super... thanks a lot for helping out.

**Closed by lws-team** 2017-11-13 16:57 UTC
