### ISSUE TITLE
ERR: lws_free_wsi: ah leak: wsi 0x7f7a2c054660

### ISSUE THREAD

**Issue by michael2009** [warmcat/libwebsockets#1154] opened 2018-01-16 14:36 UTC
[2018/01/16 12:20:57:9698] NOTICE: lws_return_http_status: return
[2018/01/16 12:59:48:7668] NOTICE: lws_return_http_status: return
[2018/01/16 12:59:48:8320] NOTICE:  forbidding on uri sanitation
[2018/01/16 12:59:48:8321] NOTICE: lws_return_http_status: return
[2018/01/16 12:59:49:7766] NOTICE: error on reading from skt : 104
[2018/01/16 16:45:21:6210] NOTICE:  forbidding on uri sanitation
[2018/01/16 16:45:21:6211] NOTICE: lws_return_http_status: return
[2018/01/16 16:48:02:6086] ERR: lws_free_wsi: ah leak: wsi 0x7f7a2c054660
[2018/01/16 17:25:59:4869] NOTICE:  forbidding on uri sanitation
[2018/01/16 17:25:59:4870] NOTICE: lws_return_http_status: return
[2018/01/16 19:27:02:2423] NOTICE: error on reading from skt : 104
[2018/01/16 20:22:17:8117] NOTICE: error on reading from skt : 110
[2018/01/16 20:22:37:2677] NOTICE: error on reading from skt : 110

**Comment by lws-team** [comment] 2018-01-16 22:19
What version of lws was this?

**Comment by lws-team** [comment] 2018-01-17 01:48
It doesn't seem to have happened on libwebsockets.org, which is running master, at least in the recent past

```
# journalctl -an 1000000 | grep "ah leak"
#
```

master doesn't have any lwsl_notice in lws_return_http_status either.  See if you still have the same problem on master.

**Comment by michael2009** [comment] 2018-01-17 02:24
https://github.com/warmcat/libwebsockets/archive/v2.4.1.tar.gz

+= -DLWS_WITH_LIBEVENT=ON
+= -DLWS_OPENSSL_SUPPORT=ON
+= -DLWS_WITH_SSL=ON

**Comment by lws-team** [comment] 2018-01-17 02:33
The code that prints this, even on v2.4 fixes up the ah that's still bound to the wsi, just before deleting the wsi.

```
        ah = pt->ah_list;
        while (ah) {
                if (ah->in_use && ah->wsi == wsi) {
                        lwsl_err("%s: ah leak: wsi %p\n", __func__, wsi);
                        ah->in_use = 0;
                        ah->wsi = NULL;
                        pt->ah_count_in_use--;
                        break;
                }
                ah = ah->next;
        }
```

...so no ah actually leaks, it's reporting that it would have leaked.  It's fixed in master I believe (the detect code is still there but "never" detects the situation for 1M system logs, which goes back to 2017-10-10 in my case) so I think since no symptom other than this message, no point spending time on it.

If you are still concerned try master, I'll also be concerned if the problem is still coming there.  master will soon become v2.5.

**Closed by lws-team** 2018-01-17 02:33 UTC
