### ISSUE TITLE
Delayed ACK

### ISSUE THREAD

**Issue by caobug** [warmcat/libwebsockets#1889] opened 2020-04-15 07:26 UTC
Hello, I download the data from the remote server to the local, every time the data is transmitted will be delayed by 100-200ms

If I set a higher `rx_buffer_size` on the remote server, such as 128k, I will get a 50ms delay.

The higher the `rx_buffer_size` value, the lower the ACK delay and the faster the transmission rate. In contrast, the transmission rate is very slow.

I have manually disabled nagle on `LWS_CALLBACK_CLIENT_ESTABLISHED` and `LWS_CALLBACK_ESTABLISHED`

```
int opt = 1;
setsockopt(lws_get_socket_fd(wsi), IPPROTO_TCP, TCP_NODELAY, &opt, sizeof(opt));
```

Although setting `rx_buffer_size` can solve the problem, it will consume a lot of memory space.

Can you tell where the problem is?

<img width="894" alt="pic" src="https://user-images.githubusercontent.com/7737673/79309518-02799600-7f2d-11ea-9355-5974e96125d9.png">

**Comment by lws-team** [comment] 2020-04-15 07:29
> Can you tell where the problem is?

Not really, if I could do that I would just predict lottery numbers.

Does this problem exist on the minimal examples?  On Linux?  On a different machine?  On a different AP?  On a different network?  What else has to be like your situation before the problem is coming?

**Comment by caobug** [comment] 2020-04-15 08:48
Remote: Centos 7.x, installed google bbr. libwebsockets version 3.2.2, used Libev event loop.
Local: macOS

local -> remote, ping 170ms.

And I changed `rx_buffer_size` to 8k, the speed just 55kb/s. In order to exclude the server network problem, I used nginx proxy libwebsockets, the transfer rate is normal,  have 1MB/s

```
http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    server {
         server_name domain.com;
         listen 444 ssl;
         location / {
             proxy_pass https://127.0.0.1:443;
             proxy_read_timeout 300s;
             proxy_send_timeout 300s;
             
             proxy_set_header Host $host;
             proxy_set_header X-Real-IP $remote_addr;
             proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
             
             proxy_http_version 1.1;
             proxy_set_header Upgrade $http_upgrade;
             proxy_set_header Connection $connection_upgrade;
         }
        ssl_certificate /usr/local/libwebsockets/ssl.cer;
        ssl_certificate_key /usr/local/libwebsockets/ssl.key;
    }
}
```

local -> remote libwebsockets 443, delayed 130ms

<img width="890" alt="direct" src="https://user-images.githubusercontent.com/7737673/79316967-aec07a00-7f37-11ea-97ad-fe576667e209.png">

local -> remote nginx 444 -> libwebsockets 443, delay and speed is normal.

<img width="785" alt="nginx" src="https://user-images.githubusercontent.com/7737673/79317223-07901280-7f38-11ea-9c26-bc4299b0db6a.png">

30 days.... I still haven't found the problem. so sad

**Comment by lws-team** [comment] 2020-04-15 08:51
The angle you're looking at it from clearly isn't helping you find out the cause.  And whatever setup and code you have, it's only you that has it.  So why don't you put that on one side and look at it from a different angle where someone else might be able to help you --->

> Does this problem exist on the minimal examples? On Linux? On a different machine? On a different AP? On a different network? What else has to be like your situation before the problem is coming?

...or you can just ignore anything except keep banging away at it yourself for another 30 days...

**Comment by caobug** [comment] 2020-04-15 11:19
local to local`100MB/s`, remote to local `0.019455 MB/s`

**All server code:** 
```
#include <stdio.h>

#include <ev.h>
#include <libwebsockets.h>

#define BUF_SIZ 4096

struct session_data {
    // ignore
};

static struct lws_context *context;
static unsigned char *buf;

static int service_callback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
    int error;
    switch (reason) {
        case LWS_CALLBACK_ESTABLISHED:
            buf = malloc(BUF_SIZ);
            lws_callback_on_writable(wsi);
            break;
        case LWS_CALLBACK_SERVER_WRITEABLE:
            error = lws_write(wsi, buf + LWS_PRE, BUF_SIZ - LWS_PRE, LWS_WRITE_BINARY);
            if (error <= 0) {
                return -1;
            }
            lws_callback_on_writable(wsi);
            break;
        default:
            break;
    }
    return 0;
}

static struct lws_protocols protocols[] = {
    {
        "example",
        service_callback,
        sizeof(struct session_data),
        BUF_SIZ, 0, NULL, BUF_SIZ
    },
    { NULL, NULL, 0, 0 }
};

static const struct lws_extension extensions[] = {
    {
        "permessage-deflate",
        lws_extension_callback_pm_deflate,
        "permessage-deflate"
         "; client_no_context_takeover"
         "; client_max_window_bits"
    },
    { NULL, NULL, NULL /* terminator */ }
};

int main(int argc, const char * argv[]) {
    struct lws_context_creation_info info;
    void *foreign_loops[1] = { EV_DEFAULT };
    
    memset(&info, 0, sizeof info);
    
    info.foreign_loops = foreign_loops;
    info.port = 4443;
    info.protocols = protocols;
    info.options = LWS_SERVER_OPTION_LIBEV;
    info.extensions = extensions;
    
    context = lws_create_context(&info);
    if (!context) {
        printf("Failed init lws context\n");
        return -1;
    }
    
    printf("Started on 0.0.0.0:4443\n");
    
    ev_run(EV_DEFAULT, 0);
    
    return 0;
}
```

**All client code:**
```
#include <stdio.h>

#include <ev.h>
#include <libwebsockets.h>

#define BUF_SIZ 4096

struct session_data {
    // ignore
};

static struct lws_context *context;
static struct ev_timer watcher;
static long count;

static int service_callback(struct lws *wsi, enum lws_callback_reasons reason, void *user, void *in, size_t len) {
    switch (reason) {
        case LWS_CALLBACK_WSI_CREATE:
            printf("connected\n");
            break;
        case LWS_CALLBACK_CLIENT_RECEIVE:
            count += len;
            break;
        default:
            break;
    }
    return 0;
}

static void timeouts(EV_P_ ev_timer *w, int revents) {
    double speed = count / 1024.0 / 1024.0;
    printf("Network: %f MB/s\n", speed);
    count = 0;
}

static struct lws_protocols protocols[] = {
    {
        "example",
        service_callback,
        sizeof(struct session_data),
        BUF_SIZ, 0, NULL, BUF_SIZ
    },
    { NULL, NULL, 0, 0 }
};

static const struct lws_extension extensions[] = {
    {
        "permessage-deflate",
        lws_extension_callback_pm_deflate,
        "permessage-deflate"
         "; client_no_context_takeover"
         "; client_max_window_bits"
    },
    { NULL, NULL, NULL /* terminator */ }
};

int main(int argc, const char * argv[]) {
    struct lws_context_creation_info info;
    struct lws_client_connect_info cinfo;
    void *foreign_loops[1] = { EV_DEFAULT };
    
    memset(&info, 0, sizeof info);
    info.foreign_loops = foreign_loops;
    info.port = CONTEXT_PORT_NO_LISTEN;
    info.protocols = protocols;
    info.options = LWS_SERVER_OPTION_LIBEV;
    info.extensions = extensions;
    
    context = lws_create_context(&info);
    if (!context) {
        printf("Failed init lws context\n");
        return -1;
    }
    
    memset(&cinfo, 0, sizeof(cinfo));
    cinfo.context = context;
    cinfo.address = "127.0.0.1";
    cinfo.port = 4443;
    cinfo.host = "localhost";
    cinfo.path = "/";
    cinfo.origin = "localhost";
    cinfo.protocol = protocols[0].name;
    
    if (!lws_client_connect_via_info(&cinfo)) {
        printf("failed connnect.\n");
        return -1;
    }
    
    ev_timer_init(&watcher, timeouts, 1, 1);
    ev_timer_start(EV_DEFAULT, &watcher);
    
    ev_run(EV_DEFAULT, 0);
    
    return 0;
}
```

**Comment by caobug** [comment] 2020-04-16 09:37
And 4.0.1 can't compile to iOS.

```
lib/plat/unix/unix-sockets.c:31:10: fatal error: 'net/route.h' file not found
```
https://forums.developer.apple.com/thread/84607

And
```
lib/plat/unix/private-lib-plat-unix.h:50:10: fatal error: 'sys/eventfd.h' file not found
```

**Comment by lws-team** [comment] 2020-04-16 10:01
It's fixed on v4.0-stable a while ago.

**Comment by caobug** [comment] 2020-04-16 11:08
> It's fixed on v4.0-stable a while ago.

No. `lib/plat/unix/unix-sockets.c:31:10: fatal error: 'net/route.h' file not found`

**Comment by lws-team** [comment] 2020-04-16 11:59
> sys/eventfd.h

This is fixed... but on master.

https://libwebsockets.org/git/libwebsockets/commit?id=eb5a41eeb55002e23b8360206b82cab617369352

For the iOS thing, there was a guy from Huawei on the mailing list telling me the same thing.  I want to point you to what I told him

https://libwebsockets.org/pipermail/libwebsockets/2020-April/008456.html

**Comment by caobug** [comment] 2020-04-16 13:39
@lws-team Thank you, I will check.

Sometimes my CPU is 100%, I don't know what caused it. 

Is it related to `lws_rx_flow_control`?

<img width="286" alt="QQ20200416-213354@2x" src="https://user-images.githubusercontent.com/7737673/79462386-fde6d780-8029-11ea-9ed8-bf296c04c566.png">

**Comment by lws-team** [comment] 2020-04-16 18:16
rx flow control is a way of turning off POLLIN event, it can only leave it listening for POLLIN the same, or disable anything waking it up for POLLIN on that socket.

If you're constantly waking on somebody's POLLIN, it seems there's still something to read on that socket by the time you return to the event loop.  If it's h1 client, you must handle the READ related callbacks as shown in the example... you are expected to call an api to do the actual recv() to clear what was sent to you. 

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-multi/minimal-http-client-multi.c#n99

Otherwise it'll come straight back telling you there's something to read forever.

**Comment by caobug** [comment] 2020-04-17 03:07
Thank you for your guidance.

Since I ca n’t handle all received websockets content in the LWS_CALLBACK_CLIENT_RECEIVE callback, I need to pause the recv event listen and resume it at the right time.

In this scenario, what kind of API should I call to clear these data sent to me?

**Comment by lws-team** [comment] 2020-04-17 03:46
For h1, you can apply rx flow control to the connection. It turns off POLLIN / RX event handling and leaves the data buffered in kernelside.

https://libwebsockets.org/git/libwebsockets/tree/plugins/protocol_lws_mirror.c#n82

You still waste memory kernelside, but the local tcp stack realizes you are not consuming it and stops sending the peer acks indicating the tcp window moved on, after a short while the peer can no longer send (in tcp terms, the window is full and the connection choked, in lws terms, the sending peer stops getting writeable indications) until the receiver consumes something to make space.

That's just how tcp works.

For h2, you can't do that since one stream is no longer one socket.  You must use tx credit management to inform the peer how much it may send you and manage that dynamically.

https://libwebsockets.org/git/libwebsockets/tree/minimal-examples/http-client/minimal-http-client-h2-rxflow

If memory or latency is any kind of factor, producing output before the peer can consume it quickly changes from "smart pipelining to maximize throughput" into a big problem.  The h2 way is more complex but ultimately provides tighter control over what is sent when and the buffer size needed at the receiver.  So long as the h2 stack isn't buggy for it on both sides.

**Comment by caobug** [comment] 2020-04-17 04:35
Yes, I have called `lws_rx_flow_control` to control the receive. However, when the `rx_buffer_size` of client side is smaller than the `tx_packet_size` of server side, if call `lws_rx_flow_control(wsi, 0)`, will cause the CPU to fill up.It looks like I have to extract all the data from the buffer and call lws_rx_flow_control to pause the receiving data. 

I think `lws_rx_flow_control` and `libev ev_io_stop` have the same efficacy, no side effects, just don't know what caused the libwebsockets infinite loop.

```
2020/04/17 12:26:18:8681] D: lws_ws_handshake_client: hs client feels it has 12 in
2020/04/17 12:26:18:8681] D: lws_ws_handshake_client: caching 12
2020/04/17 12:26:18:8681] D: lws_rxflow_cache: rxflow append 12
2020/04/17 12:26:18:8681] D: _realloc: size 53: lws_buflist_append_segment
2020/04/17 12:26:18:8681] D: lws_read_h1: h1 path: wsi state 0x119
2020/04/17 12:26:18:8681] D: lws_ws_handshake_client: hs client feels it has 12 in
2020/04/17 12:26:18:8681] D: lws_ws_handshake_client: caching 12
2020/04/17 12:26:18:8682] D: lws_rxflow_cache: rxflow append 12
2020/04/17 12:26:18:8682] D: _realloc: size 53: lws_buflist_append_segment
2020/04/17 12:26:18:8682] D: lws_read_h1: h1 path: wsi state 0x119
2020/04/17 12:26:18:8682] D: lws_ws_handshake_client: hs client feels it has 12 in
2020/04/17 12:26:18:8682] D: lws_ws_handshake_client: caching 12
2020/04/17 12:26:18:8682] D: lws_rxflow_cache: rxflow append 12
2020/04/17 12:26:18:8682] D: _realloc: size 53: lws_buflist_append_segment
...
```

**Comment by lws-team** [comment] 2020-04-17 04:48
> `ev_io_stop`

If you use libev, that is what the lws generic flow control api does.  But if you're not using libev, the lws api will still continue to work the same, either disabling POLLIN on poll()-type wait or using libuv, libevent, or glib equivalents to get the job done.

There is something that was read by lws, but you have not consumed it.

Lws has received and cleared the POLLIN event for that, lws has to take care to make sure you get called to service it again in order that you can clear it, because there won't be another network event triggering it; it's already read and buffered.  But you're not reading it.

Lws does try to understand if you flowcontrolled the connection and suppress these indications

https://libwebsockets.org/git/libwebsockets/tree/lib/core-net/service.c#n565

Assuming you're using the lws api and not trying to go behind its back with the libev one, you'll need to look into it and add logging to try to understand what's going on.

**Comment by caobug** [comment] 2020-04-17 08:51
Thank you. I have tried many methods, and didn't solve the problem. Finally, I modified value `client rx_buffer_size` > `remote tx_packet_size`, it seems ok..

....

However I have encountered new problems on `v4.0-stable`, may have nothing to do with libwebsockets

```
malloc: tiny_free_list_remove_ptr: Internal invariant broken (next ptr of prev): ptr=0x10681f2b0, prev_next=0x0
Test
(79009,0x100565dc0) malloc: *** set a breakpoint in malloc_error_break to debug
```
<img width="318" alt="1111" src="https://user-images.githubusercontent.com/7737673/79550279-b49a9480-80ca-11ea-9b26-624e70126046.png">

**Comment by lws-team** [comment] 2020-04-17 08:58
pthread_kill...  run it under valgrind and look for the first sign of madness.

**Comment by caobug** [comment] 2020-05-01 07:13
Hello, I found the reason for the memory error, because I called free twice.

I have set custom object in `lws_client_connect_info.userdata`.

I want to release the `userdata` object when the connection closes. however `LWS_CALLBACK_CLIENT_CONNECTION_ERROR` and `LWS_CALLBACK_CLIENT_CLOSED` execute simultaneously (sometimes).

I tried to process the release in `LWS_CALLBACK_CLIENT_CLOSED`, ignoring the `LWS_CALLBACK_CLIENT_CONNECTION_ERROR`.

however sometimes the memory will stay and never be freed.

**Create**
```
struct session *pss = malloc()...

struct lws_client_connect_info info;
info.userdata = pss;
...
lws_client_connect_via_info(&info);
```

**Request to close in other func**
```
lws_set_timeout(pss->wsi, PENDING_TIMEOUT_CLOSE_SEND, LWS_TO_KILL_ASYNC);
```

**Free**
```
switch (reason) {
    case LWS_CALLBACK_CLIENT_CLOSED:
        free_session(pss); // free all data..
        break;
    case LWS_CALLBACK_CLIENT_CONNECTION_ERROR:
        free_session(pss); // free all data...
        break;
}
```

What should I do, please..

**Comment by lws-team** [comment] 2020-05-01 07:26
Valgrind would find that kind of heap error very rapidly.

> however LWS_CALLBACK_CLIENT_CONNECTION_ERROR and LWS_CALLBACK_CLIENT_CLOSED execute simultaneously (sometimes).

... what does it mean "simultaneously"?  There can't be any "simultaneous" with an event loop.  You mean, "sequentially"?

If you mean sequentially, it's a bug... for one wsi, you should either get a CONNECTION_ERROR if the connection didn't get established, or a CLOSED if it did.

> however sometimes the memory will stay and never be freed.

... uh... doubt it... it sounds a bit confused.

If you set the .userdata, lws understands it shouldn't free it itself since it doesn't know what it is.  But a wsi will eventually want to be destroyed, and it will call one of CONNECTION_ERROR or CLOSED.  Wsi go through that process at context destroy time if they are still open, so it's something that should always happen.

The user data thing is really designed for auto-allocation by lws and auto-free, using the size that you set in the protocol struct.  There's a parallel attribute you have more direct control over, `opaque_user_data`.

https://libwebsockets.org/git/libwebsockets/tree/include/libwebsockets/lws-client.h#n138

You can get this out of the wsi with `lws_get_opaque_user_data(wsi)` and you can also set it with `lws_set_opaque_user_data(wsi, void *)`.

I'd use those instead of user_data, and set pss to `lws_get_opaque_user_data(wsi)`.  When you free your data, use the set api to set it to NULL so you can never free it twice whatever your code is doing.

**Closed** 2020-05-12 05:15 UTC
