### ISSUE TITLE
libwebsockets.a(Android) does not work properly

### ISSUE THREAD

**Issue by mindori** [warmcat/libwebsockets#872] opened 2017-04-13 13:11 UTC
Hi.
I'd like to get some help with Android build.

I used the latest version of libwebsockets.
Build system specifications are as follows.
```
uname -a
: Linux ...amzn1.x86_64 #1 SMP Fri Aug 12 23:25:10 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

version of ndk
: android-ndk-r12b-linux-x86_64.zip

version of imake
: imake 1.0.2-11.7.amzn1

version of cmake
: cmake 2.8.12-2.22.amzn1
```

The installation log is located on the following link
: https://gist.github.com/mindori/3cb55ce5baf14fbd7d9d7cb7ffec2426

Abnormal log is as follows
```
makedepend: warning:  cryptlib.c (reading /usr/include/stdlib.h, line 32): cannot find include file "stddef.h"
	not in /include/stddef.h
	not in ./stddef.h
	not in ../stddef.h
	not in ../include/stddef.h
	not in /usr/include/stddef.h
makedepend: warning:  /usr/include/time.h includes /usr/include/bits/types.h more than once!
Already have
	/usr/include/bits/types.h
makedepend: warning:  /usr/include/time.h includes /usr/include/bits/types.h more than once!
Already have
	/usr/include/bits/types.h
makedepend: warning:  /usr/include/time.h includes /usr/include/bits/types.h more than once!
Already have
	/usr/include/bits/types.h
makedepend: warning:  cryptlib.c (reading /usr/include/sys/types.h, line 146): cannot find include file "stddef.h"
	not in /include/stddef.h
	not in ./stddef.h
	not in ../stddef.h
	not in ../include/stddef.h
	not in /usr/include/stddef.h
makedepend: warning:  cryptlib.c (reading /usr/include/alloca.h, line 24): cannot find include file "stddef.h"
	not in /include/stddef.h
	not in ./stddef.h
	not in ../stddef.h
	not in ../include/stddef.h
	not in /usr/include/stddef.h
makedepend: warning:  cryptlib.c (reading /usr/include/string.h, line 32): cannot find include file "stddef.h"
	not in /include/stddef.h
	not in ./stddef.h
	not in ../stddef.h
	not in ../include/stddef.h
	not in /usr/include/stddef.h
makedepend: warning:  cryptlib.c (reading /usr/include/unistd.h, line 226): cannot find include file "stddef.h"
	not in /include/stddef.h
	not in ./stddef.h
	not in ../stddef.h
	not in ../include/stddef.h
	not in /usr/include/stddef.h
...
```

Anyway, I made libwebsockets.a file.
But, this library file doesn't seem to function normally.
The following error occurs when I build Unreal Engine 4 using libwebsockets.a file.
```
libwebsockets/contrib/libwebsockets/lib/ssl-client.c:138: error: undefined reference to 'SSL_get0_param'
libwebsockets/contrib/libwebsockets/lib/ssl-client.c:140: error: undefined reference to 'X509_VERIFY_PARAM_set_hostflags'
libwebsockets/contrib/libwebsockets/lib/ssl-client.c:142: error: undefined reference to 'X509_VERIFY_PARAM_set1_host'
libwebsockets/contrib/libwebsockets/lib/ssl-http2.c:99: error: undefined reference to 'SSL_CTX_set_alpn_select_cb'
libwebsockets/contrib/libwebsockets/lib/ssl-http2.c:116: error: undefined reference to 'SSL_get0_alpn_selected'
```

How can we fix these errors?
Please help me.

**Comment by lws-team** [comment] 2017-04-13 13:48
Dunno, looks like your toolchain is borked.

These problems don't seem anything to do with lws,but you can check just trying to build the same lws tree in a normal Linux distro.

**Comment by mindori** [comment] 2017-04-14 01:15
I tried it on Fedora7 but it is still not performed. 
(I used `android-make-script.sh`)

Which NDK tool should I use?
My NDK tool from https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip

**Comment by lws-team** [comment] 2017-04-14 01:22
Fedora 7?  Current Fedora release is 25.

Android build is contributed, I don't build it for Android myself and I can't support it.

**Comment by mindori** [comment] 2017-04-14 01:35
Sorry. My OS is `Red Hat Enterprise Linux Server 7.3`
That's too bad...

Uhm... is there any formal way to libwebsockets Android build?

**Comment by lws-team** [comment] 2017-04-14 01:41
Other people have used it successfully, including this guy 3wks ago

https://github.com/warmcat/libwebsockets/issues/842

So I think a) it works and b) we provide enough info to make it build.

Looking again at your problems the first ones are warnings that don't mean anything... they are looking at which includes include what, but your toolchain decides who include ./bits/*.  They are not actually errors.

The second set of errors are related to your OpenSSL version compared to the OpenSSL version CMake saw.  It's often caused by giving CMake your build machine OpenSL headers instead of the cross headers that belong to the cross libraries you are linking against.

The last two errors are just that you should not configure HTTP2 at CMake since it requires modern OpenSSL you probably don't have.

**Comment by lws-team** [comment] 2017-04-14 02:24
At any rate since others can link to OpenSSL OK with Android I think this is not a problem with lws, so closing.

**Closed by lws-team** 2017-04-14 02:24 UTC

**Comment by mindori** [comment] 2017-04-14 03:02
Thanks! :) 
The problem caused by OpenSSL version. CMake OpenSSL version differs from that Linux OpenSSL version.

**Comment by honjane** [comment] 2017-04-15 14:43
@mindori  I modified android-make-script.sh ，replace toolchain，it successfully

https://github.com/honjane/buildLibWebSocket/blob/master/buildws/android-make-script-all.sh

**Comment by tim9han** [comment] 2025-06-17 17:54
I modified [honjane](https://github.com/honjane) script to use with modern NDK (NDK r19+). 
But without using SSL, need more work to build https server. I sucessefully build mu http server. Available on github
https://github.com/tim9han/buildLibWebSocket
