### ISSUE TITLE
CMake error when outputing to an out of tree build folder

### ISSUE THREAD

**Issue by nemoem** [warmcat/libwebsockets#1992] opened 2020-07-29 22:37 UTC
Hello! First... thank you for this amazing software, and your dedication to it.

On Windows, I get these errors when I run cmake with a different output build folder than the example one, outside of the source tree:

```
-- Configuring done
CMake Error at test-apps/CMakeLists.txt:73 (add_executable):
  Cannot find source file:

    ../../win32port/win32helpers/getopt.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx
Call Stack (most recent call first):
  test-apps/CMakeLists.txt:125 (create_test_app)


CMake Error at test-apps/CMakeLists.txt:73 (add_executable):
  No SOURCES given to target: test-server
Call Stack (most recent call first):
  test-apps/CMakeLists.txt:125 (create_test_app)


CMake Error at test-apps/CMakeLists.txt:73 (add_executable):
  No SOURCES given to target: test-lejp
Call Stack (most recent call first):
  test-apps/CMakeLists.txt:171 (create_test_app)


CMake Error at test-apps/CMakeLists.txt:73 (add_executable):
  No SOURCES given to target: test-client
Call Stack (most recent call first):
  test-apps/CMakeLists.txt:214 (create_test_app)


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

It used to work, now it only works when I output the files to ./build exactly as in the examples and use `cmake ..`
It broke my build script when I updated to the latest version from version 3.1 and it's probably because of the new cmakelists files.

I have no idea how cmake figures out relative paths (or how cmake does most things in general) and why it happens. Editing out `../` on https://github.com/warmcat/libwebsockets/blob/master/test-apps/CMakeLists.txt#L60 and on the couple of lines next to it does fix it though, but no idea if that breaks anything.

**Comment by lws-team** [comment] 2020-07-30 05:05
Thanks for letting me know.

> it's probably because of the new cmakelists files.

Right, that was a major refactor / maintainability upgrade internally that should seem like a NOP for users.  It's tested for a lot of build options and platforms, including windows, but it is almost all in ./build as you say (the esp32 one has it elsewhere, but it doesn't build the old test apps).

On Fedora + master, I can't reproduce it by `cd /tmp && mkdir b ; cd b ; cmake /projects/libwebsockets`, it's specific to windows.  As you found it's because ${WIN32_HELPERS_PATH} is already corrected for the CMakeLists.txt level, unlike the other source files it doesn't need adapting for the fact the CMakeLists.txt is now one level down in the source tree.

I pushed the fix you found on master.

**Closed by lws-team** 2020-07-30 05:05 UTC

**Comment by nemoem** [comment] 2020-07-30 13:55
BTW, I never used plugins but when I looked up the issue yesterday, searching the repo for ${WIN32_HELPERS_PATH} I noticed they use the same `../${WIN32_HELPERS_PATH}` and I just tested with `-DLWS_WITH_PLUGINS=1` it gave the same errors.

**Comment by lws-team** [comment] 2020-07-30 14:03
Right... it's the same deal.  I updated the patch here to cover that as well and I'll push it later on master.
