### ISSUE TITLE
Server failing to process pipelined calls

### ISSUE THREAD

**Issue by dosvald** [warmcat/libwebsockets#638] opened 2016-09-28 09:00 UTC
When a HTTP/1.1 client talks with a libwebsockets-powered server and pipelines multiple HTTP requests in a single TCP connection, depending on the network and/or OS conditions of the two peers and/or hops between them, libwebsockets will fail to process the pipelined requests beyond the first one. The client will then hang on to the HTTP connection, waiting for more pipelined responses, but they will never arrive.

The problem is present when, due to speed of incoming traffic, a single `recvfrom` call results in data containing multiple (pipelined) HTTP requests, in which case lws only processes the first one. There may be other similar cases triggerint the behavior too, however. Using SSL I was not able to reproduce it.

The issue is easiest to reproduce with the tool httperf:
```
$ httperf --server libwebsockets.org --port 80 --uri /favicon.ico --max-connections 1 --num-calls 20 --burst-length 2 --timeout 5

httperf --timeout=5 --client=0/1 --server=libwebsockets.org --port=80 --uri=/favicon.ico --max-connections=1 --send-buffer=4096 --recv-buffer=16384 --num-conns=1 --num-calls=20 --burst-length=2
httperf: warning: open file limit > FD_SETSIZE; limiting max. # of open files to FD_SETSIZE
Maximum connect burst length: 0

Total: connections 1 requests 4 replies 3 test-duration 5.629 s

Connection rate: 0.2 conn/s (5629.3 ms/conn, <=1 concurrent connections)
Connection time [ms]: min 5629.3 avg 5629.3 max 5629.3 median 5629.5 stddev 0.0
Connection time [ms]: connect 313.5
Connection length [replies/conn]: 3.000

Request rate: 0.7 req/s (1407.3 ms/req)
Request size [B]: 81.0

Reply rate [replies/s]: min 0.6 avg 0.6 max 0.6 stddev 0.0 (1 samples)
Reply time [ms]: response 315.1 transfer 0.0
Reply size [B]: header 186.0 content 0.0 footer 0.0 (total 186.0)
Reply status: 1xx=0 2xx=0 3xx=3 4xx=0 5xx=0

CPU time [s]: user 1.18 system 4.45 (user 20.9% system 79.1% total 100.0%)
Net I/O: 0.2 KB/s (0.0*10^6 bps)

Errors: total 1 client-timo 1 socket-timo 0 connrefused 0 connreset 0
Errors: fd-unavail 0 addrunavail 0 ftab-full 0 other 0
```

A hand-rolled client program doing `write`, `usleep`, `write` also reproduces the problem sporadically, with the success of triggering the issue strongly correlated with the sleep duration - shorter sleep makes the server more likely to receive two (or more) reqs at once, resulting in second one being ignored.

I've tested this with version 2 as well as current master.

Note: in the attack.sh script in the repo, a `wget` case with multiple HTTP/1.1 requests is tested, but wget does not pipeline the calls as far as I've seen, so that case is not triggered.

**Comment by lws-team** [comment] 2016-09-28 09:12
I can reproduce it... lws should deal with http/1.1 pipelining.

I'll study it tomorrow and reply here.

**Comment by dosvald** [comment] 2016-09-28 09:14
Thank you very much!

If I find anything more I'll put extra info here.

**Comment by lws-team** [comment] 2016-09-28 12:32
I can reproduce the problem with httperf.  But looking with tcpdump, it just shows one set of headers going out.

```
20:29:16.749653 IP localhost.54752 > localhost.7681: Flags [P.], seq 1:74, ack 1, win 16384, options [nop,nop,TS val 987824478 ecr 987824478], length 73
        0x0000:  4500 007d c55c 4000 4006 771c 7f00 0001  E..}.\@.@.w.....
        0x0010:  7f00 0001 d5e0 1e01 bafd c405 6986 162f  ............i../
        0x0020:  8018 4000 fe71 0000 0101 080a 3ae1 015e  ..@..q......:..^
        0x0030:  3ae1 015e 4745 5420 2f66 6176 6963 6f6e  :..^GET./favicon
        0x0040:  2e69 636f 2048 5454 502f 312e 310d 0a55  .ico.HTTP/1.1..U
        0x0050:  7365 722d 4167 656e 743a 2068 7474 7065  ser-Agent:.httpe
        0x0060:  7266 2f30 2e39 2e30 0d0a 486f 7374 3a20  rf/0.9.0..Host:.
        0x0070:  6c6f 6361 6c68 6f73 740d 0a0d 0a         localhost....
```

this gets a correct response and then nothing... in particular no second set of headers for a pipelined request.

Can you confirm if that's the same for you or something different at tcpdump?

**Comment by dosvald** [comment] 2016-09-28 13:21
Strange. doing live tcpdump to stdout does that to me too:

```
15:12:57.702800 IP (tos 0x0, ttl 64, id 63655, offset 0, flags [DF], proto TCP (6), length 123)
    127.0.0.1.52694 > 127.0.0.1.8843: Flags [P.], cksum 0xfe6f (incorrect -> 0xfa01), seq 1:72, ack 1, win 16384, options [nop,nop,TS val 15948780 ecr 15948780], length 71
E..{..@.@.C..........."....Jj.....@..o.....
..[...[.GET /style.css HTTP/1.1
User-Agent: httperf/0.9.0
Host: localhost


15:12:57.704491 IP (tos 0x0, ttl 64, id 49004, offset 0, flags [DF], proto TCP (6), length 213)
    127.0.0.1.8843 > 127.0.0.1.52694: Flags [P.], cksum 0xfec9 (incorrect -> 0xa132), seq 1:162, ack 143, win 342, options [nop,nop,TS val 15948781 ecr 15948780], length 161
E....l@.@.|........."...j..........V.......
..[...[.HTTP/1.1 200 OK
[...]
```

Doing `tcpdump -w` to a file and then `tcpdump -r` shows two requests pipelined before first response. Wireshark prints correctly even while capturing though.

```
reading from file /tmp/a.pcap, link-type EN10MB (Ethernet)
15:12:47.868605 IP localhost.localdomain.52692 > localhost.localdomain.8843: Flags [S], seq 619519284, win 16384, options [mss 65495,sackOK,TS val 15945830 ecr 0,nop,wscale 0], length 0
	0x0000:  4500 003c 4d52 4000 4006 ef67 7f00 0001  E..<MR@.@..g....
	0x0010:  7f00 0001 cdd4 228b 24ed 1d34 0000 0000  ......".$..4....
	0x0020:  a002 4000 fe30 0000 0204 ffd7 0402 080a  ..@..0..........
	0x0030:  00f3 5066 0000 0000 0103 0300            ..Pf........
15:12:47.868618 IP localhost.localdomain.8843 > localhost.localdomain.52692: Flags [S.], seq 3023451930, ack 619519285, win 43690, options [mss 65495,sackOK,TS val 15945830 ecr 15945830,nop,wscale 7], length 0
	0x0000:  4500 003c 0000 4000 4006 3cba 7f00 0001  E..<..@.@.<.....
	0x0010:  7f00 0001 228b cdd4 b436 371a 24ed 1d35  ...."....67.$..5
	0x0020:  a012 aaaa fe30 0000 0204 ffd7 0402 080a  .....0..........
	0x0030:  00f3 5066 00f3 5066 0103 0307            ..Pf..Pf....
15:12:47.868630 IP localhost.localdomain.52692 > localhost.localdomain.8843: Flags [.], ack 1, win 16384, options [nop,nop,TS val 15945830 ecr 15945830], length 0
	0x0000:  4500 0034 4d53 4000 4006 ef6e 7f00 0001  E..4MS@.@..n....
	0x0010:  7f00 0001 cdd4 228b 24ed 1d35 b436 371b  ......".$..5.67.
	0x0020:  8010 4000 fe28 0000 0101 080a 00f3 5066  ..@..(........Pf
	0x0030:  00f3 5066                                ..Pf
15:12:47.868664 IP localhost.localdomain.52692 > localhost.localdomain.8843: Flags [P.], seq 1:72, ack 1, win 16384, options [nop,nop,TS val 15945830 ecr 15945830], length 71
	0x0000:  4500 007b 4d54 4000 4006 ef26 7f00 0001  E..{MT@.@..&....
	0x0010:  7f00 0001 cdd4 228b 24ed 1d35 b436 371b  ......".$..5.67.
	0x0020:  8018 4000 fe6f 0000 0101 080a 00f3 5066  ..@..o........Pf
	0x0030:  00f3 5066 4745 5420 2f73 7479 6c65 2e63  ..PfGET./style.c
	0x0040:  7373 2048 5454 502f 312e 310d 0a55 7365  ss.HTTP/1.1..Use
	0x0050:  722d 4167 656e 743a 2068 7474 7065 7266  r-Agent:.httperf
	0x0060:  2f30 2e39 2e30 0d0a 486f 7374 3a20 6c6f  /0.9.0..Host:.lo
	0x0070:  6361 6c68 6f73 740d 0a0d 0a              calhost....
15:12:47.868668 IP localhost.localdomain.8843 > localhost.localdomain.52692: Flags [.], ack 72, win 342, options [nop,nop,TS val 15945830 ecr 15945830], length 0
	0x0000:  4500 0034 677d 4000 4006 d544 7f00 0001  E..4g}@.@..D....
	0x0010:  7f00 0001 228b cdd4 b436 371b 24ed 1d7c  ...."....67.$..|
	0x0020:  8010 0156 fe28 0000 0101 080a 00f3 5066  ...V.(........Pf
	0x0030:  00f3 5066                                ..Pf
15:12:47.868677 IP localhost.localdomain.52692 > localhost.localdomain.8843: Flags [P.], seq 72:143, ack 1, win 16384, options [nop,nop,TS val 15945830 ecr 15945830], length 71
	0x0000:  4500 007b 4d55 4000 4006 ef25 7f00 0001  E..{MU@.@..%....
	0x0010:  7f00 0001 cdd4 228b 24ed 1d7c b436 371b  ......".$..|.67.
	0x0020:  8018 4000 fe6f 0000 0101 080a 00f3 5066  ..@..o........Pf
	0x0030:  00f3 5066 4745 5420 2f73 7479 6c65 2e63  ..PfGET./style.c
	0x0040:  7373 2048 5454 502f 312e 310d 0a55 7365  ss.HTTP/1.1..Use
	0x0050:  722d 4167 656e 743a 2068 7474 7065 7266  r-Agent:.httperf
	0x0060:  2f30 2e39 2e30 0d0a 486f 7374 3a20 6c6f  /0.9.0..Host:.lo
	0x0070:  6361 6c68 6f73 740d 0a0d 0a              calhost....
15:12:47.868681 IP localhost.localdomain.8843 > localhost.localdomain.52692: Flags [.], ack 143, win 342, options [nop,nop,TS val 15945830 ecr 15945830], length 0
	0x0000:  4500 0034 677e 4000 4006 d543 7f00 0001  E..4g~@.@..C....
	0x0010:  7f00 0001 228b cdd4 b436 371b 24ed 1dc3  ...."....67.$...
	0x0020:  8010 0156 fe28 0000 0101 080a 00f3 5066  ...V.(........Pf
	0x0030:  00f3 5066                                ..Pf
15:12:47.869633 IP localhost.localdomain.8843 > localhost.localdomain.52692: Flags [P.], seq 1:162, ack 143, win 342, options [nop,nop,TS val 15945831 ecr 15945830], length 161
	0x0000:  4500 00d5 677f 4000 4006 d4a1 7f00 0001  E...g.@.@.......
	0x0010:  7f00 0001 228b cdd4 b436 371b 24ed 1dc3  ...."....67.$...
	0x0020:  8018 0156 fec9 0000 0101 080a 00f3 5067  ...V..........Pg
	0x0030:  00f3 5066 4854 5450 2f31 2e31 2032 3030  ..PfHTTP/1.1.200
...
```

Looking more closely at the first (live) printout of tcpdump, I see that the GET is TCP seq 1-73 but the first ACK from server is for 143, which means the two requests together. So it's just tcpdump not printing that packet for some reason / bug?
```
tcpdump version 4.7.4
libpcap version 1.7.4
```

**Comment by lws-team** [comment] 2016-09-29 02:49
tcpdump will lose packets if it can't keep up.  I was aware of that and used redirect to capture it, but following your -w -r way, I can see the same result as you now, two discrete pipelined requests in two packets before the first response, the second on 14us after the first.

Whether they are coalesced or not at the transmitting side doesn't really matter, if the are both available to read by the time we read them, both will be read in one read action and the result is the same as if they went out coalesced in one packet.

Lws knows how to deal with this case and holds an rx buffer persistently in the ah.  If all the rx buffer is not used up by processing the first set of headers, the remainder will be used up with the next action, whether that be pipelined headers, or ws protocol rx if we upgraded etc.

Lws also understands that having a non-empty rx buffer after header processing is a reason to force service again without waiting for network activity (which may never come if the other side is waiting for us to service the second headers).

Everything is in place for it except that the function to "reset" an ah for reuse was always clearing the ah rx buffer down.  Some callers wanted that, eg when binding an ah to a new wsi.  But lws_http_transaction_completed() also calls it and while he wants to reset the ah state around header parsing, he wants to retain the rx buffer.  So I moved the ah rx buffer cleardown out of the reset function and to be the responsibility of the caller, and left it out of lws_http_transaction_completed().

Now the test completes immediately

```
$ httperf --server localhost --port 7681 --uri /favicon.ico --max-connections 1 --num-calls 20 --burst-length 2 --timeout 5
httperf --timeout=5 --client=0/1 --server=localhost --port=7681 --uri=/favicon.ico --max-connections=1 --send-buffer=4096 --recv-buffer=16384 --num-conns=1 --num-calls=20 --burst-length=2
httperf: warning: open file limit > FD_SETSIZE; limiting max. # of open files to FD_SETSIZE
Maximum connect burst length: 0

Total: connections 1 requests 20 replies 20 test-duration 0.003 s

Connection rate: 322.9 conn/s (3.1 ms/conn, <=1 concurrent connections)
Connection time [ms]: min 3.1 avg 3.1 max 3.1 median 3.5 stddev 0.0
Connection time [ms]: connect 0.2
Connection length [replies/conn]: 20.000

Request rate: 6457.7 req/s (0.2 ms/req)
Request size [B]: 73.0

Reply rate [replies/s]: min 0.0 avg 0.0 max 0.0 stddev 0.0 (0 samples)
Reply time [ms]: response 0.2 transfer 0.0
Reply size [B]: header 323.0 content 1406.0 footer 0.0 (total 1729.0)
Reply status: 1xx=0 2xx=20 3xx=0 4xx=0 5xx=0

CPU time [s]: user 0.00 system 0.00 (user 0.0% system 94.5% total 94.5%)
Net I/O: 11364.1 KB/s (93.1*10^6 bps)

Errors: total 0 client-timo 0 socket-timo 0 connrefused 0 connreset 0
Errors: fd-unavail 0 addrunavail 0 ftab-full 0 other 0
```

I pushed the patch on master and v2.0-stable please give it a go (libwebsockets.org is also updated to current master).

**Comment by lws-team** [comment] 2016-09-29 21:44
I assume it fixed your problem too, if not please reopen.

**Comment by dosvald** [comment] 2016-10-03 13:13
Hi. Thanks for the debugging, and general effort with libwebsockets.

Unfortunately this bug is still present but not so common.
Both v2.0-stable and current master are still affected.

I can now only reproduce it with test-server v1, both regular and extpoll variant, but not the libuv-using test-server-v2. In addition to test-server v1, I can reproduce it with a lws-using program written in style of test-server v1.

To reproduce I still run the httperf command, it just needs more tries to hit the bug. A greater `--num-calls` like 1000 or 10000 also helps.

Log:

```
[2016/10/03 12:09:45:7712] DEBUG: lws_read: incoming len 158  state 0
[2016/10/03 12:09:45:7712] PARSER: issuing 158 bytes to parser
[2016/10/03 12:09:45:7712] PARSER: WSI_TOKEN_NAME_PART 'G' (mode=0)
[2016/10/03 12:09:45:7712] PARSER: WSI_TOKEN_NAME_PART 'E' (mode=0)
[2016/10/03 12:09:45:7712] PARSER: WSI_TOKEN_NAME_PART 'T' (mode=0)
[2016/10/03 12:09:45:7712] PARSER: WSI_TOKEN_NAME_PART ' ' (mode=0)
...
[2016/10/03 12:09:45:7716] INFO: Method: GET request for '/'...
...
[2016/10/03 12:09:45:7717] DEBUG: lws_http_transaction_completed: wsi 0xf10870
[2016/10/03 12:09:45:7717] DEBUG: lws_set_timeout: 0xf10870: 0 secs
[2016/10/03 12:09:45:7717] INFO: lws_http_transaction_completed: wsi->more_rx_waiting=1
[2016/10/03 12:09:45:7717] INFO: lws_http_transaction_completed: 0xf10870: keep-alive await new transaction
[2016/10/03 12:09:45:7717] DEBUG: lws_read: thinks we have used 79
[2016/10/03 12:09:45:7717] INFO: lws_read: read_ok, used 79
[2016/10/03 12:09:45:7717] DEBUG: lws_server_socket_service: wsi 0xf10870: ah read rxpos 79, rxlen 158
```

Here lws gets stuck (strace shows it calling `epoll_wait`), while httperf waits for second response. Then httperf timeout passes. FIN from httperf arrives, triggering HUP but also parsing of the stale request:
```
[2016/10/03 12:09:50:7705] DEBUG: servicing fd 9 with ufd eventmask 1 R
[2016/10/03 12:09:50:7705] DEBUG: ufd HUP on 9
[2016/10/03 12:09:50:7705] DEBUG: fd=9, revents=17
[2016/10/03 12:09:50:7705] DEBUG: lws_server_socket_service: 0xf10870: rxpos:79 rxlen:158
[2016/10/03 12:09:50:7705] DEBUG: lws_read: incoming len 79  state 0
[2016/10/03 12:09:50:7705] PARSER: issuing 79 bytes to parser
[2016/10/03 12:09:50:7705] PARSER: WSI_TOKEN_NAME_PART 'G' (mode=0)
[2016/10/03 12:09:50:7705] PARSER: WSI_TOKEN_NAME_PART 'E' (mode=0)
[2016/10/03 12:09:50:7705] PARSER: WSI_TOKEN_NAME_PART 'T' (mode=0)
...
[2016/10/03 12:09:50:7708] DEBUG: ERROR writing len 38 to skt fd 9 err -1 / errno 32
```
As request is processed too late, it gets errno 32 = EPIPE In last line.

**Comment by lws-team** [comment] 2016-10-03 13:41
> FIN from httperf arrives, triggering HUP but also parsing of the stale request:

This is actually a different bug: the original problem simply discarded the rx buffer.

The fact it doesn't have trouble with libuv-based test apps sounds like a big clue... it sounds like it might be related to the service forcing stuff, since it has all the pieces on the wsi already just doesn't go service it (until too late).

**Comment by lws-team** [comment] 2016-10-04 00:41
I aligned the default poll() handling for forced service with the libuv handling, which is more modern... please see if it helps.

**Comment by dosvald** [comment] 2016-10-04 08:57
Checking with tesr-server in master seems it is now okay with multiple pipelined calls.
However, with the new commit, doing a request for a not-found (404) resource results in lwsts hanging at 100%CPU in an infinite loop:
```
lwsts[21894]: lws_http_serve: /404.html
    get  = /404.html
    host: = 192.168.1.100:7681
    http/1.1  = HTTP/1.1
    accept: = */*
    user-agent: = curl/7.50.3
lwsts[21894]: HTTP connect from 192.168.1.100
lwsts[21894]: test_server_fops_open: opening /usr/local/share/libwebsockets-test-server/404.html, ret -1, len 0
lwsts[21894]: Unable to open '/usr/local/share/libwebsockets-test-server/404.html'
lwsts[21894]: LWS_CALLBACK_HTTP closing
lwsts[21894]: lws_close_free_wsi: shutting down connection: 0x1231bc0 (sock 8, state 0)
lwsts[21894]: lws_set_timeout: 0x1231bc0: 5 secs
lwsts[21894]: lws_plat_service_tsi: done again
lwsts[21894]: lws_plat_service_tsi: done again
lwsts[21894]: lws_plat_service_tsi: done again
....
```

**Comment by lws-team** [comment] 2016-10-04 10:08
> Checking with tesr-server in master seems it is now okay with multiple pipelined calls.

Great.

> However, with the new commit, doing a request for a not-found (404) resource results in lwsts hanging at 100%CPU in an infinite loop:

I read that as lwsws.... there's no problem there.  I realized you meant the test server.

Following the problem it seems we just close the connection in the 1.x style test server if we meet something bad.  In the 2.x style plugin style, we return an error on the transaction and do any following pipelined headers.

Anyway when we close the connection, we do drop ah rx but not until late in the close action; the close action can return to the poll loop because he can send close packets, get responses etc.  I pushed a patch to drop them as soon as we indicate we want to close it the first time.  That fixes this one.

**Comment by dosvald** [comment] 2016-10-04 17:18
Yes, with the latest change in master, it doesn't loop any more.
Are all these going to into v2.o-stable as well?

**Comment by lws-team** [comment] 2016-10-05 00:51
The first patch is already on v2.0-stable.  I thought the other two would be hard to port, but actually the forced service consolidation work they rely on was already in v2.0 originally.  So they are also both pushed on v2.0-stable.

Crossing my fingers and closing again ^^

**Closed by lws-team** 2016-10-05 00:51 UTC

**Comment by dosvald** [comment] 2016-10-06 15:02
I see that the timing is unfortunate (v2.1 just went out), but the external poll case is stil affected with the httperf test.

I went about fixing it from test-server.c. but I can't do it without busy-looping on `lws_service`, which doesn't seem good. If polling is external, the loop needs a way to query lws library that, even though we just called lws_service_fd, and no new data came in since, `lws_service` should be called again to "force" service. That way, we would only busy-loop new rx data is there.
With libuv as far as I can see this is solved with the "idle" time,r and the latest commit put that into the internal polling as well.
However it would be better if no idle timer was needed, and instead lws signalled to the loop (be it libuv, lws's internal poll, or external poll) that there is still data in the buffers that hasn't been processed.
Another alternative would be for lws to loop internally. This would of course have the same trade-offs as the internal buffering / looping that lws does in cases of large writes.

I hope I'm just failing to see an easy way for extpoll to get the info that it needs?

**Comment by dosvald** [comment] 2016-10-06 17:39
As a hack, I tried exposing the lws_service_adjust_timeout function which checks for what we need, and checked it after `lws_service_fd` in test-server-extpoll.

As a proper solution, I think that new APIs need to be exposed to check per-FD if the associated wsi needs forced service. Ideally this would be an output parameter of `lws_service_fd`. Polling code would then know to re-service that fd/wsi.

**Comment by lws-team** [comment] 2016-10-06 19:31
Making a release is never at a good time... still we have to do it.

The tag is only a few hours old so I just stuck a patch to expose the two apis lws uses for this internally behind the release patch and reissued the tag.

```
/**
 * lws_service_adjust_timeout() - Check for any connection needing forced service
 * \param context:	Websocket context
 * \param timeout_ms:	The original poll timeout value.  You can just set this
 *			to 1 if you don't really have a poll timeout.
 * \param tsi: thread service index
 *
 * Under some conditions connections may need service even though there is no
 * pending network action on them, this is "forced service".  For default
 * poll() and libuv / libev, the library takes care of calling this and
 * dealing with it for you.  But for external poll() integration, you need
 * access to the apis.
 *
 * If anybody needs "forced service", returned timeout is zero.  In that case,
 * you can call lws_plat_service_tsi() with a timeout of -1 to only service
 * guys who need forced service.
 */
LWS_VISIBLE LWS_EXTERN int
lws_service_adjust_timeout(struct lws_context *context, int timeout_ms, int tsi);

/**
 * lws_plat_service_tsi() - Lowlevel platform-specific service api
 * \param context:	Websocket context
 * \param timeout_ms:	The original poll timeout value.  You can just set this
 *			to 1 if you don't really have a poll timeout.
 * \param tsi: thread service index
 *
 * For default poll() and libuv/ev, lws takes care of using this for you. and
 * you can ignore it.
 *
 * But for external poll() integration, you need access to this api to service
 * connections that need to be serviced but have no pending network activity.
 *
 * See lws_service_adjust_timeout() for more info.
 */
LWS_EXTERN LWS_VISIBLE int
lws_plat_service_tsi(struct lws_context *context, int timeout_ms, int tsi);
```

per-FD checks don't go to the heart of it, unless there's something different about extpoll in addition to "the heart of it".  The problem is if you put your single service thread in poll() or its equivalent, you are gone for some unbounded amount of time.  So even though when you come out of it you may see something needed forced service, by then it has been "stuck" for as long as the programmer told poll() to wait, if the system was otherwise idle.

So the main thing is to do any lws forced service first before network activity.  That doesn't require per-wsi checks, just the library helper to do all forced service, ie, lws_plat_service_tsi() with -1 timeout.

These things are on linked-lists internally, so it scales OK to check this.

**Comment by dosvald** [comment] 2016-10-19 14:56
I just noticed that even before v2.1 there had also been `lws_service_tsi`, which has the same signature, and in fact calls into `lws_plat_service_tsi` itself.

Should the `lws_plat_service_tsi` be deprecated in favor of `lws_service_tsi`? Perhaps the exposing of the (currently duplicate) `_plat_` version done deliberately because some other (additional processing, checking not wanted in forced-service case) code might be planned and added to `lws_service_tsi`, in which case we want to be prepared by having "low-level" and "high-level" servicing APIs?

**Comment by lws-team** [comment] 2016-10-20 01:18
Hum no there is no difference between the public and the _plat_ version at the moment, the lws_service_tsi() just calls through to the plat implementation.  So it does look redundant.

This should sort it cleanly?

https://github.com/warmcat/libwebsockets/commit/a3a5a8c0df42ccc032015dd291c37d9778df073c
